### ISSUE TITLE
Date and Time picker at same time??

### ISSUE THREAD

**Issue by wserpas** [wdullaer/MaterialDateTimePicker#100]
Please i want select date an time at same time like 01/01/2015 08:49

How a i can do that?

**Comment by wdullaer** [comment]
Here's some things I've seen in the wild:
* Show the timepicker after a data has been selected
* Use two buttons: one to pick the time and one to pick the date
* Show a tabbed dialog with each picker in a tab

In short: be creative! ;-)

**Comment by maelfosso** [comment]
I also want the same thing

Please How to realise the third option @wdullaer with this library ?
