### ISSUE TITLE
Datepicker view cut on top and bottom on small screen size

### ISSUE THREAD

**Issue by MrBrightside29** [wdullaer/MaterialDateTimePicker#101]
On my old smartphone with a 3.5 inch display the datepicker view gets cut on top and bottom.

![screenshot_2015-09-26-13-42-21](https://cloud.githubusercontent.com/assets/6217462/10117398/fb66e9cc-6455-11e5-816d-14787d893a72.png)

**Comment by wdullaer** [comment]
I'm aware that the current design on lower resolution screens is not perfect.
