### ISSUE TITLE
Multiple time picker on same activity

### ISSUE THREAD

**Issue by wserpas** [wdullaer/MaterialDateTimePicker#102]
I need to set two time, starter and end time, but i don't know to manage onTimeSet for each time picker

Any solución???

**Comment by wdullaer** [comment]
One way is to use [anonymous inner classes](http://docs.oracle.com/javase/tutorial/java/javaOO/anonymousclasses.html)

**Comment by wserpas** [comment]
Can you give me an example??

**Comment by varadmondkar** [comment]
@wdullaer anonymous inner class worked thank you :+1:
