### ISSUE TITLE
ViewPager PagerTitleStrip are gone when using verson 1.5.2

### ISSUE THREAD

**Issue by nomanr** [wdullaer/MaterialDateTimePicker#105]
I've used this library version 1.4.1 and it works good. But as you updated the library and added multiple theme support I updated it to verson 1.5.2. Your library works very good but the titles are my viewpager are gone after doing so. I checked everything and issues arises only when I use 1.5.2 version of this library.

**Comment by wdullaer** [comment]
Can you show me a screenshot and a code snippet?
I have very little to go on here.

**Comment by NomanR** [comment]
Okay. 
Only here I've used the library 
    public static DatePickerDialog buildDatePickerDialog(Context context, final TextView
            textView, int color) {
           Calendar now = Calendar.getInstance();
           DatePickerDialog dialog = DatePickerDialog
                .newInstance((DatePickerDialog.OnDateSetListener) context,
                        now.get(Calendar.YEAR),
                        now.get(Calendar.MONTH),
                        now.get(Calendar.DAY_OF_MONTH));
           dialog.setOnDateSetListener(new DatePickerDialog.OnDateSetListener() {
               @Override
               public void onDateSet(DatePickerDialog datePickerDialog, int year, int month, int
                    date) {
                   textView.setText(parseDate(date + "/" + (month + 1) + "/" + year));
               }
           });
      //  dialog.setAccentColor(context.getResources().getColor(color));
           return dialog;
   }
I compile this version 
     compile 'com.wdullaer:materialdatetimepicker:1.4.1'
I get this result on my screen.
![screenshot_2015-09-30-10-53-38](https://cloud.githubusercontent.com/assets/8149827/10185538/8689f3b4-6762-11e5-8e25-10b5ec3fad24.png)
As you can see Titles are visible. Everything is fine. 

But later I wanted the multiple theme support, I can change accent color. I used this version.
      compile 'com.wdullaer:materialdatetimepicker:1.5.2' 
And the titles were gone. Result is shown below.
![screenshot_2015-09-30-10-56-50](https://cloud.githubusercontent.com/assets/8149827/10185556/ca5a9ce2-6762-11e5-8543-21fe03d8db13.png)

I dont know why this is effecting my ViewPager. 
In case you are interested in ViewPager XML.

  <android.support.v4.view.ViewPager
        android:id="@+id/registrationsPager"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:layout_centerInParent="true"
        android:overScrollMode="never"
        >

        <android.support.v4.view.PagerTitleStrip
            android:id="@+id/pager_title_strip"
            style="@style/ViewPagerTitle"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="top"
            />
    </android.support.v4.view.ViewPager>

**Comment by wdullaer** [comment]
I think this is due to your theme setup.

1. Are you sure your titles are gone and not just white?
2. We removed some dummy themes from this library. They weren't used, but they were defined and could mess with the overwrite order of the themes in your app.

Try to remove the `@style/viewPagerTitle` in the xml and see if they reappear. (I know that is not a proper solution, but it should give you something to work with)

**Comment by NomanR** [comment]
Yes I am sure they are gone. As you can see in screenshots. The layout below titles moved a bit up when titles are invisible.
Okay let me try.

**Comment by NomanR** [comment]
Nope it doesn't. I think I've to stick with the old version of the library , sad unable to use the theme feature.

**Comment by wdullaer** [comment]
This is the commit which I think is causing your issue:
https://github.com/wdullaer/MaterialDateTimePicker/commit/dd313b65d8eb72582fa312918c5b828e479eee34

I can't think of anything else which could have system wide impact.

**Comment by NomanR** [comment]
I didn't get it how this could have effected the whole app. 
I created a new project and implemented a `ViewPager` with titles. Right when I compiled your library again titles were gone.

**Comment by wdullaer** [comment]
Do they show when you swipe to another page?
I found this bug: https://code.google.com/p/android/issues/detail?id=183127 which seems to be related.

I bumped the version of the support library to 23.0.0 for the 1.5 releases

**Comment by NomanR** [comment]
Nope they don't show at all. Titles are not invisible, they are just gone.

**Comment by wdullaer** [comment]
Do please read through that android bug report.
Most people seem to report that they are gone, but get added when you swipe to another page in your viewpager.
It is a bug in the support-v4 library this library depends on. v1.4.x uses an older version of that library which doesn't have this bug.

All in all, this makes me about 85% certain that this is your issue. (which I won't be able to solve until google fixes the support library)

**Comment by NomanR** [comment]
Okay thanks. I'll look into it and will let you know.

**Comment by NomanR** [comment]
Yep you are right. The bug is in support library.

**Comment by wdullaer** [comment]
I'm not depending on any new features of the support library.
You could fork it, just change the version in the dependencies back to 22.0.1 and depend on that version in your app for now.

I'll follow the bug report and close this one when google fixes it

**Comment by NomanR** [comment]
Okay no problem. I'll wait for the fix unless there is no fix when I am going to release my app then I'll fork it and will make changes accordingly. Thanks.

**Comment by wdullaer** [comment]
I saw that this was fixed in v23.1.0 of the support library
Unfortunately I just released a new version of this library before I noticed.
I will be included in the next release (early next week if nobody eats my time this weekend)
