### ISSUE TITLE
setMaxDate does not prevent max date picked when changing year

### ISSUE THREAD

**Issue by digithree** [wdullaer/MaterialDateTimePicker#106]
In v1.51

The method setMaxDate greys out dates after the date specified and prevents the user from selecting these dates by clicking on the greyed out date number. However if the user sets to a day/month in a previous year and then advances the year by clicking year and selecting the next year, the unelectable date will be highlighted and user is allowed to click OK to accept this.

**Comment by wdullaer** [comment]
Good catch.
I already fixed some edge cases in the original code when I updated this a while ago, but this one is new.

Just a quick question: what would you expect to happen when you select a higher year in the year picker?
Do I discard your date selection and set it to the maxDate?
Or do I not render the next year when it would push the currently selected date beyond the maxDate? (That would lead to situations where 2015 would render if you currently have 01-Oct selected, but not if you have 02-Oct selected and the maxDate is 01-Oct-2015)

**Comment by digithree** [comment]
Indeed! The options seem to be
1. Disable year picker if current date + 1 year is > max date
2. Allow year picker for current date year + 1 but set date to max date if current date + year > max date
3. Allow year picker for current date year + 1, set date to current date + 1 year but disable OK button.

None of them seems ideal to me however. A compromise might be to do 2 but animate setting the date backwards to max date from current date + 1 year to emphasise that it is beyond max date. So process could be
* Select year picker
* Pick next year
* Date is set to current date + 1 year, shown briefly to user
* Animate scrolling back to max date if max date < current date + 1 year

What do you think?

**Comment by wdullaer** [comment]
I'll probably go for 2.
Animating this is a nice idea, but I have no idea how hard that would be to do.

Thanks for the input!

**Comment by digithree** [comment]
Thanks, is this available on Maven-central yet?

**Comment by wdullaer** [comment]
Not yet.
I'll try to publish the latest version today or tomorrow.
