### ISSUE TITLE
DatePicker Title

### ISSUE THREAD

**Issue by krishnameena** [wdullaer/MaterialDateTimePicker#109]
There should be a title when we open the datepicker dialog like "Select Date"

**Comment by krishnameena** [comment]
Thanks but that is not reflected in the gradle file. I think for that you
have to increase gradle version.

Thanks & Regards,

Krishna Meena

**Comment by wdullaer** [comment]
I fixed it in master, which is why the issue is closed.

I have yet to release a new version to maven central.
You can wait for that or check out the code in master

**Comment by krishnameena** [comment]
Ok thanks.

Thanks & Regards,

Krishna Meena
