### ISSUE TITLE
Chinese environment displayed error

### ISSUE THREAD

**Issue by wangxin05** [wdullaer/MaterialDateTimePicker#11]
In the Chinese environment, the date displayed incorrectly Title week, all displayed as "星".

**Comment by wdullaer** [comment]
I'm not sure I fully understand: are you talking about the labels of the day in DatePickerDialog above the calendar?

**Comment by wangxin05** [comment]
![Uploading 3712C689-0CD5-4D79-9103-079575FEC5D7.jpg . . .]()

**Comment by wangxin05** [comment]
![3712c689-0cd5-4d79-9103-079575fec5d7](https://cloud.githubusercontent.com/assets/1560411/6978122/acdc5e9a-d9fe-11e4-8dd2-b7b3dbc9574e.jpg)

**Comment by wdullaer** [comment]
I'm substringing those to 1 character. That gives something like: M T W T F S S in English
I suppose that the first character is identical across the days of the week in Chinese.

What would you expect to see there?
