### ISSUE TITLE
Pressed state on AM/PM is not respecting the set color

### ISSUE THREAD

**Issue by Jawnnypoo** [wdullaer/MaterialDateTimePicker#110]
This is something I introduced when changing the lib to support custom colors. I'll take a look into it soon and see what can be done. Just wanted to document it here

![screenshot_2015-10-12-16-27-08](https://cloud.githubusercontent.com/assets/1459320/10439251/3c24c632-70fe-11e5-8de9-0ea3606affac.png)

**Comment by Jawnnypoo** [comment]
Update: this only occurs if you call setAccentColor on the dialog manually.

**Comment by wdullaer** [comment]
Can you check the latest version from master? I was refactoring this and I
vaguely remember fixing this while looking through that piece of the code.

Op di 13 okt. 2015 00:37 schreef John <notifications@github.com>:

**Comment by wdullaer** [comment]
I just reviewed my changes, this should be fixed in master. Can you confirm that?

**Comment by Jawnnypoo** [comment]
Hmm yeah I believe you are correct. Disregard then! Looking forward to the next release!
