### ISSUE TITLE
How to avoid FROM and TO option in calender

### ISSUE THREAD

**Issue by NikhilAndroidDev** [wdullaer/MaterialDateTimePicker#111]

**Comment by wdullaer** [comment]
I'm sorry, but I really don't understand the question

**Comment by NikhilAndroidDev** [comment]
![device-2015-10-22-122602](https://cloud.githubusercontent.com/assets/13031698/10658811/226416be-78b8-11e5-8730-2c0dab25f107.png)

I think now you understood my point . i want the user to select only a single date instead of FROM date and TO date . All i wanted is to avoid that FROM and TO

**Comment by NikhilAndroidDev** [comment]
![device-2015-10-22-122602](https://cloud.githubusercontent.com/assets/13031698/10658987/b986bd98-78b9-11e5-9af0-2d3e7a6da4aa.png)

I think now you understood my point . i want the user to select only a single date instead of FROM date and TO date . All i wanted is to avoid that FROM and TO

**Comment by wdullaer** [comment]
Can you show me the code you are using to generate this dialog.
I have no idea how you make those From and To tabs appear to be honest. Seems like there is a hidden feature :-)

**Comment by PavelSynek** [comment]
Looks like he's using https://github.com/borax12/MaterialDateRangePicker :)

**Comment by NikhilAndroidDev** [comment]
Sorry Guys . It was all my mistake . Hey PavelSynek thanks for the light (Now a days Im messing up with lots of libs , thats why ) and thank you  wdullaer .  I tried both lib in same project but ended up like these 



 java.lang.ClassCastException: com.borax12.materialdaterangepicker.date.AccessibleDateAnimator cannot be cast to com.wdullaer.materialdatetimepicker.date.AccessibleDateAnimator
                                                              at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:274)
                                                              at android.app.Fragment.performCreateView(Fragment.java:2114)

**Comment by wdullaer** [comment]
Try a build clean first
