### ISSUE TITLE
Not usable on small screens

### ISSUE THREAD

**Issue by phylypp** [wdullaer/MaterialDateTimePicker#112]
The dialog is too large for small and medium screens. On small screens the OK button is not visible. I think the problem increased since last update. Is it just me or is it a bug?

![time_small](https://cloud.githubusercontent.com/assets/4163776/10699084/92fb9c88-79b4-11e5-9da7-0c9a97495978.png)
![time_medium](https://cloud.githubusercontent.com/assets/4163776/10699086/92ff1b10-79b4-11e5-86a3-fa23913d3bf5.png)
![time_medium_vertical](https://cloud.githubusercontent.com/assets/4163776/10699085/92fc6640-79b4-11e5-869d-75730c6b5476.png)

Original Android dialogs:
![time_vertical_original](https://cloud.githubusercontent.com/assets/4163776/10699089/a41a1fee-79b4-11e5-9376-5499bce1c8f9.png)
![time_small_original](https://cloud.githubusercontent.com/assets/4163776/10699090/a4315da8-79b4-11e5-8455-fd059a87be84.png)

**Comment by wdullaer** [comment]
What resolution is that?
I remark that even the original dialog doesn't show properly here.

**Comment by phylypp** [comment]
Android 6.0 (API level 23), 3.2'' QVGA (ADP2), 320x480px mdpi, 160dpi
Android 6.0 (API level 23), 2.7'' QVGA, 240x320px ldpi, 120dpi

I tried with emulators. Do you think these screen sizes do not exist? I am worried, since with older versions of your lib some people were not able to see the OK button.

**Comment by wdullaer** [comment]
I am for the nexus one screen resolution as the minimum supported (480×800 px 254 ppi)

Especially the date picker had some issues on smaller resolutions, but they should now be useful on the nexus one / nexus S resolution.

It's still my intention to make the buttons always show on top, but I didn't get around to that yet.

**Comment by phylypp** [comment]
Thanks for your help! I think I will just fall back to the old pickers for small screens. The poor guys with small devices will have to live with it...

**Comment by wdullaer** [comment]
I try to accommodate it all as best as possible.
Once I get around to implementing the new material design pickers (which google seems to have tried to put in android M) things should improve even more. The design is less hungry in vertical space compared to the one I currently have in this library.
