### ISSUE TITLE
Bypassing max date

### ISSUE THREAD

**Issue by PavelSynek** [wdullaer/MaterialDateTimePicker#113]
It is possible to bypass setMaxDate by going one year back, selecting a day after max date and switching back to the current year. It may be possible to do that with setMinDate too, haven't checked.

**Comment by wdullaer** [comment]
Do you have the latest version?
I fixed this big a few releases ago.

Op di 27 okt. 2015 14:24 schreef Pavel Synek <notifications@github.com>:

**Comment by PavelSynek** [comment]
Oh it was fixed in the 1.5.4 release, I didn't get to update it yet, thanks!
