### ISSUE TITLE
Remove android.permission.VIBRATE from Library

### ISSUE THREAD

**Issue by vanniktech** [wdullaer/MaterialDateTimePicker#116]
In my opinion this library should not have the VIBRATE permission since vibration is optional and can be turned off. Correct me if I'm wrong in that please.

If one app includes the library and does not want the permission it'll get added to the app and hence the user has to manually update the app since it requires a new permission.

**Comment by wdullaer** [comment]
If you really don't want the vibrate permission you can the following to the manifest of your application
```xml
<uses-permission android:name="android.permission.VIBRATE" 
  tools:node="remove" />
```
It's all about setting good defaults: if I don't add the permission to this library I will be closing two tickets a day on why the vibrate function doesn't work.

**Comment by vanniktech** [comment]
Okay understandable. I did not know that you can remove permissions. Thanks for that!

**Comment by wdullaer** [comment]
You live and you learn right ;-)
