### ISSUE TITLE
Adding v2 to a project produces this error

### ISSUE THREAD

**Issue by Mitchlol** [wdullaer/MaterialDateTimePicker#117]
```
Error:(123, 13) Failed to resolve: com.android.support:support-v4:23.1.0
Install Repository and sync project
Show in File
Show in Project Structure dialog
```
To reproduce:
1) add ```compile 'com.wdullaer:materialdatetimepicker:2.0.0'``` to your project
2) press the gradle sync button
3) see error

Disclaimer:
This is my first time trying the project, literally just started following the instructions 5 min ago (Ok, maybe i spent an hour or two trying to figure out why gradle couldn't find packages i have installed, and downloading updates to arbitrary things), but 1.5.4 seems to work fine, and 2.0.0 fails.

Cheers!

**Comment by wdullaer** [comment]
Th error says you don't have the correct version of the support library
installed. Click on the link in the error to make android studio download
the required library.

Let me know if that doesn't fix your error or if the error changes.

Op wo 4 nov. 2015 23:28 schreef Mitchell Lustig <notifications@github.com>:

**Comment by Mitchlol** [comment]
Clicking the error gives another error, as it wont install a package i already have installed. I believe your aar needs to include its dependancies.

**Comment by wdullaer** [comment]
I tested this on 3 different machines, including a fresh VM, and I cannot reproduce this. The dependencies are resolved correctly on all of them.
Version 2.0.0 uses the exact same build chain as all the previous versions.

I really suggest you take a closer look at your build environment (try a build clean or start from a fresh environment).

**Comment by Mitchlol** [comment]
Deleted my entire SDK folder, re-downloaded everything from scratch. Fixed the issue!

Sorry for the waste of time. *slithers into a dark corner*

**Comment by wdullaer** [comment]
No worries, these things happen with java ...
