### ISSUE TITLE
Hide field selectors

### ISSUE THREAD

**Issue by Raykud** [wdullaer/MaterialDateTimePicker#118]
It would be a great enhancement the ability to hide some field selectors, for instance using only month and day or year and month when displaying the dialog.

**Comment by wdullaer** [comment]
Except that the design makes absolutely no sense if you only want to select year and month, or day and month.

I would essentially be building completely new pickers for both these scenarios.

I'm strapped enough for time as it is maintaining this library, so I don't think I'll be doing this anytime soon.
