### ISSUE TITLE
No Zero displayed when time picked is like 06:01 ?? 

### ISSUE THREAD

**Issue by thomaslc66** [wdullaer/MaterialDateTimePicker#12]
Hi, I use your TimePickerDialog to set alarm in one of my app. I've been looking forward in your code to find where you are getting the value back but i haven't find it. 

I want to change the way hour and minute below 10 are displayed. Because when you return 06 hour or 05 minutes we only have 6:5 and it's a bit confusing when it comes to hour/alarm

Can you tell me how can i change this??

Thanks

**Comment by wdullaer** [comment]
The callback of the TimePickerDialog returns an `int` not a `String`
It's your responsibility to format that.

```java
    /**
     * The callback interface used to indicate the user is done filling in
     * the time (they clicked on the 'Set' button).
     */
    public interface OnTimeSetListener {

        /**
         * @param view The view associated with this listener.
         * @param hourOfDay The hour that was set.
         * @param minute The minute that was set.
         */
        void onTimeSet(RadialPickerLayout view, int hourOfDay, int minute);
    }
```
