### ISSUE TITLE
How to use selectableTimes?

### ISSUE THREAD

**Issue by tuxmobil** [wdullaer/MaterialDateTimePicker#122]
Hi.
I just wanted to update the TimePicker in my app to use the setSelectableTimes() feature, but am
unsure how to use it. I want it to restrict only the minutes to { 0, 15, 30, 45 } but didn't found a 
TimePoint constructor for just minutes? Do I have to provide an array for the whole day (24 * 4),
or am I missing something?

Thanks.

**Comment by wdullaer** [comment]
You will have to provide the whole array. `setSelectableTime` does what the name says, it sets the times which are valid.

I might add some syntactic sugar around this to make it easier to set intervals, but in the current version this is it.
