### ISSUE TITLE
Is possible to change the the days label on the datepicker to longer strings?

### ISSUE THREAD

**Issue by unxavi** [wdullaer/MaterialDateTimePicker#123]
Hi,

Excelent library, really enjoyed. I have a question that I think it could be related to #11 but I am not sure.

When you are seeing the date picker in Catalan for example, you get this:

![dates](https://cloud.githubusercontent.com/assets/3817679/11060726/5641dbc6-87a2-11e5-89a2-a1bba3acadbc.PNG)

Of course all the days of the week in Catalan start with the letter "D", so this is the expected behavior. But Google is sorting this behavior using one more letter. For example in google calendar:

![google_calendar](https://cloud.githubusercontent.com/assets/3817679/11060777/b0b704dc-87a2-11e5-96d1-27f56726de5f.PNG)

Or in the alarm app:

![alarm](https://cloud.githubusercontent.com/assets/3817679/11060805/df47c28c-87a2-11e5-9804-8a47f4de7d9b.PNG)

So, the question is, is it possible to achieve this in the date picker dialog? So the users have a better lucking picker

thansk very much for the picker ;)

**Comment by unxavi** [comment]
Adding more information to this... the day’s labels in google calendar, in Spanish is the follow when using one letter:

![spanish days](https://cloud.githubusercontent.com/assets/3817679/11086171/93fa1986-884e-11e5-8d55-04261a5878d5.PNG)


The "Wednesday" day label is represented by "X" when the actual name is "Miercoles" that's because that's the correct representation of the day in Spanish.

In the date picker, because it use the first letter, the day is represented as "M" the same as the one before "Martes" that would be "Tuesday".

![spanish datepicker](https://cloud.githubusercontent.com/assets/3817679/11086188/d86085b0-884e-11e5-9130-42fc4a0a9d2c.PNG)

**Comment by wdullaer** [comment]
I'm aware that the current implementation doesn't work in all locales.

There are two ways to solve this: 
1. find a way to have the java Calendar class return a locale adjust single letter for a day (or two in the cases of Catalan or Chinese). Unfortunately I haven't figured this out yet.
2. build exceptions for locales where the current implementation breaks down. This is what I've done so far. Unfortunately I don't speak all languages in the world, so I rely on people like you to report these and let me know how it should be done.

**Comment by unxavi** [comment]
is cool, the library is very cool. 

What about an option to load into de dialog a char array for the week days label per locale. I mean, like i pass as a parameter the way is going to render in catalan or spanish when i create the dialog. At least it could be a workaround :cry:

**Comment by unxavi** [comment]
will you update the app with using the chars for catalan and spanish as described in the second option?

**Comment by wdullaer** [comment]
I'll add special cases for Catalan and Spanish.

**Comment by unxavi** [comment]
@wdullaer sweet mate :+1: :dancer:

**Comment by wdullaer** [comment]
I figured out the proper way to do this :-)

**Comment by unxavi** [comment]
thanks, thats a very good line of code...love the delete code. :+1:
