### ISSUE TITLE
DatePicker overlapview, serious bug

### ISSUE THREAD

**Issue by thuckechsu** [wdullaer/MaterialDateTimePicker#124]
![untitled](https://cloud.githubusercontent.com/assets/13575382/11165008/7f35019e-8b34-11e5-9c85-cf031129f92b.png)

On any size of screen, the day name is always overlap each others. Please fix it :)

**Comment by wdullaer** [comment]
This is an android version issue.
I'll have to treat API level < 18 seperately

**Comment by thuckechsu** [comment]
Tks for your reply.  How can I fix it without pulling your source code. On api > 18, the name of day only displays as the first letter. 
And by the way, there's onething I would like to improve is font size on large and x-large screen. The button Ok and Cancel look quite thin and small. Here is screenshot
![untitled1](https://cloud.githubusercontent.com/assets/13575382/11167563/f276c16e-8b99-11e5-9b3e-25c464a2a8f4.png)

I love your project so much. It's beautiful.

**Comment by wdullaer** [comment]
You can only fix this in the source code.
The single character day labels are the intended design

The dialog on tablets follows the material design specs, but I'll review it.
