### ISSUE TITLE
setmaxdate to 30 days in DatePickerDialog

### ISSUE THREAD

**Issue by shireen028** [wdullaer/MaterialDateTimePicker#125]
HI,
I am trying to set min and max date in DatePickerDialog. The max date should be 30 days from the min date. The min date works but I am not able to get the max date. I am sure this is too simple but may be I am missing some point.

public void show() {
    Calendar now = Calendar.getInstance();
 
    DatePickerDialog dpd = DatePickerDialog.newInstance(
            PostInfo.this,
            now.get(Calendar.YEAR),
            now.get(Calendar.MONTH),
            now.get(Calendar.DAY_OF_MONTH)
    );
 dpd.setMinDate(Calendar.getInstance());

    now.add(Calendar.DAY_OF_MONTH,30);
   
    dpd.setMaxDate(now.getInstance());

    dpd.show(getFragmentManager(), "Datepickerdialog");
}

**Comment by thuckechsu** [comment]
Try to use separate instance calendar of max date and min date. Those must be different.

**Comment by wdullaer** [comment]
`dpd.setMaxDate(now.getInstance());` should be `dpd.setMaxDate(now);`

**Comment by shireen028** [comment]
@wdullaer That worked like a magic. Thanks a lot.
