### ISSUE TITLE
Year Picker only mode

### ISSUE THREAD

**Issue by jintoga** [wdullaer/MaterialDateTimePicker#126]
Hello! Is there any way to make DatePicker allows only YearPicker view?

**Comment by wdullaer** [comment]
Not really.
The current design wouldn't make sense with just a year picker.
You could use a number spinner in a dialog. Or a simple dropdown.

**Comment by jintoga** [comment]
Thank you for the quick answer. Just letting you know your work helps a lot! :+1:
