### ISSUE TITLE
Please add support for onConfigurationChange.

### ISSUE THREAD

**Issue by D40298008** [wdullaer/MaterialDateTimePicker#128]
Hello,

I have a hybrid native and html5 app that mainly has one WebView activity.  It is common with browser activities to not re-create the whole view, but instead use onConfigurationChange() during rotations.  Can you please add support for rotating the dialogs without re-creating them?

Thanks.

**Comment by wdullaer** [comment]
Can you let me know what is not working right now?

**Comment by D40298008** [comment]
Sorry for the delay.  If you launch either of the pickers from an activity that does NOT re-create itself via the Android lifecycle (pause/stop/destroy/create/start/resume), the picker-dialogs will not rotate correctly.

Some activities are better to handle the rotation change themselves instead of destroying and re-creating themselves (commonly web-browsers or video players). This is done by implementing onConfigurationChanged():

http://developer.android.com/guide/topics/resources/runtime-changes.html#HandlingTheChange

**Comment by wdullaer** [comment]
I'll see what I can do, but the backlog is rather big, so don't expect anything soon.

**Comment by Nakrul** [comment]
add something like this:
```
	@Override
	public void onConfigurationChanged(final Configuration newConfig) {
		super.onConfigurationChanged(newConfig);
		ViewGroup viewGroup = (ViewGroup) getView();
		if (viewGroup != null) {
			viewGroup.removeAllViewsInLayout();
			View view = onCreateView(getActivity().getLayoutInflater(), viewGroup, null);
			viewGroup.addView(view);
		}
	}
```

for testing add in manifest:
`android:configChanges="orientation|screenSize"`

**Comment by emitchel** [comment]
Would be awesome to see @Nakrul 's fix in there.
