### ISSUE TITLE
Support for more languages?

### ISSUE THREAD

**Issue by SteveCampos** [wdullaer/MaterialDateTimePicker#132]

**Comment by wdullaer** [comment]
Such as?
The library supports some 60 different locales, inherited from the google project I forked it from.

If you feel some translations are missing or inaccurate, feel free to propose a pull request.

**Comment by SteveCampos** [comment]
Sorry, i am a dumb!

**Comment by wdullaer** [comment]
Don't feel like that.
It is a genuine request: if you have any specific remarks or requests for localisation, please share.
