### ISSUE TITLE
Set initial date for the date picker

### ISSUE THREAD

**Issue by shireen028** [wdullaer/MaterialDateTimePicker#133]
The android date picker has a method init to set an initial date for the datePicker dialog.

I want to set an initial selected date for this DatePicker. If I use setMin, it disables all the past dates. Is there any easy way to do this?

               //My date
                   Calendar cal = Calendar.getInstance();
                    cal.setTimeInMillis(l);
                   dday = cal.get(Calendar.DAY_OF_MONTH);
                    dmonth = cal.get(Calendar.MONTH);
                   dyear= cal.get(Calendar.YEAR);

               //datepicker dialog
               Calendar now = Calendar.getInstance();
                  DatePickerDialog dpd = DatePickerDialog.newInstance(
                MainActivity.this,
                now.get(Calendar.YEAR),
                now.get(Calendar.MONTH),
                now.get(Calendar.DAY_OF_MONTH)
                       );

**Comment by shireen028** [comment]
So I tried this  dpd.initialize(mCallBack,dyear,dmonth,dday);
It works but now I can't select any other date. please help

**Comment by shireen028** [comment]
I fixed it. I had to remove this line 
DatePickerDialog dpd = (DatePickerDialog)getFragmentManager().findFragmentByTag("Datepickerdialog")

from onResume()

**Comment by wdullaer** [comment]
That doesn't make any sense to me.
The default date is specified in the `newInstance()` method

```java
//datepicker dialog
Calendar now = Calendar.getInstance();
DatePickerDialog dpd = DatePickerDialog.newInstance(
    MainActivity.this,
    now.get(Calendar.YEAR),
    now.get(Calendar.MONTH),
    now.get(Calendar.DAY_OF_MONTH)
);
```
The now.get statements are your default selection.

You are not supposed to call the initialize method. I should check whether I can make that protected.

Fetching the dialog in `onResume` is required to reset the callbacks after the activity is recreated. If you remove it you'll notice that your callbacks no longer get called after an orientation change.

**Comment by shireen028** [comment]
OK but how am I supposed to get my user defined initial date if I don't use initialize method. The now.get statements won't allow me

**Comment by wdullaer** [comment]
I'm not sure I understand your problem.
The datepicker needs a default selection. The example set this to the current date, but you can set it to anything you like by passing the correct parameters.

How does the user define the initial date?

**Comment by mintheinwin** [comment]
how to setTypeFace font on the Title Text ?
pickerDialog.setTitle(mText);

**Comment by maxbaldrighi** [comment]
This is a pretty old thread...
Currently, as of version 3.4.0, method **initialize()** is still accessible.

I would like to instantiate the picker dialogs only once (I think it's better if we think about performance) and not to keep creating new instances every time a user wants to open the picker...
So I was looking for a method that allowed me just to reset values, and I found initialize().
While it seems to work with dates, on the contrary it won't reset the TimePicker at the wanted time.
I realized this, because (this is to me the more important issue) if I tap on cancel after setting the selector on a new time and I reopen the dialog, from the UI point of view the time displayed is the last selected, while the picker's **mInitialTime** value is correctly the one that we'd like...

Do you have any idea on how to solve this incongruence?

**Comment by wdullaer** [comment]
`initialize` was never meant to be public, but I wasn't paying attention when I initially released this and so it is. It's hard to turn this back (but maybe I should just bite the bullet).
The library assumes that you do create a new instance every time you need a picker.
I doubt this will have much performance impact (how many pickers do you need to show in a second?). 

I don't think there's anything you can do to make this work with the current API of the library. If you manage to get it to work, I'm happy to take a PR though.

**Comment by maxbaldrighi** [comment]
Thank you so much for your reply.
Now I have the whole picture, and yes, at least for now, I will instantiate every time the pickers.

PS. I've just submitted an issue related to this library about an odd behavior I'm experiencing. Thank you!

**Comment by wdullaer** [comment]
I'll try to make this assumption more clear in the Readme.
Maybe I'll spend some time on making sure reusing works in the future. Every now and then someone asks questions about this and it might just be less work to implement it than handle the issues ☺️

**Comment by VyMajoris** [comment]
So, in order for me to change the current selected date I must call newInstance and instantiate a new DatePicker?

**Comment by wdullaer** [comment]
There is no way to programatically update the selection once the Dialog is shown. Its purpose is for the user to select a date, you do not want to mess with that.

I recently made a few changes which should allow you to reuse picker instances, but it's not a scenario I'm actively trying to support.
The recommended way is to create a new picker every time you need to show one.

**Comment by VyMajoris** [comment]
Understood.

**Comment by zkurbonov** [comment]
Hello wdullaer, I have tried much about still no result in changing format of "MONTH" in DataPicker. When I select for example, 21 December 2017 it shows in my Edittext as 21 November 2017!! Searched from Stackoverflow, and there is written to add +1 (now.get(Calendar.MONTH) + 1), but it didnt help.  I understand that java.util.Calendar works with 0 index for months, but dont know how to change it to adapt to my case! 
Need your help!!!

**Comment by PrasadModi21** [comment]
How could we show previous selected(get from server) date along with new selected date that means previous date just show and unchanged for user and select other date including previous one.
following is sample url one of them is already highlighted(unchanged just for UI information for user to previous selected date.) and other one is selected by user. 
![u155](https://user-images.githubusercontent.com/34713663/34258073-637b6cc6-e682-11e7-910e-c2a1add5cede.jpg)

**Comment by wdullaer** [comment]
Please do not put new questions or issues in old ones. I can't easily find them here.

@zkurbonov this is just the way java Calendars work. Not an issue with this library. I suggest you read a book on java programming or try stackoverflow.

@PrasadModi21 try using setHighlighted days

**Comment by Karan197** [comment]
@wdullaer Please let me know if there is any way to Show year selection first.

**Comment by Karan197** [comment]
Like there is an option in Android widget https://stackoverflow.com/questions/38477118/show-year-selection-first-in-android-calendar-view/46223200#46223200

**Comment by Karan197** [comment]
Ahh!!! There is a method right there. Sorry for the silly query.

**Comment by abdulrehmank7** [comment]
Checkout this library https://arkapp.medium.com/ios-date-time-picker-for-android-93af45fdfaf0
