### ISSUE TITLE
How to check day of the selected date

### ISSUE THREAD

**Issue by sri4321** [wdullaer/MaterialDateTimePicker#138]
Is there any method to get day and month of selected date from date picker?i.eSunday, Monday....and April,May... Like that

**Comment by wdullaer** [comment]
Create a Calendar object with the output from the picker and read the day of the week from that

In the callback:
```java
Calendar selection = Calendar.newInstance();
selection.set(Calendar.YEAR, year);
selection.set(Calendar.MONTH, month);
selection.set(Calendar.DAY_OF_MONTH, day);

Log.debug("The user selected the following day of the week: " + selection.get(Calendar.DAY_OF_WEEK));
```

Or use a `SimpleDateFormatter` to render the Calendar object to a localised string
