### ISSUE TITLE
Set color doesn't work

### ISSUE THREAD

**Issue by dbikic** [wdullaer/MaterialDateTimePicker#139]
I tried changing accent color via method, global color accent and specifying color values but no mater which color I set it was always blue. Then I tried with older version of the lib, without changing my code and it worked fine.

**Comment by wdullaer** [comment]
Can you provide some code that fails?
Also: on which version is it failing?

**Comment by dbikic** [comment]
The newest, i reverted to 1.4.2. and it works fine. It could be a clash with some other lib.

**Comment by wdullaer** [comment]
I can't reproduce this behaviour based on your feedback.
You'll need so supply some code that reliably reproduces the issue if you want me to look into it.

**Comment by dbikic** [comment]
The older version of the lib is good enough for me. I'm closing this one, sorry for your trouble.

**Comment by wdullaer** [comment]
I'd prefer that you help me solve this, but it's your call I guess.

**Comment by goraga1** [comment]
Overriding colors not work , after changing gradle version  from 1.4.5 to 2.2

 <color name="mdtp_accent_color">#2f6900</color>
 <color name="mdtp_accent_color_dark">#998e13</color>
