### ISSUE TITLE
setCancelable(false) has no effect

### ISSUE THREAD

**Issue by geecko86** [wdullaer/MaterialDateTimePicker#14]
TimePickerDialog tpd = TimePickerDialog.newInstance(this, 21, 0, twentyFourHourStyle);
    tpd.setCancelable(false);
    tpd.show(getFragmentManager(), NIGHT_START_TIME_DIALOG_TAG);

This dialog should not have a cancel button..

Thanks for your library!

**Comment by wdullaer** [comment]
Good catch.

**Comment by geecko86** [comment]
Thanks! When do you plan on pushing it to Maven Central?

**Comment by wdullaer** [comment]
How about now? ;-)

I've noticed it can take a few hours before it becomes available on Maven Central after I've completed all the steps.
