### ISSUE TITLE
[Feature Request] Remove unselectable years/months

### ISSUE THREAD

**Issue by hitchan** [wdullaer/MaterialDateTimePicker#142]
Amazing work with this DatePicker. One thing I notice though is if I pass in a Calendar[] of selectable dates; for examle "January 1st, 2015" to "June 1st, 2015", the picker still shows July through December 2015 even though no dates are selectable in that range. Is there a way we can remove these unselectable months?

![capture](https://cloud.githubusercontent.com/assets/10233019/11991265/4d53a3e4-a9e6-11e5-95e5-8d79bae90f73.PNG)

**Comment by wdullaer** [comment]
Currently they can't be hidden.
I'm not sure if hiding the months leads to a good user experience, but I'll think about it (maybe as a separate flag)

**Comment by Mitchlol** [comment]
I would like this as well, the native implementation does this on new devices.

**Comment by Rainer-Lang** [comment]
+1

**Comment by GauthierRoomDotMe** [comment]
This feature would be amazing :+1:
