### ISSUE TITLE
Setting past date along with year range causes wrong month labels to be displayed

### ISSUE THREAD

**Issue by dimsuz** [wdullaer/MaterialDateTimePicker#143]
I create an MDTP dialog with date set to `24.12.1897` and `setYearRange(1895,2015)` and `setMaxDate(calendar.getInstance())` and I get the dialog presented in screenshot. Notice the year at top is set to 1897 - correctly, but the month labels display a year from future.

This seems to happen only for 'early' years of 20-th century or earlier, not so for 2000-s. Maybe has to do with pre- or post- 1970.

I may be able to investigate this further myself, but currently have no time, so will just report for now. Maybe you'll have a quick aha!-fix for that :)

Version of library I use is: `2.1.1`

![screenshot from 2015-12-24 13-08-36](https://cloud.githubusercontent.com/assets/42920/11994057/45532c18-aa41-11e5-8ccf-181dc860d521.png)

**Comment by wdullaer** [comment]
This is indeed an issue with pre 1970 dates.
It's a bug / limitation in the android framework Calendar implementation.
They fixed it in android 4.3 IIRC.

The only way properly fix it is to remove all dependencies of Calendar and plug in a 3rd party library which accounts for this.
Google's own apps often work around this by setting the minYear to 1970.

**Comment by dimsuz** [comment]
Hmm. Is there a way I could get it to look correct and be able to select the date pre 1970?

**Comment by dimsuz** [comment]
Actually I just found that sometimes dates pre-1970 are handled nicely. On the screen below you can see that it starts "messing up" at year 1902:

![screenshot from 2015-12-24 14-56-13](https://cloud.githubusercontent.com/assets/42920/11994862/d5f038a8-aa4e-11e5-8f59-2b9510c93d19.png)

**Comment by dimsuz** [comment]
Also it seems to affect only month names rendering. Choosing date and clicking OK produces the correct Calendar instance.

I suspect the following line is in charge (which converts date to millis prior to rendering it), but will need to clone and debug locally to be sure:

https://github.com/wdullaer/MaterialDateTimePicker/blob/master/library/src/main/java/com/wdullaer/materialdatetimepicker/date/MonthView.java#L456

**Comment by wdullaer** [comment]
The header (which looks ok in your examples) is formatted using `SimpleDateFormatter`.
If you swap out the line you highlighted for a `SimpleDateFormatter` you should probably be able to fix it I think.

**Comment by dimsuz** [comment]
Thanks, I will try it. Should I send PR if I succeed? Or do you prefer this to be a known limitation?

**Comment by wdullaer** [comment]
If you fix this, by all means send a PR.
I'm not always the fastest to integrate them, but I appreciate each and every one :-)

**Comment by wdullaer** [comment]
I've done some investigation and changing to SimpleDateFormatter will remove some localisation.
eg in Spanish it will currently display "deciembre de 2015", after changing to SimpleDateFormat it would just be "deciembre 2015".
There is a utility method which generates proper localised patterns for SimpleDateFormat but it's only available in API level 18+

Current versions of Android also do not exhibit this bug. (I'm willing to bet it was fixed in API level 18).

The only decent way to fix this, is to enumerate all possible languages, generate the proper pattern for them, save those as a localised string in the app and have SimpleDateFormat reference that.
This will take a bit of time though.

**Comment by dimsuz** [comment]
Interesting! So do you think that this issue is better to be dealt with on a per-application basis? I mean putting all those patterns into this library's resources might not be the best idea... Or it maybe the best in current circumstances, but not a very clean one (it's how it usually goes when fixing an unavoidable bug)...

**Comment by wdullaer** [comment]
I'll probably add the localised patterns in the library.
I need to do a similar hack to support the current reference design of the pickers anyway.

**Comment by dimsuz** [comment]
That would be really great! I am not sure when I will have time to try to do it myself, but in case I will, I'll make a PR if you won't beat me to it :) Probably you'll make a greater thing here, knowing library internals and this much about localization, I have less experience in working with it...

**Comment by dimsuz** [comment]
Great! Many thanks!
