### ISSUE TITLE
Can support the left-right scroll ?Like the Android native materialDate view.  

### ISSUE THREAD

**Issue by fangzb** [wdullaer/MaterialDateTimePicker#144]
Can support the left-right scroll ? Like the Android native materialDate view.

**Comment by wdullaer** [comment]
Not on the short term.
I am experimenting with a version 2 design, but figuring out how I can avoid having 2 separate code bases is taking some time.

**Comment by fangzb** [comment]
All right , thanks always :)

**Comment by livotov** [comment]
Probably this could be supported transparently after migrating from ListView to RecyclerView by just swapping horizontal/vertical layout managers.

**Comment by wdullaer** [comment]
This has been added in the v3 release (with a change to RecyclerView)

**Comment by bernaferrari** [comment]
Where? @wdullaer

**Comment by wdullaer** [comment]
It seems this got stuck in a feature branch I forgot to merge.
Will do that shortly

**Comment by ChillingVan** [comment]
Hi, I download the code and use setScrollOrientation(int orientation) of DayPickerView. It seems that it works well. Could you expose this method?

**Comment by Flo354** [comment]
Hi @wdullaer, I still don't find the method. Where is it?

**Comment by marinaguimaraes** [comment]
Hi @wdullaer, I would like to use this version, but I can't find it. Was it merged already?

**Comment by karandeep26** [comment]
I cant also find the same.

**Comment by wdullaer** [comment]
because it hasn't been merged.
The branch contains some unrelated code that I don't want to release yet, so I either have to spend some time splitting it out or finishing it.
This will be next thing I work on, hopefully I find some time over the christmas holidays.
