### ISSUE TITLE
Dialogs are inconsistent about maintaining last selected date/time when re-opened.

### ISSUE THREAD

**Issue by Mitchlol** [wdullaer/MaterialDateTimePicker#147]
###### Use case:
1. Initialize dialog to current time.
1. Show dialog
1. Select a different time, and close dialog.
1. Re-show dialog.

###### Actual
```
Date Picker: Will reopen to the last picked date, unless you have rotated the device.
Time Picker: Will never remember the last picked time when reopened, and will always open to the initialized time.
```

###### Expected
```
Date Picker: Will always reopen to the last picked date.
Time Picker: Will always reopen to the last picked time.
```

**Comment by wdullaer** [comment]
I'm running under the assumption that you create a new instance each time you need to show a date picker and manage the state in the application in the mean time.

I'll keep this open. If it turns out to be sufficiently easy to fix I'll add it in, but it's not a scenario I'm actively testing.

**Comment by wdullaer** [comment]
I don't think I can make this work the way you like.
If the dialog is not shown, Android will not call its onSaveInstanceState callback. This means that you as the application developer will always be responsible for saving the Dialog state when configuration changes happen in case it is not shown.
At that point you can just as well save the output of the dialog and create a new instance.

I'm going to put this as a wontfix and add some explanation to the FAQ
