### ISSUE TITLE
Set picker primary color from code

### ISSUE THREAD

**Issue by JORDAN1998** [wdullaer/MaterialDateTimePicker#15]
I want to be able to change the theme color globally. I have a red theme, yellow theme, and green theme. 
Since I cant put any code in the styles.xml No matter what theme it stays default(red) instead of switching to yellow or green

**Comment by wdullaer** [comment]
I can see how setting the accent color from code can be useful. I'll see if I can add this in the next version.

Just on the side: it sounds like you're theming your entire app in code, which is a major horrorshow.
It is possible to switch themes at runtime, you just need to make sure you restart the current activity for the changes to take effect.
Take a look at this stackoverflow entry for some information on how to achieve that: http://stackoverflow.com/questions/18301554/android-change-app-theme-onclick

**Comment by JORDAN1998** [comment]
Thanks for the suggestion. Helped me alot :)

**Comment by JORDAN1998** [comment]
Please can you add changing the accent color by code soon I've been waiting since April it will be the icing on the cake for this library since I absolutely love what you have done thus far

**Comment by wdullaer** [comment]
This change is not as easy as it looks.
I have an idea on how to do this, but I estimate the work at about 2 days, aka a full weekend.

I don't think I'll be able to dedicate that amount of time to this until somewhere in August.

**Comment by JORDAN1998** [comment]
I understand it's difficult thank you for the eta and all the work you have
put into this library. What you have done is amazing and I hope some day I
can be as good as a coder as you.

**Comment by wdullaer** [comment]
Added in v1.5.0

**Comment by JORDAN1998** [comment]
Thank you so much!
