### ISSUE TITLE
Show TimePicker with 5 minutes intervals?

### ISSUE THREAD

**Issue by AamirAbro** [wdullaer/MaterialDateTimePicker#152]
How can I show TimePickerDialog with 5 minutes interval, So that user can only select 5, 10, 15 mins in radial time picker.

**Comment by mikeee324** [comment]
I had to do this and came up with this:  

    public static Timepoint[] generateTimepoints(int minutesInterval) {
        List<Timepoint> timepoints = new ArrayList<>();

        for (int minute = 0; minute<=1440; minute += minutesInterval) {
            int currentHour = minute / 60;
            int currentMinute = minute - (currentHour > 0 ? (currentHour * 60) : 0);
            if (currentHour == 24)
                continue;
            timepoints.add(new Timepoint(currentHour, currentMinute));
        }
        return timepoints.toArray(new Timepoint[timepoints.size()]);
    }
It's probably not the best way of doing it, but it does what I need.  
To use it just do:
    
    timePicker.setSelectableTimes(generateTimepoints(5)); // 5 Min interval
    timePicker.setSelectableTimes(generateTimepoints(10)); // 10 Min interval
    timePicker.setSelectableTimes(generateTimepoints(15));  // 15 Min interval

I've tried it with 5 and 15 minute intervals and it just greys out the ones inbetween.

**Comment by AamirAbro** [comment]
@mikeee324 thanks,
yah there does not seems to be any other way :) i ended up doing something like this with minTime checks.

**Comment by wdullaer** [comment]
This is currently the way to do it.

I might add this code in and expose some sugar method.
