### ISSUE TITLE
Two date pickers in one dialog?

### ISSUE THREAD

**Issue by anupsarode** [wdullaer/MaterialDateTimePicker#153]
I am developing an app for tablets and I need a date range selector for which I was thinking to use your awesome component. I need to have two date pickers side by side in one dialog, is it possible?

**Comment by wdullaer** [comment]
The dialogs can be used as plain fragments.
You can then use the child fragment manager to inflate them side by side in your Dialog (this puts restrictions on the API level)

Alternatively, someone made a range picker based off this library: https://github.com/borax12/MaterialDateRangePicker
