### ISSUE TITLE
Maven library does not have latest autoDismiss() feature

### ISSUE THREAD

**Issue by evalincius** [wdullaer/MaterialDateTimePicker#158]
The latest autoDismiss() feature is not in maven's 2.1.1 library of Material DateTime Picker.

**Comment by wdullaer** [comment]
It doesn't. I haven't released a new version since I added that feature.
I have been away from computers for a while. I'll try to release a new version this weekend

**Comment by wdullaer** [comment]
I have released a version containing this feature. It should be available on Nexus in a few hours.

**Comment by evalincius** [comment]
Thank you, great job by the way, I really like your library, it's easy to integrate, it's robust and looks good on all screen sizes I have tried.
