### ISSUE TITLE
[Feature request] Dialog title

### ISSUE THREAD

**Issue by geecko86** [wdullaer/MaterialDateTimePicker#16]
I know it's not in the original TimePickerDialog but a title would be very useful to me.

It would look (sort of) like this: ![this](https://dl.pushbulletusercontent.com/AUGFcPd9FY0bJzIw9XJcaG2GGdG55B9i/Screenshot_2015-04-05-04-24-39.png)

What do you think?

**Comment by wdullaer** [comment]
I hope that's a mock and not a screenshot of this library with the dark theme. If it is, I'll need to clean that up a bit!

I can see the usefulness, but it should fit the overall design. Unfortunately I'm not a good graphic designer, so this might take some time.

Alternatively, you might try extending the pickers. In `onCreateView` call the `super` method first, which gives you the current picker view and embed that in your own custom layout which has the title.

```java
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState) {
    // Have the library create the View with the picker
    View pickerView = super(inflater, container, savedInstanceState);
    // Inflate your own view which contains the title and room for the picker
    View parentView = inflater.inflate(R.layout.dialog_parent, container, false);
    // Add the picker to your layout
    ViewGroup container = (ViewGroup)parentView.find(R.id.container);
    container.addChild(pickerView);
    // Return your custom layout with the picker in
    return parentView;
}
```
This is just some code on top of my head, it will need some tweaking probably.

**Comment by geecko86** [comment]
No it's not from this library. it's from Talon for Twitter and the dev says he coded it himself.

The problem with just overriding onCreateView is that calling your static newInstance method will create a TimePickerDialog (without the overridden methods) no matter what.

**Comment by wdullaer** [comment]
I was just going to suggest that :-)

The screenshot looks nice.
The material design spec suggests that you align the title of a dialog left.

Adding this to the timepicker will be easy.
Adding it to the datepicker will require some thinking: it's already close to the max length. There's hardly any room for a title.

**Comment by geecko86** [comment]
Problem is that it only looks nice in portrait. For now it's really "hack"-y. Looking forward to a proper implementation. :)

**Comment by wdullaer** [comment]
The landscape versions have the same problem as the DatePicker: there is not enough space left to fit a title at the top.
Adding this will require more redesign than just adding an additional TextView at the top.
It'll take some time before I get around to working on this.

**Comment by geecko86** [comment]
Hey walt,

I actually really need this feature. Do you want a pull request or are you already working on it? :)

**Comment by wdullaer** [comment]
I haven't had a lot of spare time lately, so I didn't start working on this yet.

Like I mentioned: it will require some redesign of most of the components, because they're close to max height already see #17 .
If you need it urgent, it's probably best to give it a shot yourself.
