### ISSUE TITLE
Disable hour format when 24 hour mode is selected.

### ISSUE THREAD

**Issue by MustafaAdil** [wdullaer/MaterialDateTimePicker#162]
First of all this library is really helping me in my current project. Great work! 

There is a little problem, when 24 hour mode check box is selected,  additional hour format is showed in the outer circle. How to disable/hide that additional hour format?

**Comment by wdullaer** [comment]
I don't understand what you mean.
Can you show a screenshot and highlight what you think is wrong?

**Comment by MustafaAdil** [comment]
Here is the attached screenshot:
![hour](https://cloud.githubusercontent.com/assets/17173766/13035577/6ee0551c-d375-11e5-867a-be6ad01169e4.jpg)

How to hide the outer circle of hours(13,14,15 etc) ?

**Comment by wdullaer** [comment]
Disable 24hour mode.
The entire point of 24 hour mode is to show 13h, 14h etc.
