### ISSUE TITLE
Select only month and year

### ISSUE THREAD

**Issue by HyruleMaster5** [wdullaer/MaterialDateTimePicker#163]
Hi,

In my app, I want my user to be only able to select the year and the month at a certain place. Is there a possibility of parameter to set to disable the day selection?

Thanks

**Comment by wdullaer** [comment]
There is no such parameter.
The design of the dialog is meant to select days. It doesn't make a lot of sense when selecting just a month and a year.

You can easily use dropdowns for this.

**Comment by HyruleMaster5** [comment]
I get your point, the thing is, I can select months for a big range of years and having dropdown for that with my UI doesn't work well.. I'll find something else, thanks.
