### ISSUE TITLE
How to use setSelectableDays(Calendar[] )?

### ISSUE THREAD

**Issue by sammyrocz** [wdullaer/MaterialDateTimePicker#165]
How to use this function , do I have to pass the array of calendar ? 
I am new to android and  I haven't used the calendar class in android.
I read some tutorials and as far I know we cant create the array of Calendar class!!!!

**Comment by wdullaer** [comment]
Take a look at the sample app code in this repository.
You need to pass a `Calendar[]`, there's nothing stopping you from doing that.
