### ISSUE TITLE
ThrowsClassCastException in android.support.v4.app.Fragment

### ISSUE THREAD

**Issue by Haraprasad** [wdullaer/MaterialDateTimePicker#166]
java.lang.ClassCastException: android.support.v4.app.FragmentManagerImpl cannot be cast to com.wdullaer.materialdatetimepicker.date.DatePickerDialog$OnDateSetListener
                                                                                   at com.example.suyog.dailyexpences.ExpensesFragment$1.onClick(ExpensesFragment.java:25)

**Comment by wdullaer** [comment]
I think this is an issue with your code: the error says that some class cannot be cast to an OnDateSetListener.

So I think the thing you're passing in as the callback is not an implementation of the OnDateSetListener.

**Comment by Haraprasad** [comment]
Thank You,
Actually this error comes when I extends android.support.v4.app.Fragment

**Comment by wdullaer** [comment]
The dialogs extend from normal Fragment, not the support Fragments.
In any case: the code excerpt you've given me is too short to debug this. For now everything points into the direction of an issue with your code rather than the library.

**Comment by CoolMind** [comment]
Hello!
I also use support fragments and want to re-set callbacks on orientation change. Reading https://android-arsenal.com/details/1/3779 is write:
`
DatePickerDialog dpd = (DatePickerDialog) getFragmentManager().findFragmentByTag("Datepickerdialog");`
and receive this error: "Inconvertible types cannot cast android.support.v4.app.fragment to 'com.wdullaer... DatePickerDialog'".
I see that findFragmentByTag returns Fragment of support library.

**Comment by CoolMind** [comment]
Solution is simple. Because I invoked a DatePickerDialog from support fragment, I have to write getActivity():
`DatePickerDialog dpd = (DatePickerDialog) getActivity().getFragmentManager().findFragmentByTag("Datepickerdialog");`.
If you wish, you can write this in README.
