### ISSUE TITLE
how to let the day before today are "ALL" disable select

### ISSUE THREAD

**Issue by hvsimon** [wdullaer/MaterialDateTimePicker#169]
i know there is additional option can do limit selectable dates
but i have no idea how to deal with a lot uncertain count day
thx : )

**Comment by wdullaer** [comment]
I don't really understand what you are trying to do.
You can restrict the valid selections using the following methods:
* setYearRange
* setMinDate
* setMaxDate
* setSelectableDays

**Comment by hvsimon** [comment]
i got it 
just setMinDate 
this is my logic mistake haha
ty : ))
