### ISSUE TITLE
Setting Accent Color Not Theming Whole Window

### ISSUE THREAD

**Issue by vincekennedy** [wdullaer/MaterialDateTimePicker#170]
When I set the accent color of a window I'm seeing something odd in 5.1.

If I run without trying to theme anything, everything looks fine. But if I add an accent color the view behind the date or time entries and the button colors go to the same as the background color. I created an empty theme based on `Theme.AppCompat.NoActionBar` and have tried overriding accentColor there. I've tried overriding in the colors.xml as well to something different with no luck.

![screen shot 2016-02-25 at 2 23 25 pm](https://cloud.githubusercontent.com/assets/1082390/13331477/a664c668-dbcb-11e5-97d6-af47c63f6fcd.png)
![screen shot 2016-02-25 at 2 24 30 pm](https://cloud.githubusercontent.com/assets/1082390/13331478/a6650538-dbcb-11e5-829e-a04c0c80cda2.png)

```java
DatePickerDialog dpd = DatePickerDialog.newInstance(dateSetListener,
                                                            date.getYear(),
                                                            date.getMonthValue(),
                                                            date.getDayOfMonth());
dpd.setOkText("Select");
dpd.setThemeDark(true);
dpd.setAccentColor(0x46A4C3);
dpd.setCancelText("Cancel");
dpd.show(getFragmentManager(), dpd.getTag());```

**Comment by wdullaer** [comment]
Very strange.
I can't reproduce this here.
Which version of the library are you running?

**Comment by vincekennedy** [comment]
Version 2.2

The style for that activity is

```<style name="AppTheme" parent="Theme.AppCompat.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="android:dropDownListViewStyle">@style/SpinnerStyle</item>
    </style>```

And the colors

```    <color name="colorPrimary">#46A4C3</color>
    <color name="colorPrimaryDark">#206980</color>
    <color name="colorAccent">#FF4081</color>```

Maybe one of those is causing an issue.

**Comment by wdullaer** [comment]
Can you reproduce this by modifying the sample app?

The code snippits you've shown don't really show anything wrong.

**Comment by vincekennedy** [comment]
I created this simple project https://github.com/vincekennedy/datepickertest with the issue.

It appears to happen no matter what the base theme is.

**Comment by wdullaer** [comment]
I'll check that out and see where I get.
Thanks for taking the time to create this!

**Comment by vikramkakkar** [comment]
The issue here is that you are not supplying the alpha bits. Check this:

    // Accent color, as you're supplying
    int colorAsItIs = 0x46A4C3;
    Log.i("TAG", "Color as it is: " + colorAsItIs);                                     // 4629699

    // Accent color, with alpha bits set
    int colorWithAlphaSet = 0xFF46A4C3;
    Log.i("TAG", "Color with alpha bits set: " + colorWithAlphaSet);        //-12147517

    // Accent color, when parsed
    int parsedColor = Color.parseColor("#46A4C3");
    Log.i("TAG", "Parsed color value is: " + parsedColor);                      // -12147517

So, either use `Color.parseColor(String)`, or supply the `FF` alpha bits.

Note: The color shows up in `mDayOfWeekView` since the color is preprocessed by `Utils.darkenColor(int)` ==> Color.colorToHSV(...) extracts RGB components.

**Comment by wdullaer** [comment]
@vikramkakkar thanks a lot for going through this! I've been lacking the time recently.

I think I'll add an overloaded function which takes in a `String` and parses the color for the user. This should hopefully make this easier for people to use.
Alternatively/additionally I can force the alpha bits in `setColor`

**Comment by vincekennedy** [comment]
Thanks for the help with this. I never thought about the Alpha bits.

**Comment by vikramkakkar** [comment]
@wdullaer Not a problem. I'm happy to help.

@vanniktech You're welcome!
