### ISSUE TITLE
Time picker doesn't update the digital clock unless clicked on slowly

### ISSUE THREAD

**Issue by Chozzle** [wdullaer/MaterialDateTimePicker#174]
I think you are using onClickListeners when you should be using onTouchListeners. I'm happy to fix this if you want me too

**Comment by wdullaer** [comment]
I don't understand what you're referring to.
The pickers implement onTouch where required and react just snappy to touches over here.

**Comment by Chozzle** [comment]
Hi, I've attached a video. When I rest my finer in the same place for a moment before moving it, it works. However if I touch with a swiping action, the top clock doesn't update and there's no vibration. Carson 


Sent from my Samsung device

-------- Original message --------

**Comment by Chozzle** [comment]
I tried it on both my phone and emulator. Can you reproduce it too? My app is very simple so I don't think it would be anything specific to my app.

**Comment by wdullaer** [comment]
I see what you mean now.
I never really considered it a bug, but I'll see what I can do about it.
