### ISSUE TITLE
Selected day circle color in MonthView

### ISSUE THREAD

**Issue by formakidov** [wdullaer/MaterialDateTimePicker#177]
Please add method to change circle color of the selected day (as it's shown in guidelines, dark theme)
http://www.google.com/design/spec/components/pickers.html#pickers-date-pickers

**Comment by wdullaer** [comment]
Indeed, because the spec has them in the same color.

You can mod this in, but I'm not going to support it.
It doesn't need to expose every option under the sun, that's what forking is for.

**Comment by formakidov** [comment]
Ok. Sorry for bothering you:)

**Comment by wdullaer** [comment]
No worries, all questions and requests are welcome, provided I'm allowed to say no too ;-)
