### ISSUE TITLE
Use borax12 library

### ISSUE THREAD

**Issue by Lecraver** [wdullaer/MaterialDateTimePicker#178]
I am interested in using your library but also the fork by the borax12, is it possible to use both ?
I have this when I add the second library :
```
java.lang.ClassCastException: com.wdullaer.materialdatetimepicker.date.AccessibleDateAnimator cannot be cast to com.borax12.materialdaterangepicker.date.AccessibleDateAnimator
```
In my gradle :
```
    compile 'com.wdullaer:materialdatetimepicker:2.1.1'
    compile 'com.borax12.materialdaterangepicker:library:1.5'
```

Best regards,

**Comment by wdullaer** [comment]
You'll need to explicitly specify the namespace in your cast.

There shouldn't be any issues using both in your project.

**Comment by Lecraver** [comment]
Well, i did it but it doesn't works. May be because i try to use both in the same fragment, i'm giving up. 
Thanks
