### ISSUE TITLE
Time picker - set Time Slots : Unable to view 12:00 time when set through setSelectableTimes - 12 hour format.

### ISSUE THREAD

**Issue by alokomkar** [wdullaer/MaterialDateTimePicker#179]
Log :
11:20, 11:40, 12:20, 12:40, 14:20, 14:40, 15:00, 15:20, 15:40, 16:00, 16:20, 16:40, 17:00, 17:20, 17:40, 18:00, 18:20, 18:40, 19:00, 19:20, 19:40, 20:00, 20:20, 20:40 

if (workingDays.containsKey(dateKey)) {
                ArrayList<String> timeSlots = workingDays.get(dateKey);
                timepoints = new Timepoint[timeSlots.size()];

                for (String timeSlot : timeSlots) {
                    Logger.d("TimeSlots",timeSlot);
                    String[] timeSplit = timeSlot.split(":");
                    int hour = Integer.parseInt(timeSplit[0]);
                    int min = Integer.parseInt(timeSplit[1]);
                    timepoints[timeIndex++] = new Timepoint(hour, min, 00);
                }

                if( timeSlots != null && timeSlots.size() > 0 ) {

                    hour = Integer.parseInt(timeSlots.get(0).split(":")[0]);
                    minutes = Integer.parseInt(timeSlots.get(0).split(":")[1]);
                    timePickerDialog = com.wdullaer.materialdatetimepicker.time.TimePickerDialog.newInstance(
                            BookASlotActivity.this,
                            hour,
                            minutes,
                            false
                    );
                    timePickerDialog.setSelectableTimes( timepoints );
                    timePickerDialog.setOnTimeSetListener(this);
                    timePickerDialog.show(getFragmentManager(), "TimePickerDialog");
                }

            }

**Comment by wdullaer** [comment]
What is the actual issue here?
You are constructing an Array of TimePoints that doesn't contain 12:00. This does not seem to be related to the library.

**Comment by alokomkar** [comment]
Its not just an issue with 12:00, any slot which is available from 12 to 1 wouldn't render 12 as selected in time picker. This is the screen shot : 

![screenshot_20160315-095233](https://cloud.githubusercontent.com/assets/4961459/13767732/e6e810b0-ea93-11e5-9492-1a59052190e4.png)

Time slots from Log : 
[10:00, 10:20, 10:40, 11:00, 11:20, 11:40, 12:00, 12:20, 12:40, 14:00, 14:20, 14:40, 15:00, 15:20, 15:40, 16:00, 16:20, 16:40, 17:00, 17:20, 17:40, 18:00, 18:20, 18:40, 19:00, 19:20, 19:40, 20:00, 20:20, 20:40]

**Comment by aldefy** [comment]
To add : The setMinTime and setSelectable times , when used - the TPD does not show 12 as highlighted white (selectable color) , one can select 12 and its min slots but not see the 12 highlighted as seen above.

**Comment by wdullaer** [comment]
Ok, I get it now.
I'll have a closer look.
