### ISSUE TITLE
Timer Picker select interval 5min on 15 (or more ?)

### ISSUE THREAD

**Issue by neoteknic** [wdullaer/MaterialDateTimePicker#18]
Hello,
is it possible to force the timepicker to select a time with 5 min interval or 15 min (or more ?).
It's still possible to round the result after the validation but it will be better if we can block the minute selection to 5 min interval or to 15 min interval (For 15 min interval it's more difficult I think because you have to hide 5, 10 20 25 etc ... in the minute selector.

**Comment by wdullaer** [comment]
This should be possible. I'll add it to the list.

Even if you set it to 15 minutes, it kind of makes sense to show the in between numbers for reference.

**Comment by ConorOD** [comment]
I'm looking for something similar on 30 minute intervals. Is this possible to do myself as the code is at the moment? I only want people to select and see certain intervals

**Comment by wdullaer** [comment]
It is not a one line hack, or I would have done it already.
The current logic is contained partly in `snapPrefer30s()` in `RadialPickerLayout.java`
That function makes sure you can only select hours (every 30 degrees). It's not really written in an extensible way at the moment, but it should be possible to make it happen.

I'm a bit low on time at the moment, but I'm always open to pull requests.

**Comment by wdullaer** [comment]
This will be possible in the next release using the setSelectableTimes function.
It requires an array of Timepoints to configure the selectable times, which is a bit cumbersome to set up for this usecase, but it does the trick.

I might add some sugar function around this later.
