### ISSUE TITLE
Exclude single date, all date of a day 

### ISSUE THREAD

**Issue by SaqibJDev** [wdullaer/MaterialDateTimePicker#188]
Hi,

Is it possible to exclude a specific date or range of dates of a specific day? e.g. National holidays, Sundays etc.

Thanks

**Comment by wdullaer** [comment]
There is a method to limit the options to a specific set of days, but no method to exclude a set.

What you can do is extend `DatePickerDialog` and override ìsOutOfRange` with the logic you need.
