### ISSUE TITLE
How to set date text size?

### ISSUE THREAD

**Issue by kim-montano** [wdullaer/MaterialDateTimePicker#189]
The text size I want to make larger is here: [http://prntscr.com/alhi6n]

It's for a tablet display.

**Comment by wdullaer** [comment]
Is that a screenshot from the tablet?
The library includes separate styling for sw600 which should account for most things.

In case you really want to tweak it, you can override `mdtp_day_number_size`

**Comment by kim-montano** [comment]
Yes it's from a tablet. 

> In case you really want to tweak it, you can override mdtp_day_number_size

Will you be able to create a method that sets the text size for day number display?

Also, thank you so much for creating this library, and thank God that you're replying to inquiries such as mine.

**Comment by wdullaer** [comment]
I'm not going to create a method to set this text size.
I'm on the hook to make sure that such a method works and gives sensible results with every future version of the application. This is a burden I don't want.

As I mentioned earlier, nothing prevents you from overwriting `mdtp_day_number_size` with a value you like more in your own application.

**Comment by kim-montano** [comment]
Okay in case someone else would want want a bigger text, I was able to increase the text size by declaring the `mdtp_day_number_size` on my values folder, dimen.xml and on sw600dp/dimens.xml with 12sp, and 18sp respectively for the sizes.

Normal Text Size on tablet:
[http://prntscr.com/anunf3]

Larger Text Size on tablet:
[http://prntscr.com/anunpd]

Thank you so much for this library, wduallaer.

**Comment by wdullaer** [comment]
Just for the aesthetics you might want to increase the label size as well

**Comment by kim-montano** [comment]
Already did. Thank you very much!
