### ISSUE TITLE
OK/Cancel button text color seems off

### ISSUE THREAD

**Issue by firoze** [wdullaer/MaterialDateTimePicker#19]
Thank you for this amazing library! I've been using it in my current project, but I've run into this styling issue...here's the `colors.xml` stuff. I haven't done anything fancy about initializing the dialog, just the way described in README.md (`newInstance`).

```
    <color name="fountain_blue">#53B5C3</color>
    <color name="oxford_blue">#364D58</color>
    <color name="mdtp_accent_color">@color/fountain_blue</color>
    <color name="mdtp_accent_color_dark">@color/oxford_blue</color>
    <color name="mdtp_button_color">@color/oxford_blue</color>
```

The calendar background and header colors took, but the button text color turned into this light grayish thing. I'm testing this on a Genymotion running Android 4.3. Let me know if I'm doing something wrong, or if I missed anything.

Screenshot:
![](http://i.imgur.com/Vgl8ssm.png)

Thanks again for this great library, and please let me know if there's anything I can do to improve this setting...

**Comment by wdullaer** [comment]
The buttons should use your `accent_color` by default.

However, I noticed I didn't properly namespaced the theme used for the buttons.
Are you by any chance using this library (https://github.com/afollestad/material-dialogs) in your project as well? 
Some style definitions might clash with the ones in this library.

**Comment by firoze** [comment]
Hmm you are right, we are using the Material Dialogs library in this project as well, although I didn't override any of the styles from that library, the way I wanted to specify the colors in your MDP library.

**Comment by wdullaer** [comment]
The problem was that my library was overwriting them :-)
