### ISSUE TITLE
Time picker Header two digit numbers are gone 10,11,12

### ISSUE THREAD

**Issue by milaptank** [wdullaer/MaterialDateTimePicker#190]
Hello Sir 
In some device Time picker Header two digit numbers are gone (10,11,12). I have attached screen you can find attachment 
 
![Timepicker](https://cloud.githubusercontent.com/assets/5506264/14141424/80ac5076-f69c-11e5-87ee-40e22c27c8bb.png)

**Comment by wdullaer** [comment]
I'll need to shrink the font size on smaller displays.
Thanks for bringing this to my attention.
