### ISSUE TITLE
date and time ?

### ISSUE THREAD

**Issue by PeterPhyo** [wdullaer/MaterialDateTimePicker#191]
How to disable previous date and time from current date and time ? And I don't want to do **mode24Hours**. How to do this?

**Comment by wdullaer** [comment]
Read the docs, look at the sample, etc ...

* `setMinTime(Timepoint time)`  
Set the minimum valid time to be selected. Time values earlier in the day will be deactivated
* `setMinDate(Calendar date)`  
Set the minimum valid date to be selected. Earlier dates will be deactivated
* Timepicker Constructor:
```java
TimePickerDialog tpd = TimePickerDialog.newInstance(
  MainActivity.this,
  now.get(Calendar.HOUR_OF_DAY),
  now.get(Calendar.MINUTE),
  mode24Hours.isChecked()
);
```
