### ISSUE TITLE
Differentiate dialogs by tag

### ISSUE THREAD

**Issue by jerry33** [wdullaer/MaterialDateTimePicker#193]
Hey,

I'm using your library and I must say that it looks pretty nice. However, there's one thing I would like to ask: Is there any possibility to differentiate between two picker dialogs? For example I have two time picker dialogs in one fragment (time from, time to), and in `onTimeSet()` method I would really appreciate getting picker tag or id, that I might have set yet during initialization. I noticed you can set tag to `DialogFragment`, but it doesn't come as an argument in `onTimeSet()` method. Instead of it, `RadialPickerLayout` comes.

So is there a way to differentiate between these dialogs or is it something missing?

Thanks.

**Comment by wdullaer** [comment]
Hey Jerry,

I agree that returning the time picker fragment makes more sense.
The library is a fork from a google library and this was the signature they used.

I'm considering changing the signature of the callback to include the fragment, similar to the dateset callback, in the next big version.

The `RadialPickerLayout` is a child of the Time Fragment, so maybe `getParent()` can help you out in the mean time.

**Comment by emitchel** [comment]
Anyone find a way to get the tag? `.getParent()` returns `null` for `.getTag()` as well as the next several `.getParent().getParent().getParent()...` views returned. A static placeholder can solve this problem on the high level, but I feel as though this tag should persist somewhere in the view.

**Comment by Winky93** [comment]
I 'm very confused that why Google choose RadialPickerLayout rather than TimePickerDialog?
Author , How can I solve this problem?

**Comment by Winky93** [comment]
`btn_begin_time.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Calendar now = Calendar.getInstance();
                begin_tpd = TimePickerDialog.newInstance(CreatItemActivity.this,now.get(Calendar.HOUR_OF_DAY),now.get(Calendar.MINUTE),false);
                begin_tpd.show(getFragmentManager(), "Timepickerdialog");
                begin_tpd.setOnTimeSetListener(new TimePickerDialog.OnTimeSetListener() {
                    @Override
                    public void onTimeSet(RadialPickerLayout view, int hourOfDay, int minute, int second) {
                       
                            begin_time_tv.setText(s+"/"+hourOfDay+"/"+minute+"/"+second);
                      
                    }
                });
            }
        });`   is Ok?
