### ISSUE TITLE
there is no Year Selection in my DatePicker

### ISSUE THREAD

**Issue by amlashi-sadra** [wdullaer/MaterialDateTimePicker#195]
as you can see in my MaerialDatePicker i can't find any YearPicker, can any one solve my problem?
i dont want use showYearFirst(Boolean)!

![erge](https://cloud.githubusercontent.com/assets/18361407/14403011/f80cf7ee-fe5b-11e5-9c85-b3220acc0d85.jpg)

**Comment by wdullaer** [comment]
Can you supply some additional information:
* Does this happen on multiple devices?
* Can you show some of the code that generates the picker? (the year picker should always be visible, there's no way to hide it in this library)

**Comment by layerlre** [comment]
I have the same problem in Huawei P9.
Year is not appear.

**Comment by layerlre** [comment]
I decrease text size for date. Now year is appear.
