### ISSUE TITLE
Can I Control Locale?

### ISSUE THREAD

**Issue by JandyCindy** [wdullaer/MaterialDateTimePicker#198]
First of all, thank you for your sharing.
I am making an application which services only two type of languages.
By the way using this, I found that it reads locale from device and offers it.
I want to give consistency to user.
I wonder if there is any way for managing locale for myself.
Thank you.

**Comment by wdullaer** [comment]
There's no way to enforce a certain locale. It uses the default locale of the device it's running on.

It probably is possible to make this configurable, but it's not on my short list of things to add.

**Comment by JandyCindy** [comment]
okay, I understand.
Then I will try to find other way by my self.
Thank you for the answer.
