### ISSUE TITLE
onCancel do not work

### ISSUE THREAD

**Issue by 1hsyn1** [wdullaer/MaterialDateTimePicker#20]
I am thinking when i clicked Cancel button inside datePicker I should reach onCancel. Maybe I am missing something simple but when I write 

 Calendar calendar=Calendar.getInstance();
            DatePickerDialog dp=DatePickerDialog.newInstance(MainActivity.this, calendar.get(Calendar.YEAR),calendar.get(Calendar.MONTH), calendar.get(Calendar.DAY_OF_MONTH));
            dp.show(getFragmentManager(),"datePick");
            dp.onCancel(dateCancel);

private DialogInterface dateCancel=new DialogInterface() {
        @Override
        public void cancel() {
            System.out.println("cancel");
        }

        @Override
        public void dismiss() {
            System.out.println("dismiss");
        }
    };

I can not see neither any of the println lines which inside dateCancel, nor can reach those lines with debug mode when i clicked Cancel button. But I can get when I clicked OK with onDateSet .

**Comment by wdullaer** [comment]
I am not calling any callbacks when you click cancel, just dismissing the dialog.

I'll try to add this in.

**Comment by 1hsyn1** [comment]
is it possible for you to add this dismiss and cancel callbacks soon?

**Comment by wdullaer** [comment]
Just on the side: the date and time which are picked are delivered through a separate interface which doesn't expose an onCancel() callback. Neither do the built-in date and time pickers.

This would make this an API breaking change, and I also try to keep the API of this library as close as possible to the built-in date and time pickers.

**Comment by wdullaer** [comment]
Ok, I found an elegant workaround.
I'll try to publish the changes today.

btw: you are using that onCancel() method incorrectly.

**Comment by wdullaer** [comment]
Fixed in 0ef38ff22334cb244f4703367733f2f7bc4409b1

**Comment by 1hsyn1** [comment]
thanks for the quick response which I was not expecting.  By the way library is a great work of art, another thanks for your effort.
