### ISSUE TITLE
Dialog does not appear on single click of EditText

### ISSUE THREAD

**Issue by bapu-nawaz** [wdullaer/MaterialDateTimePicker#202]
When this functionality is set to appear onClickListener set on an EditText, the dialog does not seem to appear unless you make a consecutive second click on the same EditText. I am using both Date and Time picker. I tried using onTouchListener but that would execute the command for more than once, i.e the dialog appears twice.

**Comment by khawars** [comment]
@bapu-nawaz I am also facing this issue. How did you fix that?

**Comment by wdullaer** [comment]
You shouldn't use an EditText as a Button.
It clashes with the built-in event listeners.
