### ISSUE TITLE
Set min date to Current Date

### ISSUE THREAD

**Issue by elpoisterio** [wdullaer/MaterialDateTimePicker#205]
Be able to use native method datePickerDialog.getDatePicker(<time in millis>);

**Comment by wdullaer** [comment]
Reply to the title:
```java
dpd.setMinDate(Calendar.getInstance());
```

I don't undertand the question you're asking in the body of the issue.

**Comment by elpoisterio** [comment]
if I need to set min date to today's date, then ?
