### ISSUE TITLE
How to show two TimePickerDialog ?

### ISSUE THREAD

**Issue by PeterPhyo** [wdullaer/MaterialDateTimePicker#207]
I am using for Open Hour (Am & Pm). User chooses Am time;  and then, I would like to show TimePickerDialog again for Pm time when AmTimePickerDialog click **ok** button. And then, I would like to show that two data [time = am +pm] in (txt_time.setText(time))

**Comment by wdullaer** [comment]
You initialize and show the second picker in the callback of the first one.
This sort of question is more suited for stackexchange than here. It is not an issue with this library.
