### ISSUE TITLE
Dark Theme Dialog Actions

### ISSUE THREAD

**Issue by nwhessel** [wdullaer/MaterialDateTimePicker#21]
The background for the picker actions isn't in dark mode when the rest of the picker is.

![device-2015-05-01-203522](https://cloud.githubusercontent.com/assets/9904661/7439460/3c708582-f042-11e4-9f1b-7ea430f191e6.png)

**Comment by wdullaer** [comment]
The dark mode is very much "try at your own risk".
It's a remnant from the original google code, I'm amazed that it still looks as good as it does.

This should be relatively easy to fix though.
