### ISSUE TITLE
not able got view.getTag() in onTimeSet

### ISSUE THREAD

**Issue by UdayKumarNayak** [wdullaer/MaterialDateTimePicker#212]
like from
 ```
@Override
    public void onDateSet(DatePickerDialog view, int year, int monthOfYear, int dayOfMonth) {
        String tag=view.getTag();
    }
```
that code i give me  "Datepickerdialog" which is set at
`dpd.show(getFragmentManager(), "Datepickerdialog");`

but in onTimeSet i am getting null.

**Comment by wdullaer** [comment]
This is because the callback doesn't return the `TimePickerDialog` but a child View.
It's a leftover from the google code that I forked and not very intuitive.
You're not the first to complain about this and I intend to change this behaviour in the next major release.

**Comment by UdayKumarNayak** [comment]
Thanks for replay.
