### ISSUE TITLE
Disable To on Date and Time Dialog

### ISSUE THREAD

**Issue by tux-world** [wdullaer/MaterialDateTimePicker#214]
Hi, how can i disable TO from date and time picker? i dont need to have that,

Thanks

**Comment by wdullaer** [comment]
By fixing your dependencies and actually using this library rather than https://github.com/borax12/MaterialDateRangePicker

Duplicate of #151

**Comment by tux-world** [comment]
@wdullaer Thanks, but whats dependency? i'm using ``` compile 'com.borax12.materialdaterangepicker:library:1.6' ```

**Comment by wdullaer** [comment]
It's more or less the first thing in the README on the homepage of this github project
