### ISSUE TITLE
Dialog to show days of the week

### ISSUE THREAD

**Issue by IomarSantos** [wdullaer/MaterialDateTimePicker#216]
It shows only the weekdays

**Comment by wdullaer** [comment]
Can you be a bit more specific?
Perhaps indicate on a screenshot what is wrong or make a mockup of how you'd like things to be displayed.

**Comment by IomarSantos** [comment]
only day of the week dialog

**Comment by wdullaer** [comment]
Repeating your original question is not being more specific
