### ISSUE TITLE
This is not compatible for Support Library.

### ISSUE THREAD

**Issue by neonwarge04** [wdullaer/MaterialDateTimePicker#217]
I cannot seem to pass FragmentManager from a fragment via a getFragmentManager(). The version of the support library I am getting this from is v4's. 

Here is my code:
```
        EditText fromDate = (EditText) view.findViewById(R.id.edittext_frag_filter_date_from);
        fromDate.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View view)
            {
                FragmentManager fg = RankingsFilterFragment.this.getFragmentManager();

                Calendar now = Calendar.getInstance();
                DatePickerDialog datePickerDialog = DatePickerDialog.newInstance(RankingsFilterFragment.this, now.get(Calendar.YEAR), now.get(Calendar.MONTH), Calendar.DAY_OF_MONTH);
                datePickerDialog.show(fg, "THIS IS NOT WORKING FIX THIS!");
            }
        });
```

I am having error on show() since it is asking for FragmentManager I need to pass FragmentManager from v4 support library. I can't. 

It says this one has support for Android 4.0 (API15) I am using API16. Is there a workaround for this? Or something I've missed?

**Comment by wdullaer** [comment]
It is compatible, in the sense that you need to use the regular FragmentManager to display the dialogs, but can use the SupportFragmentManager in other place of your application

From the FAQ
>Why not use SupportDialogFragment?
>
>Not using the support library versions has been a well considered choice, based on the following considerations:
>
>Less than 5% of the devices using the android market do not support native Fragments, a number which will decrease even further going forward.
>Even if you use SupportFragments in your application, you can still use the normal FragmentManager
>This means that in the current setup everyone can use the library: people using the support library and people not using the support library.
>
>Finally changing to SupportDialogFragment now will break the API for all the people using this library.
>
>If you do really need SupportDialogFragment, you should fork the library. It involves changing all of 2 lines of code, so it should be easy enough to keep it up to date with the upstream.

**Comment by reisub** [comment]
Hi @wdullaer,
thanks for the great work on the lib!

I just wanted to let you know that I forked the lib because I need support for fragments from support lib:
https://github.com/infinum/MaterialDateTimePicker

I don't plan to add any new feature, but I do plan to keep the fork up-to-date with your changes. It's also published to jcenter.

**Comment by wdullaer** [comment]
Cool
I'll see if I can add this to the README.

You can use both the regular and support fragment manager side by side in a single app, but for religious people / esoteric use cases, this could be great

**Comment by reisub** [comment]
@wdullaer Hi again! Just wanted to point out that now seems like a good time to revisit the decision to not support fragments from the support lib.

Please take a look at this answer from a google engineer explaining that platform fragments will be deprecated in the next version of Android:
https://github.com/android/android-ktx/pull/161#issuecomment-363270555
