### ISSUE TITLE
Implement Unselectable/Disabled Days in addition to Selectable/Enabled Days

### ISSUE THREAD

**Issue by JeffreyCA** [wdullaer/MaterialDateTimePicker#219]
How can I disable a few days in the date picker, but have enabled dates which encompass a large range?

It would be very inefficient to put all of the allowed days into a Calendar array and use `setSelectableDays`, as my enabled days span over a large amount of years.

Could something like `setDisabledDays` be implemented, so that I can use `minDate` an `maxDate` along with the disabled/unselectable days in between?

**Comment by wdullaer** [comment]
There's no way to disable specific days right now.
You can set enabled days and min/max dates.

I'll add this to the (admittedly long) list of things I'll look at.

Right now, you can extend `DatePickerDialog` and overwrite `isOutOfRange()`for custom behaviour.

**Comment by JeffreyCA** [comment]
Alright, thanks!
