### ISSUE TITLE
Cannot reset time and date to default / current time

### ISSUE THREAD

**Issue by aminalzanki** [wdullaer/MaterialDateTimePicker#22]
When user selected the date and time to somewhere in future and then he/she tend to revert back to current time, he/she could not be able to do so since there have no button to set to current time back. It's a good decision to add one button to satisfy this request. 

Thanks.

**Comment by wdullaer** [comment]
You can add this in your app: have a button to select today or make it the default value, and then have a button to pick a specific date, which shows the datepicker.

I'm trying to stick as close to the material design example as possible.
