### ISSUE TITLE
How to use it in a Service?

### ISSUE THREAD

**Issue by aravindmeganathan** [wdullaer/MaterialDateTimePicker#222]
I need to inflate it in a service like a dialog. Couldn't get fragment manager in a Service. How can i solve it?

**Comment by wdullaer** [comment]
`Services` are background processes and don't have a UI. As a consequence they can't render `Fragments`.

You need to launch an `Activity` using an `Intent` from your `Service` and then have the `Activity` take care of rendering the dialog.
