### ISSUE TITLE
Custom background color / more theming options

### ISSUE THREAD

**Issue by MaximilianKeppeler** [wdullaer/MaterialDateTimePicker#223]
Though I love the predefined 2 themes (dark and light theme with the option to change the primary color), I really wish there would be a few more theming options. In some cases it just doesn't fit to the rest of the app. I wish I could set a custom color(s) for the backgrounds.

**Comment by wdullaer** [comment]
You can set the accent colour and chose between a dark and light theme.
This is what the material design specs foresee for pickers.
I don't really want to support any more customizations.

You can do a lot by overriding some mdtp_* color definitions in your app. If not, it should be easy enough to change this in a fork.

**Comment by MaximilianKeppeler** [comment]
Okay, thank you for your reply. In quite new in all this things here. I will check if overriding does work as I want. Otherwise I will fork it, if I'm allowed to do that. Thanks for your help.
