### ISSUE TITLE
DateTime Dialog

### ISSUE THREAD

**Issue by kenmeidearu** [wdullaer/MaterialDateTimePicker#229]
i have issue i need module DateTimeDialog in one place like this
![DateTimePicker](https://github.com/kenmeidearu/MaterialDateTimePicker/blob/master/DateTimePicker.png)

i was modified your library but for the time still ugly
can you combine your date dialog and time dialog in one datetime dialog.

sorry i reupload your project in[ my gith](https://github.com/kenmeidearu/MaterialDateTimePicker/) with little modification. because i need fast

**Comment by wdullaer** [comment]
There's a work in progress in the datetimepicker branch.
Feel free to experiment with that.
