### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by JORDAN1998** [wdullaer/MaterialDateTimePicker#23]
Hello Wdullaer,

I was just wondering if you know when you might add the change Theme by code feature for your library. It is much needed for my app and I will be very happy when you add it. Any idea when?

Thank you,

Jordan :)

**Comment by wdullaer** [comment]
I've been very busy the last two weeks. But this will be one of the next features I add.

Also: please just keep the original issue #15 open.

**Comment by JORDAN1998** [comment]
Thank you sounds great. Sorry didn't know if I commented again on that
issue, if you would receive a notification or not. Next time I won't make a
new one.

Thanks for all your awesome work,

Jordan
