### ISSUE TITLE
Only Month and Year Picker?

### ISSUE THREAD

**Issue by cyrilnoah1** [wdullaer/MaterialDateTimePicker#233]

**Comment by cyrilnoah1** [comment]
Is there any possibility to only allow Month and Year input, by hiding the DatePicker?

**Comment by wdullaer** [comment]
It's a DatePicker, hiding it wouldn't make too much sense.
The design just isn't meant to do that.

**Comment by cyrilnoah1** [comment]
Sorry, I asked that. I knew the purpose of the library, but, I badly needed a Month-Year picker. 
Anyway, Thank you for replying. :)

**Comment by wdullaer** [comment]
You can try to use just dropdowns.
There aren't that many values to display.
If you have an idea that closely resembles the datepicker, you can always fork and rip out the bits you don't like, nothing wrong with that :-)
