### ISSUE TITLE
Disable today Date

### ISSUE THREAD

**Issue by salunkhenilesh** [wdullaer/MaterialDateTimePicker#236]
just disable  today date also

**Comment by wdullaer** [comment]
I don't understand the question. Can you give a bit more detail?

**Comment by salunkhenilesh** [comment]
i am just want to current date also disable. no one can select today date

**Comment by wdullaer** [comment]
From the readme:

```java
Calendar[] disabledDays = {Calendar.getInstance()};
dpd.setDisabledDays(disabledDays);
```

**Comment by ipsjolly** [comment]
> From the readme:
> 
> ```java
> Calendar[] disabledDays = {Calendar.getInstance()};
> dpd.setDisabledDays(disabledDays);
> ```

hi, can you please tell... how to add SUNDAYS in the current month to disabledDays?

Is there any event which is fired on Date select or month change?
