### ISSUE TITLE
change Month Label

### ISSUE THREAD

**Issue by anastr** [wdullaer/MaterialDateTimePicker#238]
is there any way to change **Month label** to digits ?

like `01 02 03 .....`
thank you.

**Comment by wdullaer** [comment]
Nope, this is not supported.
The goal is to stay as close as possible to the Material Design specs as possible.

It should be easy enough to change yourself in `MonthView.java/drawMonthTitle()`

**Comment by anastr** [comment]
`MonthView.java/#getMonthAndYearString()`
`pattern = "MM yyyy"` ... 
this should work.
thanks.
