### ISSUE TITLE
[Feature request] Gray out a week after or before selected day by user's choice

### ISSUE THREAD

**Issue by raviteja83** [wdullaer/MaterialDateTimePicker#240]
Is it possible to grey out the next 7 days based on the selected day? The selection has to change as the date changes to the next or previous 7 days as set by the user.

**Comment by wdullaer** [comment]
This is not supported.
It's also trivially easy to circumvent this restriction: select a date around 10 days back and you can then select any dates that were previously disabled.

You can disable dates when you initialize the dialog, but not dynamically when it's open.

**Comment by raviteja83** [comment]
can you provide a listener when user selects a date other than dateselectedlistener which is currently called on dialog ok button?

**Comment by wdullaer** [comment]
You can attach to some standard Dialog callbacks which are triggered on cancel or dismiss, but there is not callback for a user selection.
