### ISSUE TITLE
Portray orientation doesn't always scale correctly

### ISSUE THREAD

**Issue by TormundsMember** [wdullaer/MaterialDateTimePicker#241]
I've tested this on a couple devices now and one in particular, the Huawei-ALE21, doesn't properly scale all the way down. The bottom of the text at the end is cut off.

![device-2016-09-15-092944](https://cloud.githubusercontent.com/assets/14214087/18542453/3da86c9c-7b2b-11e6-9faa-dd42f37b3869.png)

**Comment by wdullaer** [comment]
You are not using the latest version of the library.

**Comment by TormundsMember** [comment]
Well, I feel stupid now. Sorry for bothering

**Comment by wdullaer** [comment]
It happens :-)
