### ISSUE TITLE
OnClickListener for ok and cancel buttons

### ISSUE THREAD

**Issue by Shayne3000** [wdullaer/MaterialDateTimePicker#245]
Is there a way to set custom click listeners for the ok and cancel buttons?

**Comment by wdullaer** [comment]
Yes there is, and it is mentioned in the README.

**Comment by Shayne3000** [comment]
What I meant was currently we have onDateSet call back which gets called when the user clicks "OK". What I wanted to ask was if we could attach our own listeners to the buttons such as Android has in the current AlertDialog specification i.e. builder.setPositiveButton(positiveText,
                        new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                            
                            }
                        });
It seems as the positive and negavtive button clicks are locked to specific callbacks and not customisable. Hence the question.

**Comment by wdullaer** [comment]
Allow me to copy the relevant section from the README then

`OnDismissListener` and `OnCancelListener`
Both pickers can be passed a `DialogInterface.OnDismissLisener` or `DialogInterface.OnCancelListener` which allows you to run code when either of these events occur.

```java
tpd.setOnCancelListener(new DialogInterface.OnCancelListener() {
    @Override
    public void onCancel(DialogInterface dialogInterface) {
      Log.d("TimePicker", "Dialog was cancelled");
    }
});
```

**Comment by a1018875550** [comment]
why dismiss also go to this method 'setOnCancelListener'

**Comment by wdullaer** [comment]
It shouldn't, and as far as I can see, it doesn't?
