### ISSUE TITLE
Minor Bug in date picker's month numbers

### ISSUE THREAD

**Issue by Shayne3000** [wdullaer/MaterialDateTimePicker#247]
I started using this library yesterday and I noticed today that the date picker mismatched the months. I assume that it started counting January as the Oth month because it returns 21st September 2016 as 21/08/2016.

**Comment by farkerhaiku** [comment]
That's [covered](https://github.com/wdullaer/MaterialDateTimePicker#why-does-the-datepickerdialog-return-the-selected-month--1) on the FAQ section of the readme.
