### ISSUE TITLE
How to set animation for change month from scroll up - down to Swipe left right 

### ISSUE THREAD

**Issue by Poonjaroen** [wdullaer/MaterialDateTimePicker#248]
Please help me, for this.  Thank you.

**Comment by wdullaer** [comment]
That's not implemented yet.

There's a pull request that adds this, that I really need to review

**Comment by Poonjaroen** [comment]
Thank you for informaton, and I have one question.
 - This library provide set Locale (localization such as France) or not ?


Thank you again.

**Comment by wdullaer** [comment]
Yes, it's localised into most languages.
You can check that in the code

**Comment by wdullaer** [comment]
This has been added in the v3 release
