### ISSUE TITLE
Timezone issues

### ISSUE THREAD

**Issue by otiasj** [wdullaer/MaterialDateTimePicker#252]
All the date we receive from our server are UTC,
and DatePickerDialog.mCalendar is final and private, 
so I can not override the current timezone of the calendar.
adding accessors for mCalendar would solve this issue.

e.g : I receive from the server "31/10/2016" 
I expect to see the picker dialog on the 31th but it is showing on the 30th (time difference between utc and device local time)

**Comment by wdullaer** [comment]
The dialog is behaving as expected: render a given date in the timezone of the current device.

If you really need to treat some date timezone independent, you'll have to do the timezone conversion up front, before initializing the dialog
