### ISSUE TITLE
newInstance is changed but the documentation is not updated 

### ISSUE THREAD

**Issue by aanchalharit** [wdullaer/MaterialDateTimePicker#253]
Now the new method DatepickerDialog.newInstance need onDateSetListener as a parameter , but the documentation of the library is not updated to incorporate the same.

**Comment by wdullaer** [comment]
`newInstance` always required a callback.
The javadoc in the code reflects this, the examples in the README reflect this.

The only thing missing in the docs is an explicit description of the signature of `newInstance`, but I'm not sure how much this would add.

**Comment by aanchalharit** [comment]
Sorry for raising this incorrectly due to new to programming.. Actually I missed the Activity implements DatePickerDialog.OnDateSetListener part and that was causing the issue, closing this one now, thanks for quick reply.
