### ISSUE TITLE
Broken design on LG

### ISSUE THREAD

**Issue by kuba14** [wdullaer/MaterialDateTimePicker#255]
Hi, on my LG F60 I have one issue. The buttons (OK/Cancel) are not shown properly, they seem to be cut (there is no scrolling).

Mobile: LG F60
Android OS: 4.4.4
Density: HDPI
Resolution: 480px x 734px

I think this is quite an important thing. These buttons should be displayed at all times. 

![screenshot_2016-10-08-17-20-39](https://cloud.githubusercontent.com/assets/5584537/19214122/d9ddc8a6-8d7c-11e6-8fc6-5cd464c693e2.png)

**Comment by kuba14** [comment]
Update: This issue is caused by title. In case I remove it, buttons are displayed correctly.
![screenshot_2016-10-08-17-37-18](https://cloud.githubusercontent.com/assets/5584537/19214201/fe07179a-8d7d-11e6-8629-50f6d2b1c40b.png)

**Comment by wdullaer** [comment]
I'm aware of this. The pickers are very hungry for vertical space, and if you add all the options, they won't work properly on low res screens.
The "marshmallow" layout should suffer less from this (whenever I get around to finishing that)

**Comment by wdullaer** [comment]
Can you check whether the `VERSION_2` in the newly released version 3.0.0 fixes this?

**Comment by kuba14** [comment]
Yes, this version fixed the problem. Thanks.

**Comment by wdullaer** [comment]
Great1

**Comment by marekfri** [comment]
Hi wdullaer, this fix isn't working 100%. Time picker is displayed well on portrait orientation, but there is an issue when I switch to landscape mode. Title is displayed well, however hours are missing.
![selection_669](https://cloud.githubusercontent.com/assets/5584533/20858695/8257db9e-b94b-11e6-8a17-d247f167425f.png)

**Comment by wdullaer** [comment]
Can you try 3.1.1?
I changed the sizes in the header slightly so everything should now render properly

**Comment by kuba14** [comment]
Unfortunately, the problem still exists, also in 3.1.2. Hours are missing. I used VERSION_2 as you said.
![screenshot_2017-02-24-20-09-45](https://cloud.githubusercontent.com/assets/5584537/23317250/e2f377c4-facd-11e6-892c-2c72e7540b7a.png)
