### ISSUE TITLE
Issue with Gradle Dependency 

### ISSUE THREAD

**Issue by ashishraval21** [wdullaer/MaterialDateTimePicker#256]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.borax12.materialdaterangepicker:library:1.8.
     Searched in the following locations:
         file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/borax12/materialdaterangepicker/library/1.8/library-1.8.pom
         file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/borax12/materialdaterangepicker/library/1.8/library-1.8.jar
         https://jcenter.bintray.com/com/borax12/materialdaterangepicker/library/1.8/library-1.8.pom
         https://jcenter.bintray.com/com/borax12/materialdaterangepicker/library/1.8/library-1.8.jar
         file:/Users/songline/Library/AndroidStudio/extras/android/m2repository/com/borax12/materialdaterangepicker/library/1.8/library-1.8.pom
         file:/Users/songline/Library/AndroidStudio/extras/android/m2repository/com/borax12/materialdaterangepicker/library/1.8/library-1.8.jar
         file:/Users/songline/Library/AndroidStudio/extras/google/m2repository/com/borax12/materialdaterangepicker/library/1.8/library-1.8.pom
         file:/Users/songline/Library/AndroidStudio/extras/google/m2repository/com/borax12/materialdaterangepicker/library/1.8/library-1.8.jar

**Comment by wdullaer** [comment]
Not related to this library.
You have this library in your dependencies: https://github.com/borax12/MaterialDateRangePicker
