### ISSUE TITLE
Button bar not visible on small devices

### ISSUE THREAD

**Issue by Iggy82** [wdullaer/MaterialDateTimePicker#26]
Hello,

Thanks for your great library. But there is a problem on small devices. The button bar with the OK and Cancel buttons is not visible and therefore you cannot choose a date :(
Do you already know this problem? Can you fix it?

![buttons](https://cloud.githubusercontent.com/assets/9903554/7544751/519919a4-f5d0-11e4-8d41-201b28981997.JPG)

Thank you very much.

**Comment by wdullaer** [comment]
Can you show me how the date picker in google calendar looks on this device?

On a first look, I doubt I'll be able to squeeze in all the content on a screen this size. I don't think there are a lot of devices with this screensize out there anymore.

**Comment by Iggy82** [comment]
Hello,

Sorry for the late reply. I didn't get a reminder about your answer :(

Of course this is an extreme sample but it could be on some devices and there are still a lot old devices or cheap devices. I have tested it on an emulator. Here are 2 screenshots of the datepicker dialog in the API demo app. The button bar is always overlapping the content area. You can see it at best in the time picker from Google. I think overlapping the content area is better than not be able to choose a date :)
What do you think?

![calendargoogle](https://cloud.githubusercontent.com/assets/9903554/7663522/165f5532-fb6c-11e4-8933-483024b1e35f.JPG)
![timegoogle](https://cloud.githubusercontent.com/assets/9903554/7663524/1a75dc04-fb6c-11e4-912b-313baf9dc620.JPG)

**Comment by wdullaer** [comment]
I'll see what I can do.
I do not intend to support resolutions not even Google supports.

I do need to tweak the current design to support smaller resolutions though. I estimate this will be 1 to 2 days of full time work, which I currently don't have actually. 
I'll take this into consideration then.

**Comment by Iggy82** [comment]
Thank you. It would be great if you could find the time in a future version.

**Comment by wdullaer** [comment]
I've reduced the size of the DatePicker in recent versions. I'm going to assume that this resolves this issue in all practical cases.
Feel free to reopen if that's not the case
