### ISSUE TITLE
add date picker in fragment

### ISSUE THREAD

**Issue by arpit999bicubic** [wdullaer/MaterialDateTimePicker#260]
How can i add this in fragment please solve my issue. 

Error  = java.lang.ClassCastException: com.bicubic.botadnews.activity.MainActivity cannot be cast to com.wdullaer.materialdatetimepicker.date.DatePickerDialog$OnDateSetListener

HERE =   Calendar now = Calendar.getInstance();
                DatePickerDialog dpd = DatePickerDialog.newInstance(
                        (DatePickerDialog.OnDateSetListener) getActivity(),
                        now.get(Calendar.YEAR),
                        now.get(Calendar.MONTH),
                        now.get(Calendar.DAY_OF_MONTH)
                );
                dpd.setAccentColor(Color.parseColor("#9C27B0"));
                dpd.setTitle("DatePicker Title");
                dpd.show(getActivity().getFragmentManager(), "Datepickerdialog");

**Comment by Binzzzz** [comment]
Pls Implement the Fragment with the Date listener and override the OnDateSet

` @Override
    public void onDateSet (DatePickerDialog view, int year, int monthOfYear, int dayOfMonth) {
}`

**Comment by veeranath** [comment]
yes i had tried that way but it giving me the same error 

 Calendar now = Calendar.getInstance();
        DatePickerDialog dpd = DatePickerDialog.newInstance(Doc_Amount_Billed.this,
                now.get(Calendar.YEAR),
                now.get(Calendar.MONTH),
                now.get(Calendar.DAY_OF_MONTH)
        );
        dpd.setOnDateSetListener(this);
        dpd.show(getFragmentManager(), "startbill");

**Comment by veeranath** [comment]
i havnt got the solution for so i had used the interfaces i had done it

**Comment by wdullaer** [comment]
The exception tells you everything you need to know: your `MainActivity` does not implement the `OnDateSetListener` interface.
Either pass something in that does implement the interface, or implement it on your main activity.

This is clearly an issue with your code and not this library
