### ISSUE TITLE
How to use setCanceledOnTouchOutside() for TimePickerDialog?

### ISSUE THREAD

**Issue by zohabAli** [wdullaer/MaterialDateTimePicker#264]
I want to use this function "setCanceledOnTouchOutside()" so that TimePickerDialog should not cancel when user touch outside the dialog.....Can you please tell me how can I use it?

**Comment by wdullaer** [comment]
There's no built-in support for that.

Either create your own `Dialog` with that option set, and add the `TimePickerDialog` to it as a `DialogFragment`.

Or extend the `TimePickerDialog` as follows

```java
class MyTimePickerDialog extends TimePickerDialog {
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        Dialog dialog = super(savedInstanceState);
        dialog.setCanceledOnTouchOutside(false);
        return dialog;
    }
}
```
