### ISSUE TITLE
How to block saturday and sunday and block specific dates 

### ISSUE THREAD

**Issue by azaabudeen** [wdullaer/MaterialDateTimePicker#269]

**Comment by wdullaer** [comment]
https://github.com/wdullaer/MaterialDateTimePicker#additional-options
`setSelectableDays()`
`setDisabledDays()`

https://github.com/wdullaer/MaterialDateTimePicker#how-do-i-use-my-custom-logic-to-enabledisable-dates

**Comment by azaabudeen** [comment]
@wdullaer  can you provide a sample code?

**Comment by wdullaer** [comment]
That's not the purpose of the issue tracker.
The information in the readme should allow you to write this code yourself.

The issue tracker is for reporting bugs with the library, not a forum for me to help you build your app.

**Comment by ipsjolly** [comment]
> @wdullaer can you provide a sample code?

I have written some code to 

                // Setting Min Date to today date
                Calendar min_date_c = Calendar.getInstance();
                datePickerDialog.setMinDate(min_date_c);



                // Setting Max Date to next 2 years
                Calendar max_date_c = Calendar.getInstance();
                max_date_c.set(Calendar.YEAR, Year+2);
                datePickerDialog.setMaxDate(max_date_c);

There is also sample code to disable all SUNDAYS and SATURDAYS between above min max check [here](https://www.freakyjolly.com/android-material-datepicker-and-timepicker-by-wdullaer-tutorial-by-example/)

**Comment by wdullaer** [comment]
That's currently not supported.
Someone opened a PR, but never bothered to incorporate the code review comments.

This will be the next feature I add, but I can't give an ETA. I haven't had a lot of spare time to work on this.

In general: it's better to open a new issue rather than resurrecting a 3 year old one.
