### ISSUE TITLE
[Feature Request] Date Picker Mode

### ISSUE THREAD

**Issue by RadhiFadlillah** [wdullaer/MaterialDateTimePicker#27]
Is it possible to add DatePicker mode for potrait like this :
![mockup date picker](https://cloud.githubusercontent.com/assets/6129042/7554387/41f678ca-f751-11e4-86af-d2cf732c64c2.jpg)
This way, we can use suitable mode for device with small screen.

**Comment by andremacpereira** [comment]
Support

**Comment by wdullaer** [comment]
The medium one looks very close to the new design on the material design reference, and it was posted here before that was out: kudos.

I might implement the new reference designs as separate widgets, I haven't decided yet.
A lot will depend on how much work this will be.

**Comment by dimsuz** [comment]
Hello! Any news on this issue, do you still plan to implement a new design, or is the decision still pending?

**Comment by wdullaer** [comment]
It's been nearly done for a while now.
Unfortunately work/life balance has taken a massive swing to the work side lately, which didn't leave any time to work on this library in the last 2 months.

I need one or two full time days to wrap it up. I'm gunning for early June now.

**Comment by dimsuz** [comment]
It's great news, thank you for working on this!

**Comment by paskuale75** [comment]
Is it possible to select only a month in calendar control ? Thanks

**Comment by wdullaer** [comment]
It's not possible to select just a month.
The design doesn't make sense for that use case.

**Comment by wdullaer** [comment]
Fixed in version 3.0.0
