### ISSUE TITLE
how to put two date picker in a single activity

### ISSUE THREAD

**Issue by sachitkarki** [wdullaer/MaterialDateTimePicker#270]
i want to use this library for check-in date and check-out date. But im getting a same date which is selected first. Please help me. thanks.

**Comment by wdullaer** [comment]
You need to create two seperate instances and give them a different tag when showing them using the FragmentManager.

You can chose to give them both the same callback, and distinguish by inspecting the tag on the DatePickerDialog argument in the callback, or give them both a separate callback as an anonymous inner class.
