### ISSUE TITLE
How to set custom typeface

### ISSUE THREAD

**Issue by saibbyweb** [wdullaer/MaterialDateTimePicker#276]
I tried to override the default font "serif" to my custom typeface. It works perfectly, but it created some unnecessary margins between textviews in material date picker. See screenshot below:

![screenshot_20161123-143025](https://cloud.githubusercontent.com/assets/12108899/20555758/a908ebda-b189-11e6-976e-a59b0c629d02.png)

As you can see in this screenshot, text "2016" touches the bottom of the blue colored layout, doesn't look nice. I cannot exclude my material picker from my font override as it applies to every text view throughout the app, so I was thinking can I apply some other custom type face to these text views, "NOV", "03", "2016" in material date picker?

**Comment by wdullaer** [comment]
The font you are using seems to impact the margins and padding rules.
You will have to override the sizes of these pieces of text to fix your issue.
Check res/values/dimens in the code to find the value you're looking for.
Overrides done in your app take precedence over the values in the library.

**Comment by saibbyweb** [comment]
I used version two of material date picker, looks better. And no margin issues.
