### ISSUE TITLE
How to start Datepicker from tomorrow's date or how to setMinDate to tomorrow's date

### ISSUE THREAD

**Issue by aga8541** [wdullaer/MaterialDateTimePicker#277]
I need to start Datepicker from tomorow's date or else i want to setMinDate to tomorrow's date i tried so many solutions but not worked..Please help!!!

**Comment by aga8541** [comment]
Calendar now = Calendar.getInstance();
        dateButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                DatePickerDialog datePickerDialog ;
                datePickerDialog = DatePickerDialog.newInstance(LoginSuccess.this,  now.get(Calendar.YEAR),
                        now.get(Calendar.MONTH),
                        now.get(Calendar.DAY_OF_MONTH));
                datePickerDialog.setThemeDark(false);
                datePickerDialog.showYearPickerFirst(false);
                datePickerDialog.setAccentColor(Color.parseColor("#009688"));
                datePickerDialog.setTitle("Select Date From DatePickerDialog");
Calendar cMin=Calendar.getInstance();
                cMin.add(now.DAY_OF_MONTH, 1);
now.add(Calendar.DAY_OF_MONTH, 30);
List<Calendar> dayslist= new LinkedList<Calendar>();
                Calendar[] daysArray;
                Calendar cAux = Calendar.getInstance();
                while ( cAux.getTimeInMillis() <= now.getTimeInMillis())
                {
                    if (cAux.get(Calendar.DAY_OF_WEEK)!=1)
                    {
                        Calendar c = Calendar.getInstance();
                        c.setTimeInMillis(cAux.getTimeInMillis());
                        dayslist.add(c);
                    }
                    cAux.setTimeInMillis(cAux.getTimeInMillis()+(24*60*60*1000));
                }
                daysArray = new Calendar[dayslist.size()];
                for (int i = 0; i<daysArray.length;i++)
                {
                    daysArray[i]=dayslist.get(i);
                }

                datePickerDialog.setMinDate(cMin);
                datePickerDialog.setMaxDate(now);
                datePickerDialog.show(getFragmentManager(), "DatePickerDialog");
                 datePickerDialog.setSelectableDays(daysArray);
            }
        });
    }

**Comment by wdullaer** [comment]
First: please keep this issue tracker for bugs with the library. General programming questions, like this one, belong more on sites like stackoverflow

The parameters you give to the dialog when creating it contain the default date.
You'll need to set your Calendar instance to the date you want before querying it for the data given to the datepicker dialog.
```
Calendar startDate = Calendar.getInstance();
startDate.add(Calendar.DAY_OF_MONTH, 1);
DatePickerDialog dpd = DatePickerDialog.newInstance(
    this,
    startDate.get(Calendar.YEAR),
    startDate.get(Calendar.MONTH),
    startDate.get(Calendar.DAY_OF_MONTH)
);
```
I strongly suggest you read some general java programming guides and the documentation for the Calendar class
https://developer.android.com/reference/java/util/Calendar.html
