### ISSUE TITLE
Add option to disable Window.FEATURE_NO_TITLE

### ISSUE THREAD

**Issue by nightmare00** [wdullaer/MaterialDateTimePicker#279]
Hi!
Somtehing like: 

` DatePickerDialog dpd = DatePickerDialog.newInstance(....);

dpd.showDialogTitle("dialog title")`

**Comment by wdullaer** [comment]
What's wrong with the current `setTitle()` option?

https://github.com/wdullaer/MaterialDateTimePicker#additional-options

**Comment by nightmare00** [comment]
I'm sorry for the delay!
The current title is very small. 
Users sometimes can not find a title. Is it possible to customize the header font size?
Thanks!

**Comment by wdullaer** [comment]
You can tweak these values by overwriting certain `mdtp_` prefixed values in your app.
However if you increase the title font size, the vertical space of the pickers and they probably won't work that well anymore on smaller screen sizes (the dialogs are rather big as is)

**Comment by wdullaer** [comment]
The pickers are also DialogFragments, so they can be embedded in your own Dialog, rather than the built-in logic. This should allow you to create exactly the behaviour you want.
