### ISSUE TITLE
Show only Year or Month Picker

### ISSUE THREAD

**Issue by manikavi** [wdullaer/MaterialDateTimePicker#280]
Hi,
  Please clarify this query,

1.Is it possible to show only Year or Month Picker?.If Yes how i have to do this?

**Comment by wdullaer** [comment]
This is currently not possible.
A month picker without a year would also need some layout tweaking (hide the weekdays, because they are not well defined in such a case)

**Comment by manikavi** [comment]
Could you please add this request in your library

**Comment by wdullaer** [comment]
Not any time soon.
I have only a very limited amount of time to work on this and there are a few more high priority features I'd like to get done

**Comment by luna-vulpo** [comment]
Still no hope?

**Comment by wdullaer** [comment]
Nope. Updating to the current material design standards and implementing a combined date and time picker will consume all the time I have to work on this for the foreseeable future.

**Comment by hasnain-ahmad** [comment]
@wdullaer Did you add functionality of only show the both of month and year in the `MaterialDateTimePicker`?

**Comment by wdullaer** [comment]
If there is any progress on this, I'll update the issue.
This is not something which is high priority at this point.

**Comment by hpatel4u** [comment]
Hi any update as i can see this is required since 2016

**Comment by wdullaer** [comment]
I will probably never implement this.
In order to make this intuitive the design will differ significantly making it essentially a seperate library. It's too far out of the current scope.

If someone ends up making this, I'll gladly link to it from the README.
