### ISSUE TITLE
monthOfYear returning 0

### ISSUE THREAD

**Issue by Queskr** [wdullaer/MaterialDateTimePicker#282]
Hi,

Using the code below (with jodaTime) fails due to monthOfYear returning 0 when a date in January 2017 is chosen.

        DatePickerDialog dpd = DatePickerDialog.newInstance(
                new DatePickerDialog.OnDateSetListener() {
                    @Override
                    public void onDateSet(DatePickerDialog view, int year, int monthOfYear, int dayOfMonth) {
                        DateTime time = new DateTime(year, monthOfYear, dayOfMonth, currentHourOfDay, currentMinuteOfHour);
                        setTime(new Instant(time));
                        listener.onCompleted();
                    }
                },
                dt.getYear(),
                dt.getMonthOfYear(),
                dt.getDayOfMonth()
        );
        dpd.show(mActivity.getFragmentManager(), "");

**Comment by wdullaer** [comment]
https://github.com/wdullaer/MaterialDateTimePicker#why-does-the-datepickerdialog-return-the-selected-month--1
