### ISSUE TITLE
How to change color of text ?

### ISSUE THREAD

**Issue by phucloc8697** [wdullaer/MaterialDateTimePicker#286]
I have a request that make the color of the unchosen text like the chosen one, not darker. Is it possible, and how can I do it if yes ? Thanks.

**Comment by wdullaer** [comment]
You can overwrite the `mdtp_*` prefixed colour values in your app to achieve this.
This isn't part of the "public API", so I won't promise that these will never change on a newer version.

I'm not exactly sure which pieces you want to change the colour of, but you can find the available values in `res/values/colors.xml`
