### ISSUE TITLE
Showing year picker first should show month view after clicking OK

### ISSUE THREAD

**Issue by dimsuz** [wdullaer/MaterialDateTimePicker#288]
Consider this scenario: my form has some kind of birthday date field and whenever user clicks on it, date picker is shown with `showYearPickerFirst=true`. Let's assume that field already contains some date picked earlier and user wants to change the day or month but not a year. So my app passes some initial date to MDTP and opens it.

The thing is that in this case when year picker is shown (first), the button `OK` will *close* the dialog while I would expect that it switches to a month view, i.e. continues the selection flow.

Just like it does when user picks a different year.

I.e. current flow is not very consistent in this case: If user picks another year than was preselected, the month view is shown next, but if user clicks OK on year picker (leaving the year unchanged), dialog gets closed. You could try it "live" to understand better. I feel that this is counterintuitive, but maybe it's just me?

If you are in favor of this change, I could submit a PR - I decided to ask before trying to implement this feature. Maybe I got something wrong.

**Comment by wdullaer** [comment]
Why is this counter intuitive?
It is consistent with the behaviour when showing the daypicker first, or the behaviour of the timepicker.

Clicking OK accepts the current selection and closes the dialog.

Selecting a a year auto advances to the day picker. Just like selecting hours in the timepicker will autoadvance to the minute picker.

The thing that bothers me is that it's not really clear how to get to the year picker, unless you make it appear first. (I didn't know there even was a year picker until I discovered it in the code)

**Comment by dimsuz** [comment]
It's a bit counterintuitive if I want to leave the year unchanged and change only month. Or day. In this case some users just click OK on year picker, waiting to be taken to the month view which is next. But instead the dialog closes. I observed it on several people in our office :)

I.e. if a user needs to select a different year, he would surely tap on it. But if year stays the same it is not obvious if tapping is needed (it's already highlighted) or if just OK can be clicked.

**Comment by dimsuz** [comment]
And yes, almost all notice that picking year is not that obvious. Not all figure out that it can be tapped to bring up a year picker. There are even reviews in Google Play that mention that they are quite bored to have to swipe all the way up/down only to choose a date from another year (in case it is +-5 or more years)

**Comment by wdullaer** [comment]
So here's a suggestion:
Show a year only picker, and then launch a date only picker from the callback.
In this case, you have to always click OK to advance to the next stage. (although there is no obvious way to return back to the year selection)

This isn't currently supported by the library, but could quite easily be implemented on the marshmallow layout I think.

I don't want to change the behaviour that the OK button closes the dialog.

**Comment by dimsuz** [comment]
This crossed my mind, but I didn't know that a stand alone year picker exists in this library.
How would I launch it?

I see only `YearPickerView` in my completion...

If you suggest to use `showYearPickerFirst` option and react on OK to show a non-`showYearPickerFirst` version, then I already tried that and it is not possible, because imagine these cases:

1. Show 1st dialog with year picker. User clicks OK. He proceeds to 2nd non-year-first dialog with a month view by following my custom logic. He clicks OK => all good
2. Show 1st dialog with year picker. User selects a year by *touching* it in list. He proceeds to month view automatically (still in 1st dialog). He clicks OK => *second* dialog is shown as per logic above

Currently there's no way to distinguish if user has tapped a year in year picker, or pressed OK there...

**Comment by dimsuz** [comment]
I.e. in second case user will see a month view twice which is not what was intended.

**Comment by wdullaer** [comment]
There is no stand alone year picker currently, but it shouldn't be too much work to do.
Especially the marshmallow layout is straightforward to adapt.
The original layout would require more changes to look nice when used as just a year picker.

**Comment by dimsuz** [comment]
I see! OK, thanks for clarification, good that I asked beforehand :) Will try to implement this customization locally.

**Comment by wdullaer** [comment]
I will take well written pull requests ;-)

The design I have in mind is making an option `enableYearPicker` and `enableDatePicker` (throw if show() is called when both are set to false)
Then don't render the year / date in the header and put a guard in autoAdvance()

**Comment by dimsuz** [comment]
I'll do one if I come up with a meaningful implementation.
And if both flags are 'true' - behavior is identical to a current version?

**Comment by wdullaer** [comment]
That's the idea yes.
The default should be the current behaviour
