### ISSUE TITLE
How do i get 12 Hours time AM and PV

### ISSUE THREAD

**Issue by focusteck** [wdullaer/MaterialDateTimePicker#291]
Hey,
First of all thanks for such an awesom work done. 
I was just trying to get selected values for AM and PM in 12 Hour time format. 
Any help is much appreciated.
Thanks

**Comment by wdullaer** [comment]
The last parameter in the `getInstance()` toggles 24 hour mode. (you want to set this to `false`)

```java
Calendar now = Calendar.getInstance();
TimePickerDialog tpd = TimePickerDialog.newInstance(
    TimePickerFragment.this,
    now.get(Calendar.HOUR_OF_DAY),
    now.get(Calendar.MINUTE),
    mode24Hours.isChecked()
);
```

**Comment by focusteck** [comment]
yeah i got that but how do i get the AM PM values after time is selected? 
In listener onTimeSet only returns below params
`new TimePickerDialog.OnTimeSetListener() {
                    @Override
                    public void onTimeSet(TimePickerDialog view, int hourOfDay, int minute, int second) {
                        tvTimeLastInspected.setText(hourOfDay + " : " + minute);
                    }
                }`

**Comment by wdullaer** [comment]
The callback always returns 24h values for better compatibility with the java `Calendar` class.
In case you really need to know whether it's am or pm, you can use the calendar class to figure it out

```java
Calendar someDate = Calendar.getInstance();
someDate.set(Calendar.HOUR_OF_DAY, hourOfDay);
someDate.set(Calendar.MINUTE, minute);
someDate.set(Calendar.SECOND, second);
if (someDate.get(AM_PM == Calendar.AM) System.println('The selected time is AM');
else System.println('The selected time is PM');
```

**Comment by focusteck** [comment]
Thanks (y)
