### ISSUE TITLE
how to get selected date?

### ISSUE THREAD

**Issue by pro100svitlo** [wdullaer/MaterialDateTimePicker#292]
Hi!

i need some method like:

`mDatePiker.getCurrentDate()`

that will return calendar with current (selected) date without opening dialog.
I was trying to make own datePiker dialog that extend your's one, but I can't get mCalendar from DatePickerDialog ... 
I think this can be useful for lot of people ;-)

also i have one more proposal: add compareDate function.
for example
   
```
/**
* true if newDate before endDate
*/
```
```
fun compareDate(newDate: Calendar?):Boolean{
            if (newDate != null ){
                var star = newDate.timeInMillis
                var end = mCalendar.timeInMillis
                if (end > star){
                    return true
                }
            }
            return false
        }
```

so will be glad to see this functions in new release )
please let me know if you will add tham

**Comment by wdullaer** [comment]
I don't understand the request?
If you don't intend to open the Dialog, then what's the point of the picker?
Just use `Calendar.getInstance()`

The `Calendar` class also includes methods to compare and manipulate dates, so use those. That's functionality that does not belong in a picker.

**Comment by pro100svitlo** [comment]
thanks for reply!
ok, maybe you are right...

one more question: what about change current date programmatically without recreating dialog?
for example startDate was changed by user, and after that i need to change endDate before dialog will be open?

**Comment by wdullaer** [comment]
I'm assuming you're rendering two dialogs here.
So that means you're creating the second Dialog in the callback of the first one. You can read the selection made in the first one and use that to manipulate the second one as needed.

You probably want to use an anonymous inner class rather than implement the callback interface on your Fragment/Activity
