### ISSUE TITLE
No resource found that matches the given name (at 'layout_above' with value '@id/seconds_space')

### ISSUE THREAD

**Issue by Lithium-HD** [wdullaer/MaterialDateTimePicker#293]
thanks for the library
with Gradle (compile 'com.wdullaer:materialdatetimepicker:3.0.0') in Android Studio, I'm getting this error on file (land\mdtp_time_header_label.xml). how to get rid of it?

and one more question. does this library support picking a date range or I should implement it myself?

**Comment by wdullaer** [comment]
Are you sure you're using the latest version?
If you are, I suggest doing a build clean (or whatever forces the library to be redownloaded). It sounds like a corrupted download to me.

The library doesn't support picking a date range. You could implement it yourself, or you can take a look at this fork: https://github.com/borax12/MaterialDateRangePicker

**Comment by Lithium-HD** [comment]
I have done clean & rebuild several times but the error's not fixed. I don't know why. And about picking a range I will implement it on this lib. Thanks

**Comment by wdullaer** [comment]
Can you show me the code and options you're using to create the dialog?

**Comment by Lithium-HD** [comment]
I get the error on gradle sync process and can't go farther than that

**Comment by wdullaer** [comment]
I can't reproduce that here, so I can't really help.
I find that gradle introduces just as much problems as it solves (and generally behaves like a big black box when combined with android studio)

**Comment by Lithium-HD** [comment]
it's ok. I imported the library and fixed the problem manually
thanks anyway :)

**Comment by wdullaer** [comment]
Did you have to change code in the library to fix this?
Can you let me know what you did?

**Comment by Lithium-HD** [comment]
in this layout file: "land\mdtp_time_header_label.xml", I just removed the line containing this: " android:layout_above=@id/seconds_space".

**Comment by wdullaer** [comment]
Can you give the exact error message you get which points to that line?

**Comment by Lithium-HD** [comment]
I wasn't able to test that with gradle on my current project so I made a new project and tested your library with gradle. I got no error. I don't know why but it is fixed

**Comment by wdullaer** [comment]
There might be a clash on the "seconds_space" id somewhere in your project or in one of your dependencies.
I'm happy you confirmed it works on a blank project, because I couldn't think of any reason that piece would call a compilation failure on its own

**Comment by Lithium-HD** [comment]
yes you're right. I just found out that this library ([](https://github.com/mohamad-amin/PersianMaterialDateTimePicker)) is using your classes and the name of resources are exactly the same. I refactored that library to have both libraries in my project

**Comment by wdullaer** [comment]
I prefixed most color and value resources, but not the id's in layouts.
I should probably do that as well to reduce the chances of this happening. (although if someone forks this library and doesn't bother to change the resource prefixes, you'll still run into the same issue)

**Comment by Lithium-HD** [comment]
thanks for your time. I'm still involved with the designation problems. trying to fix them...

**Comment by Kaminiak** [comment]
I have the same issue, when I try to use this library with that: https://github.com/borax12/MaterialDateRangePicker

**Comment by meddd** [comment]
when in sample (without any change, i get today and try) of  https://github.com/borax12/MaterialDateRangePicker add in build.gradle compile 'com.wdullaer:materialdatetimepicker:3.0.0', there is compile error describe in first post.
SO it is error of borax12 library or error in MaterialDateTimePicker ?
