### ISSUE TITLE
Google Calendar DatePicker Lookalike

### ISSUE THREAD

**Issue by roman-ku** [wdullaer/MaterialDateTimePicker#295]
Can we get a version of the datepicker that looks like the Google Calendar one.

Included picture for reference:

<img src="https://cloud.githubusercontent.com/assets/10580420/21748552/9df7be98-d53c-11e6-8c10-815be0b99201.png" width="400">

**Comment by roman-ku** [comment]
Also the following apps use that implementation:

* Google Keep
* Google Maps
* Transit

**Comment by wdullaer** [comment]
Have you taken a look at the new v2 layout?

**Comment by roman-ku** [comment]
Are you referring to this? This is the v2 layout I see.

<img src="https://camo.githubusercontent.com/e72e9ce81a905baac712a2e3c74ac47408f65b8e/68747470733a2f2f7261772e6769746875622e636f6d2f7764756c6c6165722f4d6174657269616c4461746554696d655069636b65722f67682d70616765732f696d616765732f646174655f7069636b65725f76322e706e67" width="400">

**Comment by wdullaer** [comment]
That's the one.
There are still some tweaks left to do on the margins and it still scrolls vertically, but that should eventually look like the current google guidelines

**Comment by roman-ku** [comment]
OK cool! Looking forward to using it. The Google Calendar picker is pretty slick.

By the way will this be v2 updated or a new v3 layout?

**Comment by wdullaer** [comment]
That would be an update to v2

**Comment by nizamsp** [comment]
right and left buttons near month is missing. I have seen users trying to scroll vertical in the calendar since a wall hanging calendar should be scrolled up. at least it should have a button indicator for left and right i think.

**Comment by wdullaer** [comment]
Yes, the left / right buttons are still on the todo list.
If it is too confusing, you can configure the calendar to scroll vertically regardless of which layout you are using.
