### ISSUE TITLE
Do you plan to add the Recurrence Picker too?

### ISSUE THREAD

**Issue by chrisonline** [wdullaer/MaterialDateTimePicker#296]
Is it planned to add the new recurrence picker from Google Calendar / Material Design?

**Comment by wdullaer** [comment]
That's not on the road map.
The goal is to implement these:
https://material.io/guidelines/components/pickers.html

I hardly have enough time to keep up with those :-)

**Comment by chrisonline** [comment]
OK thanks for the info.
