### ISSUE TITLE
Android support lib

### ISSUE THREAD

**Issue by podurets-ruslan** [wdullaer/MaterialDateTimePicker#298]
Is it possible to use android support libs v24 for Material DateTime Picker v3.0.0 or v3.1.0?

**Comment by wdullaer** [comment]
what's the problem with v25?

**Comment by podurets-ruslan** [comment]
Anything, but using v24 in app and don't want use v25 too. Can I exclude v25 via gradle and use v24?

**Comment by wdullaer** [comment]
I don't think it works that way. If you have build issues (I don't remember all the specifics on how android scopes dependencies when building), you should either update the support library version in your application or fork this one and downgrade the dependency.

**Comment by podurets-ruslan** [comment]
Thanx)
