### ISSUE TITLE
3.1.0 Regression - You can select non-selectable hours when using setSelectableTimes

### ISSUE THREAD

**Issue by jacobminer** [wdullaer/MaterialDateTimePicker#299]
Probably from the change in 7177c31, you can now drag the hour marker to select non-selectable times.

Observed on a Galaxy S7 Edge, Android 6.0.1.

Here are the times I'm passing into `timePicker.setSelectableTimes(times);`
<img width="404" alt="screen shot 2017-01-16 at 3 56 02 pm" src="https://cloud.githubusercontent.com/assets/13003765/22002904/736f0d9c-dc04-11e6-8ca3-646c1b584541.png">

![device-2017-01-16-154640](https://cloud.githubusercontent.com/assets/13003765/22002721/0a0bf442-dc03-11e6-9ea6-e536d2937072.png)

![device-2017-01-16-154654](https://cloud.githubusercontent.com/assets/13003765/22002722/0c4d51ce-dc03-11e6-9030-c32313bccf8a.png)

**Comment by wdullaer** [comment]
Confirmed, will try to get a fix out asap

**Comment by jkmckay** [comment]
This issue still persists on version 3.2.1:
The user can select a non-selectable time if they touch a hour/minute that is selectable and they drag their finger to a non-selectable hour/minute.

**Comment by wdullaer** [comment]
It seems it is not properly rounding the value when you actually release the touch.
This is not this regression, but a different issue. Would be better to track it in a different issue.
