### ISSUE TITLE
Gradle version?

### ISSUE THREAD

**Issue by Jdruwe** [wdullaer/MaterialDateTimePicker#3]
I can only find this version: compile 'com.wdullaer:materialdatetimepicker:1.0.0'
Not the 1.0.1 you listed in the docs.

**Comment by wdullaer** [comment]
Something must have gone wrong when I published on maven Central . I'll
take a look at it.

Op za 21 feb. 2015 10:47 schreef Jeroe <notifications@github.com>:

**Comment by wdullaer** [comment]
It is working fine for me here.
I also just checked maven.org and version 1.0.1 is properly listed.
Maybe it wasn't available yet when you tried (it takes some time after I publish before it is available), or it's some sort of cache issue.

![schermafbeelding 2015-02-22 om 09 55 42](https://cloud.githubusercontent.com/assets/6305221/6319654/394a46a8-ba79-11e4-986c-b0404a8d2c65.png)
