### ISSUE TITLE
 <merge /> can be used only with a valid ViewGroup root and attachToRoot=true

### ISSUE THREAD

**Issue by ruhaly** [wdullaer/MaterialDateTimePicker#302]
when i use snakebar,this problem has emerged.

 <merge /> can be used only with a valid ViewGroup root and attachToRoot=true

**Comment by wdullaer** [comment]
I'm sorry but I do not understand this issue?
What exactly is the problem? Can you elaborate, maybe show a screenshot of the issue and provide some code that reproduces it?

**Comment by ruhaly** [comment]
when i load this library 
![image](https://cloud.githubusercontent.com/assets/4638754/22189452/a0bc4e6a-e157-11e6-8751-a77febc53c62.png)

this problem has emerged,this is code:

![image](https://cloud.githubusercontent.com/assets/4638754/22189459/ab2f1c06-e157-11e6-822b-c0653be463ad.png)


![image](https://cloud.githubusercontent.com/assets/4638754/22189516/ebeb3248-e157-11e6-97d5-f92f592e2401.png)



When I don't use it, it's perfect,I can't understand why

**Comment by ruhaly** [comment]
https://git.oschina.net/ruhaly/MVVM-FRAME.git

this is my demo source ,you can try it ,add a activity and use snackbar

**Comment by wdullaer** [comment]
I'm not sure this is linked to my library.
Version 3.1 uses v25 of the support library, so try upgrading that dependency and see if the problem persists.

Also: the code in that repository doesn't seem to be the code that is giving an error: there is no line 77 in the LoginActivity file (which is where your stacktrace points to)

**Comment by ruhaly** [comment]
please switch to    the branch: water-os
and  add a snackbar in loginActivity

**Comment by ruhaly** [comment]
I gave a complete code, please update
switch to the branch: water-os

**Comment by ruhaly** [comment]
Can you help me see

**Comment by ruhaly** [comment]
I found, 
compile 'com.tbruyelle.rxpermissions:rxpermissions:0.9.1@aar'   
compile 'com.wdullaer:materialdatetimepicker:3.1.0'
They are in conflict
