### ISSUE TITLE
Screen stays dim after dismissing dialog

### ISSUE THREAD

**Issue by NickalasB** [wdullaer/MaterialDateTimePicker#311]
I assume there's probably an easy solution to this- when I set the time or cancel the TimePickerDialog the screen stays dim until you touch it again. Any help is appreciated. 

thank you  

 ```
 @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        final Calendar now = Calendar.getInstance();
        final TimePickerDialog timePickerDialog = TimePickerDialog.newInstance(
                TimePickerFragment.this,
                now.get(Calendar.HOUR_OF_DAY),
                now.get(Calendar.MINUTE),
                android.text.format.DateFormat.is24HourFormat(getActivity())
        );
        timePickerDialog.dismissOnPause(true);
        timePickerDialog.enableSeconds(true);
        timePickerDialog.setVersion(TimePickerDialog.Version.VERSION_2);
        timePickerDialog.setTitle("Chore Due By...");
        timePickerDialog.show(getActivity().getFragmentManager(), TIME_PICKER);
    }

    @Override
    public void onResume() {
        super.onResume();
        TimePickerDialog timePickerDialog = (TimePickerDialog) getActivity().getFragmentManager().findFragmentByTag(TIME_PICKER);
        if (timePickerDialog != null) {
            timePickerDialog.setOnTimeSetListener(this);
        }
    }
```

**Comment by wdullaer** [comment]
Can you reproduce this on multiple devices?
That code looks fine to me, and I've never seen this behaviour myself.

**Comment by NickalasB** [comment]
Yes issue is present on both Nexus 5 and Pixel. After setting time- screen
stays dim and seems as if activity is paused. Thank you for responding

**Comment by wdullaer** [comment]
Are both running the same android version?

Can you create a minimal application that reproduces this issue / does the included sample app exhibit this issue?

**Comment by NickalasB** [comment]
One is on Marshmallow and one is on Nougat

I created a small sample app that reproduces the same issue. Again- I'm sure it's something simple but I haven't been able to figure it out so thank you.

Here's the app
 https://nick_bradshaw@bitbucket.org/nick_bradshaw/materialdatetimepickersample.git

**Comment by wdullaer** [comment]
I checked out your code: you are in fact launching a Dialog in a Dialog.
Clicking the button launches the Dialog you created using the TimePickerFragment.
In the TimePickerFragment you launch the actual pickers, which are their own Dialogs.
After selecting the date and time, the inner Dialogs have been dismissed, but the callback in your activity does not dismiss the outer Dialog. Because the outer Dialog does not have any views anymore that are rendered, it just shows the dimmed background.

The solution would be to move the code launching the pickers out of a DialogFragment into the Activity, or alternatively calling `this.dismiss()` in `onTimeSet()` after you have called the Activity's callback.

```java
    @Override
    public void onTimeSet(TimePickerDialog view, int hourOfDay, int minute, int second) {
        mCalendar.set(Calendar.HOUR_OF_DAY, hourOfDay);
        mCalendar.set(Calendar.MINUTE, minute);
        mCalendar.set(Calendar.SECOND, second);

        mMillis = mCalendar.getTimeInMillis();
        mOnDueDateSelectedListenerCallback.onDueDateSelected(mMillis);
        this.dismiss();
    }
```

**Comment by NickalasB** [comment]
Thank you very much. I figured it would be something simple I was overlooking.
