### ISSUE TITLE
Can I change the style so it look more like default Android date picker?

### ISSUE THREAD

**Issue by SupreeSeekSter** [wdullaer/MaterialDateTimePicker#314]
I want the date picker to have left and right arrow. Just like default Android date picker.

![9df7be98-d53c-11e6-8c10-815be0b99201](https://cloud.githubusercontent.com/assets/19761196/22863321/78ab8764-f170-11e6-985a-739c4c2cc79c.png)

Can I do that?

**Comment by wdullaer** [comment]
Not right now
I want to eventually support this in the version 2 layout, but I haven't had the time recently
