### ISSUE TITLE
Do not mutate arguments of setMinDate and setMaxDate

### ISSUE THREAD

**Issue by inlacou** [wdullaer/MaterialDateTimePicker#316]
Hi,

If a calendar is passed to setMaxDate or setMinDate, time is reset to 00:00:00:000. Could this method create a copy of the passed calendar and reset time just on it?

It's not a huge issue, but I lost some precious time finding it and I hope others don't have to.

`trimToMidnight` could be changed to this, for example:

`private Calendar trimToMidnight(Calendar calendar) {
		Calendar copy = Calendar.getInstance();
		copy.set(Calendar.YEAR, calendar.get(Calendar.YEAR));
		copy.set(Calendar.MONTH, calendar.get(Calendar.MONTH));
		copy.set(Calendar.DAY_OF_MONTH, calendar.get(Calendar.DAY_OF_MONTH));
		copy.set(Calendar.HOUR_OF_DAY, 0);
		copy.set(Calendar.MINUTE, 0);
		copy.set(Calendar.SECOND, 0);
		copy.set(Calendar.MILLISECOND, 0);
		return copy;
	}`

**Comment by wdullaer** [comment]
The library doesn't take a deep copy of the Calendar you pass in.
Time is set to midnight to avoid weird rounding errors.

I'll see if I can improve this behaviour, but it's more an issue with how java (pass by reference) and java Calendar work (mutates internal state), than a bug in this library.
