### ISSUE TITLE
Disable/Disabling Specific Time Frame for Time Picker

### ISSUE THREAD

**Issue by devious33** [wdullaer/MaterialDateTimePicker#319]
Hello, Is there any way or method that we could use in order to disable certain timeframes as opposed to what setSelectableTimes() does? 
i.e. I wanna disable times between 8:00AM - 9:30AM and all others are still enabled

**Comment by wdullaer** [comment]
There is no such method right now.
You can either explode an Array of TimePoints and use that with setSelectableTimes.
Alternatively, you can extend this class and override `isOutOfRange()` with your own logic.

**Comment by devious33** [comment]
Okay thanks alot man. I'll give it a shot
