### ISSUE TITLE
Crashes when started from Fragment

### ISSUE THREAD

**Issue by SangeetaSoni** [wdullaer/MaterialDateTimePicker#32]
When I call the DateTimePicker on button click from fragment application crahes.

**Comment by wdullaer** [comment]
Well, this is working just fine for me.
So unless you can give me more information on how to exactly reproduce this, I'm going to have to assume that this is a problem with your code.

**Comment by SangeetaSoni** [comment]
Can you please provide the example of using it in fragment.

**Comment by wdullaer** [comment]
It works just the same as in an Activity.
Without any code or instructions on how to reproduce, there is not much I can do.

General coding questions are also much better off on stackexchange rather than this issue tracker.
