### ISSUE TITLE
Intermediate minutes dots

### ISSUE THREAD

**Issue by smelfungus** [wdullaer/MaterialDateTimePicker#322]
It there any solution to display intermediate minutes dots availiable like it's done in 7.1.1 system picker? 
Thank you.

![scr](https://cloud.githubusercontent.com/assets/3989453/23458874/a568cc80-fe86-11e6-8b5a-a82f9a2d363e.jpg)

**Comment by wdullaer** [comment]
This isn't possible right now

**Comment by DummyCo** [comment]
Would be nice to implement this enhancement
