### ISSUE TITLE
onDayOfMonthSelected method is not being called

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [wdullaer/MaterialDateTimePicker#324]
Hello.

I have created my own class by extending this `DatePickerDialog` like this:

    public class MyDatePicker extends DatePickerDialog {
         @Override
         public void onDayOfMonthSelected(int year, int month, int day) {
             super.onDayOfMonthSelected(year, month, day);
             Log.d("OOOO", "SELECTED " + year + "  " + month + "  " + day);

         }
    }

Then In my activity I launch my datePicker like this:

    Calendar now = Calendar.getInstance();
                DatePickerDialog dpd = MyDatePicker.newInstance(
                        MainActivity.this,
                        now.get(Calendar.YEAR),
                        now.get(Calendar.MONTH),
                        now.get(Calendar.DAY_OF_MONTH)
                );
                dpd.setVersion(DatePickerDialog.Version.VERSION_2);
                dpd.show(getFragmentManager(), "Datepickerdialog");

When my picker shows and I click on dates `onDayOfMonthSelected` is not firing. Does that means that this method is not callback? Or I'm missing something?

**Comment by wdullaer** [comment]
`onDayOfMonthSelected` is an internal method.
You need to implement the `OnDateSetListener` interface with the `onDateSet` method to obtain the selection of the Dialog. There is no need to extend the class.
Please go through the README which contains code examples and further information
