### ISSUE TITLE
Could set text size

### ISSUE THREAD

**Issue by wuyingtong** [wdullaer/MaterialDateTimePicker#327]
i use this library for the large devices，the font maybe little small

**Comment by wdullaer** [comment]
I try to use appropriate font sizes wherever possible.
That said, you can overwrite the font size by setting the correct `mdtp_` prefixed dimension in your own app.
Check the resource folder in the library to see which dimensions are defined and relevant for you

**Comment by wuyingtong** [comment]
Thank you for your reply！
