### ISSUE TITLE
How to get days of the week

### ISSUE THREAD

**Issue by Bekakk** [wdullaer/MaterialDateTimePicker#329]
Hi
I'm using your library.How i can receive like this datetime format FRI.FEB 2017?
this is my code

`     public class CalendarOnClickListener implements View.OnClickListener {
               @Override
        public void onClick(View v) {
            DatePickerDialog dpd = DatePickerDialog.newInstance(
                    new DatePickerDialog.OnDateSetListener() {
                        @Override
                        public void onDateSet(DatePickerDialog datePickerDialog, int year, int monthOfYear, int dayOfMonth) {

                            calendar.set(Calendar.YEAR, year);
                            calendar.set(Calendar.MONTH, monthOfYear);
                            calendar.set(Calendar.DAY_OF_MONTH, dayOfMonth);
                            ((TextView)mView.findViewById(R.id.departure_day_large)).setText(dayOfMonth+"");
                            ((TextView)mView.findViewById(R.id.departure_day_small)).setText(monthOfYear+","+year);

                        }
                    },
                    calendar.get(Calendar.YEAR),
                    calendar.get(Calendar.MONTH),

                    calendar.get(Calendar.DAY_OF_MONTH)
            );
            dpd.show(getActivity().getFragmentManager(), null);
        }
    }``

`

**Comment by DigitalChip** [comment]
> How i can receive like this datetime format FRI.FEB 2017?

```
       Calendar time = Calendar.getInstance();
       time.set(Calendar.HOUR_OF_DAY,hourOfDay);
       time.set(Calendar.MINUTE,minute);
       time.set(Calendar.SECOND,second);

       SimpleDateFormat sdfDate = new SimpleDateFormat("E.MMM yyyy");  // FRI.FEB 2017
       String strDate = sdfDate.format(time.getTimeInMillis());
```
strDate is you need format.

**Comment by Bekakk** [comment]
@DigitalChip  in onDateSet method does not has minute or second option

**Comment by DigitalChip** [comment]
@Bekakk This is part of my project, so there is a setting of minutes. I was inattentive...
