### ISSUE TITLE
Display Chinese have a problem？

### ISSUE THREAD

**Issue by tomhuahua** [wdullaer/MaterialDateTimePicker#33]
![g828 nd e ic9q dduytfo](https://cloud.githubusercontent.com/assets/5968293/7771504/66a0d364-00ca-11e5-9221-633854f0179d.png)

The figure I show up with a red box labeled that “周”，instead “周一、周二、周三...”.I do not know what went wrong, please take a look at the trouble

**Comment by wdullaer** [comment]
#29 is supposed to fix this.
I don't speak nor read Chinese so it's hard to judge for me, but comparing that pull request with your comment, it looks like it will do the job.

Please reopen this if the next release doesn't solve the issue.
