### ISSUE TITLE
HapticFeedbackController leak activity

### ISSUE THREAD

**Issue by bialek** [wdullaer/MaterialDateTimePicker#331]
Hi,

I have an activity which I don't want to recreate on orientation change, so I set android:configChanges="orientation|screenSize" in manifest file. When I did it I have problem with the date picker, if I open it, rotate device and go back to the previous activity, HapticFeedbackController.mContext leak my activity. How could I fix it?

**Comment by wdullaer** [comment]
Are you sure you're not holding on to an instance of the `Dialog`?
The `HapticfeedbackController` has a reference to the `Context`, but only the dialog has a reference to that. Once the `Dialog` is dismissed all of this will be freed.

**Comment by bialek** [comment]
@wdullaer I have instance variable to my datepickerdialog but I tried with such instance and without. I changed some things since I posted and actually I cannot reproduce problem so I hope it work now :).

**Comment by wdullaer** [comment]
Thanks for getting back on this.
I'll close this now. If you do manage to reproduce, you can reopen it (or create a new one referencing this)
