### ISSUE TITLE
I getting bellow error when adding gradle dependency

### ISSUE THREAD

**Issue by jainMadhur42** [wdullaer/MaterialDateTimePicker#333]
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

**Comment by wdullaer** [comment]
Are you sure this is linked to this library, because the resources that it's complaining about are android built-in ones.

**Comment by jainMadhur42** [comment]
Can yoy help me on this. Bcz i am getting this error only after adding this
dependency in my gradle.

On Fri, Mar 31, 2017, 5:13 PM wdullaer <notifications@github.com> wrote:

Are you sure this is linked to this library, because the resources that
it's complaining about are android built-in ones.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wdullaer/MaterialDateTimePicker/issues/333#issuecomment-290690687>,
or mute the thread

**Comment by wdullaer** [comment]
With the information you've provided, I cannot help you.
Based on what's in this issue, it's unlikely that this library is the root cause of your issue.
Try a build clean and look into your build chain.
