### ISSUE TITLE
Cancel has no meaning

### ISSUE THREAD

**Issue by jemshit** [wdullaer/MaterialDateTimePicker#334]
Hi, i'm having a problem: 
There is Cancel and Ok button. I change date, then no matter if i click Ok, Cancel or outside of dialog, dialog is dismissed and date is **set**. 
So what is the difference between Cancel and Ok ? I mean Cancel should cancel the selected date and don't change the date, Ok should change the date. This behaviour is also exist in SDK, thats why i try this library.

**Comment by wdullaer** [comment]
I think you have an implementation issue, because the callback is not called when you cancel or dismiss the Dialog.
Try the example app to see this in action

**Comment by jemshit** [comment]
In the sample project, you create DatePickerDialog from scratch every time, but i create it once and reuse it (why not?)

**Comment by wdullaer** [comment]
Because the Dialog is built with the assumption that it's going to be used once.
Not all initialisation happens properly when reused.

In general I do not think android Dialogs are meant to be reused.

**Comment by jemshit** [comment]
I do reuse AlertDialogs actually (for showing error or loading state), but anyway. I am creating new instance everytime now.
