### ISSUE TITLE
showing wrong date on (++dayOfMonth)

### ISSUE THREAD

**Issue by Shohrukhbek** [wdullaer/MaterialDateTimePicker#335]
I want to add +1 day to my selected date and show it in my `TextView`, all looks fine except for 1 thing. if current date is 31 on `(++dayOfMonth)` its showing in 32/MM/yyyy. How can I add it correctly? Should update my Calendar instance & check if there is a date or not?

**Comment by wdullaer** [comment]
Create a Calendar instance with the returned data, and roll that one day forward. It will do the necessary work for you.
