### ISSUE TITLE
Support library issue

### ISSUE THREAD

**Issue by kshitij-sminq** [wdullaer/MaterialDateTimePicker#338]
I get the following warning when I try to include your library. This issue came up when I updated your library from v2.1.2 to v3.1.3. I tried changing versions and found that this issue comes up on v3.0.0 and above. My support library version is 25.3.1

![screenshot from 2017-04-18 12-03-28](https://cloud.githubusercontent.com/assets/22586547/25117371/771c1764-242f-11e7-90e8-3c55846f7924.png)

**Comment by wdullaer** [comment]
This project also includes the support library. The versions must match. It looks like you're using an older version.

**Comment by kshitij-sminq** [comment]
I am using v25.3.1 which is the latest stable release at this time

**Comment by wdullaer** [comment]
I need to release a new version with that version

**Comment by kshitij-sminq** [comment]
Can you make it such that your library dependencies don't affect the projects that use your library?

**Comment by wdullaer** [comment]
This is really really hard on the jvm.
I'd have to write a custom class loader, adding significant complexity and brittleness.

**Comment by DAltena** [comment]
@kshitij-sminq you can actually avoid this issue by excluding the support libraries in your gradle file, like so:

compile ('com.wdullaer:materialdatetimepicker:3.2.2') {
        exclude group: 'com.android.support'
}

@wdullaer  do you foresee any issues doing this, or would this maybe be worth including in the readme? It seems to fix the issue on my end.

**Comment by wdullaer** [comment]
I wasn't aware you could do that with gradle.
Based on the docs this should do the trick.
Of course this puts the burden on the user to ensure that the version of the support library in the app is compatible with this library, but it will be in the majority of the cases.

I'll add this to the FAQ in the readme, and if I ever require a particular version the support library I'll try to explicitly mention it.
