### ISSUE TITLE
Updated newInstance methods

### ISSUE THREAD

**Issue by tir38** [wdullaer/MaterialDateTimePicker#339]
Two requests on `DatePickerDialog.newInstance` and `TimePickerDialog.newInstance`. Can you create new `newInstance` methods that do the following

1. put the callback as the last parameter, to make lambdas read better

```
DatePickerDialog datePickerDialogFragment = DatePickerDialog.newInstance((view, year, monthOfYear, dayOfMonth) -> {
    // TODO
}, 2017, 4, 19);
```

doesn't read as nice as 
```
DatePickerDialog datePickerDialogFragment = DatePickerDialog.newInstance(2017, 4, 10,
        (view, year, monthOfYear, dayOfMonth) -> {
            // TODO
        }
);
```

2. create a separate `newInstance` method that defaults to `now`? I imagine that a lot of people are already doing this:

```
DatePickerDialog dpd = DatePickerDialog.newInstance(
  MainActivity.this,
  now.get(Calendar.YEAR),
  now.get(Calendar.MONTH),
  now.get(Calendar.DAY_OF_MONTH)
);
```

If this is of interest, I'll issue a PR.

**Comment by wdullaer** [comment]
Adding an overloaded constructor that just takes now and the default selection is a good idea.

Changing the position of the parameters I'm not a big fan of. It results in a rather confusing API (if I keep both versions) and the gain is not big enough to justify a breaking API change (if I remove the current version)

**Comment by tir38** [comment]
You could always mark the old one as @Deprecated and add a note that it'll be removed in future versions...

... either way I'll see what I can cook up w.r.t. the overloaded constructor for `now`.

**Comment by wdullaer** [comment]
I've added the overloaded now constructor.
I'll think about deprecating the existing ones, although I'm not sure the friction is worth the benefit still.

I'll also try to release a new version somewhere this week that has all these changes in it

**Comment by tir38** [comment]
great thx.
