### ISSUE TITLE
Add ability to filter selectable days via some predicate

### ISSUE THREAD

**Issue by dewarder** [wdullaer/MaterialDateTimePicker#341]
Use case: I have to restrict ability to select weekends.

How can I do it now: create instance of `Calendar` for all days which I want to disable from `getStartDate()` to `getEndDate()`. By default start year is 1900 and end year is 2100. In this case huge amount of objects must be created. I can reduce boundaries via `setMinDate()` and `setMaxDate()`, but this solution is not good enough.

How can it be done: create some predicate that accept `Calendar` as parameter and return `boolean` which means disabled state of day.

If you decide that this idea is good I will try to implement this.

**Comment by wdullaer** [comment]
I am in the process of adding this.
The idea is that you implement an interface where you can use any logic to limit the selectable dates.

You can achieve the same thing right now by extending the class and overwriting `isOutOfRange`, `setToNearest`, `getStartDate` and `getEndDate`

I hope to release a version with this feature in the next few days

**Comment by wdullaer** [comment]
This is in 3.2.0
