### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by aiynmm** [wdullaer/MaterialDateTimePicker#346]
When I invoke `dpd.setDatePickerScrollOrientation(OrientationHelper.HORIZONTAL);` ,NullPointerException occurred.
There is the exception:java.lang.NullPointerException: Attempt to invoke virtual method 'void com.wdullaer.materialdatetimepicker.date.DayPickerView.setScrollOrientation(int)' on a null object reference.

**Comment by wdullaer** [comment]
This feature wasn't supposed to be in this release, I must have made a mistake when switching between my different branches.

So this is coming up, I'll try and patch it up shortly so it doesn't blow up if you accidentally try to use it.
