### ISSUE TITLE
Change select date's background color

### ISSUE THREAD

**Issue by Bekakk** [wdullaer/MaterialDateTimePicker#347]
Hi
I'm using this repo and i have two questions
1) Is it a possible to change only selected date's background color.I'm using setAccentColor ,but not working only selected date
2) How i can get calendar's custom date.I mean,how i can select form example 20 jun in first time?

Thanks

**Comment by wdullaer** [comment]
1. This is not officially supported (and I don't really want to go to that level of customisation). You can overwrite the relevant color resource in your app, or if you need more control, fork the library
2. The initial selection is passed when you call `DatePickerDialog.newInstance()`

**Comment by InfoAndroid** [comment]
you can change color 
"<color name="mdtp_date_picker_selector"># your color </color>"  add this in your app color.xml
