### ISSUE TITLE
Cannot use library when Fragment is support.v4.fragment

### ISSUE THREAD

**Issue by reverseBitsTech** [wdullaer/MaterialDateTimePicker#348]
Hi, Nice library, But when i am using it in android.support.v4.app.Fragment then i was not able to use show method. It requires getFragmentManager from old android.app.Fragment class.
How can i use library in this case?

**Comment by wdullaer** [comment]
https://github.com/wdullaer/MaterialDateTimePicker#why-not-use-supportdialogfragment

Provided you run on Android 3+ you can just call `getActivity().getFragmentManager()`, both can exist side by side

**Comment by ericmguimaraes** [comment]
would'n be a good idea to add that comment to the docs?

**Comment by wdullaer** [comment]
That comment is in the FAQ actually ;-)
