### ISSUE TITLE
[Feature request] - Use colorPrimary attribute

### ISSUE THREAD

**Issue by fmeneuhe** [wdullaer/MaterialDateTimePicker#35]
Hi,
It would be nice the library uses the colorPrimary and colorPrimaryDark attributes to get the Material colors instead of overriding "mdtp_accent_color" and "mdtp_accent_color_dark". I change the theme at runtime overriding the colorPrimary  attribute.

**Comment by wdullaer** [comment]
This one shouldn't be too hard. I'll try to get it in for the next release

**Comment by eeieeipoo** [comment]
I agree this would be a very nice touch to make the Picker seamlessly flow with many app designs!

**Comment by wdullaer** [comment]
I misjudged this one.

`?attr/colorPrimary` and `?attr/colorPrimaryDark` are defined by AppCompat, which this library actually doesn't use. You can also define an attribute just once, so defining them in this library will give compilation errors when using AppCompat in your application.

I currently don't see an elegant way of doing this.

Is the following not working for you guys?
```xml
<color name="mdtp_accent_color">?attr/colorPrimary</color>
<color name="mdtp_accent_color_dark">?attr/colorPrimaryDark</color>
```

**Comment by fmeneuhe** [comment]
The first thing I tried was including 
<code>
</code>

**Comment by fmeneuhe** [comment]
The first thing I tried was the solution you say, but it gives a crash inflating XML, at least with AppCompat, in both pre and Lollipop devices.
So, in my App, I color backgrounds using "?attr/colorPrimary" on "background" attribute because if you use the attribute either in a "color" label or "drawable" the code crashes. 
If the library does not use AppCompat I will have to modify the library into my project to fit my requirments, because my app, the material theme can be changed at runtime.

**Comment by KlausConrado** [comment]
I agree with this feature request, it would be much more simpler just use colorPrimary and colorPrimaryDark.
I don't see any problem in this lib start using AppCompat. Most apps already use it.

Thanks.

**Comment by wdullaer** [comment]
I don't want to pull in AppCompat unless I absolutely need to.

I'm going to take a closer look at why the workaround of assigning `?attr/colorPrimary` to the colours crashes though.

**Comment by wdullaer** [comment]
Library will use `colorAccent` as of v1.5.0
