### ISSUE TITLE
How to show date time Picker both?

### ISSUE THREAD

**Issue by vihangptl** [wdullaer/MaterialDateTimePicker#350]
How can I combine your date dialog and time dialog in one DateTime dialog?

**Comment by wdullaer** [comment]
There's no out of the box solution for this.
I think most people trigger the `TimePickerDialog` from the callback of the `DatePickerDialog`.

Alternatively you can try to build your own `Dialog` using the picker as `Fragments`.

There are no plans to change any of this in the near future.

**Comment by AsadAlihp** [comment]
@wdullaer hi I have been trying to implement more than one timepickers in same activity but failing. Is it possible to take minutes and hours from different timepickers??

**Comment by CoderYellow** [comment]
> There's no out of the box solution for this.
> I think most people trigger the `TimePickerDialog` from the callback of the `DatePickerDialog`.
> 
> Alternatively you can try to build your own `Dialog` using the picker as `Fragments`.
> 
> There are no plans to change any of this in the near future.

Can you be more specific please.Is there a listener like `date click listener`  to  trigger the `TimePickerDialog` in the `DatePickerDialog`
