### ISSUE TITLE
setTheme to DatePickerDialog

### ISSUE THREAD

**Issue by Samadhan-Medge** [wdullaer/MaterialDateTimePicker#352]
How I can set different theme to DatePickerDialog?

Suppose I have set AppThemeBlue to Activity  and using a fragment with AppThemeGreen in same activity. In this case DatePickerDialog showing AppThemeBlue(i.e Activity Theme) but I have to set AppThemeGreen. Need to set theme to DatePickerDialog dynamically.

**Comment by wdullaer** [comment]
https://github.com/wdullaer/MaterialDateTimePicker#additional-options

Use `setAccentColor`

**Comment by Samadhan-Medge** [comment]
Thanks @wdullaer its working fine
