### ISSUE TITLE
Disable the Weekdays and enable only weekend days

### ISSUE THREAD

**Issue by kanagalingam** [wdullaer/MaterialDateTimePicker#354]
Hi,
I am not able to find the way to disable the weekdays and enable only weekends(Saturdays and Sundays) in MaterialDateTimePicker

**Comment by wdullaer** [comment]
You need to implement your own `DateRangeLimiter`
https://github.com/wdullaer/MaterialDateTimePicker#how-do-i-use-my-custom-logic-to-enabledisable-dates

**Comment by jclova** [comment]
Actually, using a custom DateRangeLimiter is not possible remove some set of days within the range (e.g. all Saturdays and Sundays).
Looks like the only choice is to list all set of days you want to exclude and add to the filter manually using the setDisabledDays(). :(
