### ISSUE TITLE
Date and Time Picker Title

### ISSUE THREAD

**Issue by mitsus** [wdullaer/MaterialDateTimePicker#356]
Hi,
I try to set Title for Date and Time picker...but I'm not able to see it show.
Where I wrong?

Thanks a lot

**Comment by wdullaer** [comment]
Take a look at the README and the sample app in this repository.
If you have issues, stackoverflow is probably a better place to ask for assistance on how to write code.
Github is where I like to track actually bugs in the library.

In any case, you will need to share some code if you expect people to help. Your current message does not contain anything of use.
