### ISSUE TITLE
Using setTimeInterval eats up the CPU/GPU

### ISSUE THREAD

**Issue by tir38** [wdullaer/MaterialDateTimePicker#357]
When displaing a `TimePickerDialog`, if I don't use `setTimeInterval()` then I can spin my finger all day long and the cpu/gpu keep up. 

![working_well](https://cloud.githubusercontent.com/assets/1980553/26373796/f4228092-3fd0-11e7-8097-e221689e32a7.gif)

If I then add a `setTimerInterval(1,5)` It just eats up the GPU/CPU cycles and I have massive frame drops.

![not_working](https://cloud.githubusercontent.com/assets/1980553/26373802/fb9a0dea-3fd0-11e7-9cc0-fa2000c5e176.gif)

**Comment by wdullaer** [comment]
This doesn't surprise me.
As the docs state: `setTimeInterval()` is just some naive sugar around `setSelectableTimes()`.
The rounding logic does not scale well as a function of the size of the argument of `setSelectableTimes()` and `setTimeInterval()` makes it very easy to create big bit arrays of selectable times when you set the resolution rather fine grained (as you just did in this example).

I was in the process of revisiting this part of the code, so the next minor release should see some improvement here (but I'm not making any promises yet)

**Comment by wdullaer** [comment]
I've refactored how this is done internally.
Could you try your benchmarks again and see if the performance is better.
It will never reach the same performance as when you're not limiting any timepoints, but it shouldn't be this bad anymore

**Comment by tir38** [comment]
I'm no longer working on the project that uses this library so you'll have to test yourself, but it should be pretty straight forward. Feel free to close this issue if you've fixed the problem.

**Comment by joanvilab** [comment]
Is this solved??

**Comment by wdullaer** [comment]
I've improved the performance quite a bit, this shouldn't be an issue any more.
In case your interval is so fine grained that it's still causing issues (even searching in a big tree isn't totally free), you can implement your own TimeRangeLimiter with something specific for your needs that's lighter on resources than the default implementation.

**Comment by joanvilab** [comment]
I've missed to add the seconds interval and now it works perfect, thanks!
