### ISSUE TITLE
Month Name issues in OS version : below 5 

### ISSUE THREAD

**Issue by parthvora112** [wdullaer/MaterialDateTimePicker#360]
![screenshot_1](https://cloud.githubusercontent.com/assets/3677984/26754218/06a22ecc-4894-11e7-8a82-bda4ee746e11.png)

**when using Locale**
 ```
 Locale locale = new Locale("en");
        Locale.setDefault(locale );
        Configuration config = new Configuration();
        config.locale = locale;
        mContext.getResources().updateConfiguration(config, mContext.getResources().getDisplayMetrics());
```

Please help me

**Comment by wdullaer** [comment]
Are you manually  setting the locale?

**Comment by parthvora112** [comment]
Yes, because my application support multiple language.

**Comment by wdullaer** [comment]
Why not let the device select it's own locale?
And are you sure you're using a valid locale string, or that the locale is present / supported on the device you are using?

**Comment by parthvora112** [comment]
I got solution, Thanks for your support 

Solution :+1: 
```
Locale locale = new Locale("**en_us**");
       Locale.setDefault(locale );
       Configuration config = new Configuration();
       config.locale = locale;
       mContext.getResources().updateConfiguration(config, mContext.getResources().getDisplayMetrics());
```
