### ISSUE TITLE
How to increase font size or to zoom dialogue picker

### ISSUE THREAD

**Issue by farhanmubasher** [wdullaer/MaterialDateTimePicker#365]
Dialogue pickers are little bit small to select, can i increase their font size or can i zoom them ? so that i can easily select date and time.

**Comment by wdullaer** [comment]
You can override the `mdtp_*` font size values in your app.
On phones the fonts are comparable to the built in date pickers, but the spacing is a bit too tight.
I intend to improve this, but haven't found the magic incantation yet
