### ISSUE TITLE
Convert date into different Language !

### ISSUE THREAD

**Issue by deshario** [wdullaer/MaterialDateTimePicker#367]
String date_vb = dayOfMonth+"/"+(++monthOfYear)+"/"+year;
  date_birth.setText(date_vb );  //  Output = 29/06/2017

Can i convert the date_vb into different language [th] ?
Friday/June/2017 Something like this or any other format that was in word !

**Comment by wdullaer** [comment]
That's beyond the scope of this library.
Take a look at `java.util.Calendar` and `java.text.DateFormat`
https://developer.android.com/reference/java/text/DateFormat.html
