### ISSUE TITLE
getting error for land/mtdp_time_header_label.xml

### ISSUE THREAD

**Issue by christianCallelero** [wdullaer/MaterialDateTimePicker#369]
I solve it in my project but i think it should be fixed generally. So the error is coming from the the layouts that uses attributes that use "@id". It needs to be change to "@+id". Please disregard this if its a duplicate. 

Errors: 
```
error: Error: No resource found that matches the given name (at 'layout_toLeftOf' with value '@id/mdtp_separator')
error: Error: No resource found that matches the given name (at 'layout_alignBaseline' with value '@id/mdtp_separator')

Error: No resource found that matches the given name (at 'layout_alignBottom' with value '@id/mdtp_separator')

Error: No resource found that matches the given name (at 'layout_above' with value '@id/mdtp_seconds_space')

```

**Comment by wdullaer** [comment]
I will take a look

**Comment by wdullaer** [comment]
This should be fixed in https://github.com/wdullaer/MaterialDateTimePicker/commit/5fd6bedf46f50de1b8fb97b607f60f70669899b7

I will try to release a new version shortly

**Comment by christianCallelero** [comment]
ok thank you.
