### ISSUE TITLE
How do i Compare the time and restrict and set seelcted false?

### ISSUE THREAD

**Issue by sejalbaraiya** [wdullaer/MaterialDateTimePicker#370]
I have a restriction like,
I have a start and end time both are in 24hour format so there is no AM and PM 
so I have to restrict start time at 2 to 3 after 3 I can select the time ...and I can select up to 1:45 only coz I have given 15 min interval 
then at the end time when the start time is 2 then I can not select the 2 and max time is 3.
so how can I give the restriction using your Time Picker

**Comment by wdullaer** [comment]
I do not fully understand the question.
You are showing 2 pickers?
