### ISSUE TITLE
setStartTime(hours,minuts) not working

### ISSUE THREAD

**Issue by prashantpag26** [wdullaer/MaterialDateTimePicker#371]
when i use setSelectableTimes(timePointArray)
and after i set time by setStartTime(hours,minuts) where hours is also available in timePointArray.
but its select default 00 time for 24 hours

**Comment by wdullaer** [comment]
I don't understand your problem.
24h is the same as 0h
Maybe show a screenshot with a code snippet and indicate what the expected outcome is.
