### ISSUE TITLE
If Select AM Time picker is giving me PM and PM is giving AM

### ISSUE THREAD

**Issue by hemanthkaipaa** [wdullaer/MaterialDateTimePicker#372]
In TimePickerDialog.JAVA

else {
            OnClickListener listener = new OnClickListener() {
                @Override
                public void onClick(View v) {
                    // Don't do anything if either AM or PM are disabled
                    if (isAmDisabled() || isPmDisabled()) return;

                    tryVibrate();
                    int amOrPm = mTimePicker.getIsCurrentlyAmOrPm();
                    if (amOrPm == AM) {
                        amOrPm = PM;
                    } else if (amOrPm == PM) {
                        amOrPm = AM;
                    }
                    mTimePicker.setAmOrPm(amOrPm);
                }
            };

has to modify.. 

my Code:-
   @Override
    public void onTimeSet(TimePickerDialog view, int hourOfDay, int minute, int second){

        try {

            Calendar calendar = Calendar.getInstance();
            calendar.set(Calendar.HOUR,hourOfDay);
            calendar.set(Calendar.MINUTE,minute);
            calendar.set(Calendar.SECOND,second);
            textViewStartTime.setText(startTimeFormat().format(calendar.getTime()));

             ***** Here I'm getting AM =1 and PM =0****************
            System.out.println("ampm "+calendar.get(Calendar.AM_PM));

            calendar.add(Calendar.HOUR,initialTimeCount);
            hourOfDay=calendar.get(Calendar.HOUR);
            textViewEndTime.setText(startTimeFormat().format(calendar.getTime()));
            this.hourOfDay=hourOfDay;
            this.minute=minute;
            this.second=second;
            System.out.println(hourOfDay);
        } catch (Throwable e) {
            e.printStackTrace();
        }

    }

**Comment by hemanthkaipaa** [comment]
Right now for Temporary I'm simply modifying my code to
 Calendar calendar = Calendar.getInstance();
            calendar.set(Calendar.HOUR,hourOfDay);
            calendar.set(Calendar.MINUTE,minute);
            calendar.set(Calendar.SECOND,second);
            if (calendar.get(Calendar.AM_PM)!=0){
                calendar.set(Calendar.AM_PM,0);
            }else{
                calendar.set(Calendar.AM_PM,1);
            }
            textViewStartTime.setText(startTimeFormat().format(calendar.getTime()));
            System.out.println("ampm "+calendar.get(Calendar.AM_PM));

**Comment by wdullaer** [comment]
The callbacks return `Calendar.HOUR_OF_DAY` not `Calendar.HOUR`

**Comment by hemanthkaipaa** [comment]
Yeah,..!

**Comment by hemanthkaipaa** [comment]
that's why I've closed this
