### ISSUE TITLE
BUTTON_NEUTRAL

### ISSUE THREAD

**Issue by mcxinyu** [wdullaer/MaterialDateTimePicker#376]
How can I add a neutral button?

**Comment by wdullaer** [comment]
Can you give a bit more explanation?
What is the button supposed to do?
Maybe provide a small mockup.

**Comment by mcxinyu** [comment]
This is what I use android.app.DatePickerDialog implementation:

`DatePickerDialog dialog = new DatePickerDialog(this, new DatePickerDialog.OnDateSetListener() {
        @Override
        public void onDateSet(DatePicker view, int year, int month, int dayOfMonth) {
                calendar.set(year, month, dayOfMonth);
                Date date = calendar.getTime();
                startActivity(SingleNewsListActivity.newIntent(MainActivity.this, date));
                }
        }, mYear, mMonth, mDay);
        **dialog.setButton(BUTTON_NEUTRAL, getString(R.string.ramdom_data), new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int which) {
                startActivity(SingleNewsListActivity.newIntent(MainActivity.this, getRandomDate()));
                }
        });**

        dialog.show();`

**Comment by wdullaer** [comment]
The pickers can be embedded in a custom dialog, allowing you to show effectively any buttons you want.

**Comment by mcxinyu** [comment]
thank!

**Comment by mcxinyu** [comment]
How to do it?
