### ISSUE TITLE
Can not use android.support.v4.app.Fragment?

### ISSUE THREAD

**Issue by Pennan** [wdullaer/MaterialDateTimePicker#381]

**Comment by Pennan** [comment]
?

**Comment by aiynmm** [comment]
The part of FAQ ,have you seen Why not use SupportDialogFragment?Maybe it can help you!

**Comment by aiynmm** [comment]
The part of FAQ ,have you seen Why not use SupportDialogFragment?Maybe it can help you!@Pennan

**Comment by wdullaer** [comment]
https://github.com/wdullaer/MaterialDateTimePicker#why-not-use-supportdialogfragment
