### ISSUE TITLE
setDisabledDays  function error

### ISSUE THREAD

**Issue by liziNo1** [wdullaer/MaterialDateTimePicker#384]
When I disabled all the dates,it will never show and will broke down。

**Comment by wdullaer** [comment]
Can you elaborate a bit more?
Also: why would you disable all the days? If the user cannot select any days, wouldn't it be better to disable the button that shows the picker, rather than confuse the user with a dialog that is essentially useless?

**Comment by Atomico001** [comment]
Hi, i have this problem too. I dinamically disable some days and when i disable all the calendar don't show up and it freeze my app.

At your question: i have an app to booking, sometimes no days are available and i want a calendar with all grey days.
