### ISSUE TITLE
Question: Possibility to use for calendar style apps?

### ISSUE THREAD

**Issue by ridcully99** [wdullaer/MaterialDateTimePicker#388]
Your calendar is really well done and looks great. We would love to use it for a calendar like app, so here are a few questions: Is there a way, or is it planned, to
 - embed the calendar into an activity or fragment layout?
 - show event markers (e.g. colored dots)?
 - select a date range instead of just one day?

Thank you.

**Comment by wdullaer** [comment]
I'm afraid I don't have a lot of good news for you.

### Embed calendar into activity or fragment layout
No plans at the moment. You can use the code in this library as a starting point though.
If you find an easy refactor to make reusing the calendar view easier, do let me know or make a PR.
I have a feeling this could make this library easier to support.

### Show event markers
There is a feature to highlight certain dates. Currently this renders them in bold, but I intend to change that to a circle line around the date.
I have no plans to turn this into full blown event marker support at the moment.
It should be easy enough to extend this, should you decide to fork / base your calendar component off this library

### Date range
No support planned. There is a DateRangePicker library (https://github.com/borax12/MaterialDateRangePicker), which forked this one and uses a tabbed layout to allow users to select a start and end date.

**Comment by ridcully99** [comment]
Thanks for your answer and the hints on how to proceed. Will give it a shot and provide a PR if I manage to get somewhere.
