### ISSUE TITLE
Set the Locale?

### ISSUE THREAD

**Issue by Spiderbezno** [wdullaer/MaterialDateTimePicker#39]
Is it possible set the locale for change language??

**Comment by wdullaer** [comment]
The library uses the locale of the current device. I don't see any problem with that.

**Comment by Spiderbezno** [comment]
I have application where I can change the language of it, the calendar would changed? 
El 4/6/2015 20:48, wdullaer <notifications@github.com> escribió:The library uses the locale of the current device. I don't see any problem with that.

**Comment by wdullaer** [comment]
I think you better try to set the locale globally and rely on the android framework to recreate all your activities in the new locale.

Here's a stackexchange post that explains how you could go about this. Like the author of that post I would recommend against this though.

http://stackoverflow.com/questions/2900023/change-language-programatically-in-android

**Comment by Spiderbezno** [comment]
Thx 
El 6/6/2015 11:39, wdullaer <notifications@github.com> escribió:I think you better try to set the locale globally and rely on the android framework to recreate all your activities in the new locale.

Here's a stackexchange post that explains how you could go about this. Like the author of that post I would recommend against this though.

http://stackoverflow.com/questions/2900023/change-language-programatically-in-android
