### ISSUE TITLE
Gradle build failed.

### ISSUE THREAD

**Issue by LeeReindeer** [wdullaer/MaterialDateTimePicker#390]
when I use the 26 version of the Android Support Libraries, it failed to build.
```
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.wdullaer:materialdatetimepicker:3.2.2'
```
if i commented ` compile 'com.wdullaer:materialdatetimepicker:3.2.2'`,it works well.

**Comment by wdullaer** [comment]
The current published version of the library depends on an older version of the support library.
Java cannot use 2 different versions of the same package namespace, so this could generate an error.

Try adding this clause from the README in your `build.gradle`
https://github.com/wdullaer/MaterialDateTimePicker#how-do-i-use-a-different-version-of-the-support-library-in-my-app
That way, the version of the support library from materialdatetimepicker won't be used.

Alternatively, you can wait until I publish a version that depends on a newer version of the support library.

**Comment by wdullaer** [comment]
v3.2.3 uses support library v26.0.1, which should fix your build

**Comment by yaseen-homage** [comment]
Can you update it to 26.1.0. I still have issues even after addding 
`compile ('com.wdullaer:materialdatetimepicker:3.3.1') {
        exclude group: 'com.android.support'
}` in gradle.

**Comment by wdullaer** [comment]
That exclude statement should work. Exactly which error are you getting?

**Comment by yaseen-homage** [comment]
I'm getting the foolowing error in console `Error:Execution` failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.1) from [com.android.support:support-v13:26.0.1] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:customtabs:26.1.0] AndroidManifest.xml:25:13-35 value=(26.1.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

**Comment by wdullaer** [comment]
Are you sure there are no other dependencies with subdependencies on the support library (such as firebase)?
Are you explicitly declaring MaterialDateTimePickers support library dependencies in your app? (all of them need to be there)
