### ISSUE TITLE
It's not possible to use android.support.v4.app.Fragment

### ISSUE THREAD

**Issue by abiemann** [wdullaer/MaterialDateTimePicker#395]
```
        android.support.v4.app.Fragment thisfrag = this;
        dpd.show(thisfrag, "Datepickerdialog");
```

results in 

Error:(180, 12) error: no suitable method found for show(Fragment,String)
method DialogFragment.show(FragmentManager,String) is not applicable
(argument mismatch; Fragment cannot be converted to FragmentManager)
method DialogFragment.show(FragmentTransaction,String) is not applicable
(argument mismatch; Fragment cannot be converted to FragmentTransaction)

is there a solution ?

**Comment by wdullaer** [comment]
https://github.com/wdullaer/MaterialDateTimePicker#why-not-use-supportdialogfragment
