### ISSUE TITLE
Disallow year selection

### ISSUE THREAD

**Issue by sbaar** [wdullaer/MaterialDateTimePicker#40]
I'm attempting to have the user pick a date up to one month in advance. Therefore they should only be able to select the next year when it is currently december. So, in december when we call 
picker.setYearRange(curYear,curYear+1); then the picker works as intended. However, at all other times the year should not be selectable. In that case, there will always be a year range for the user to select. Either curYear to curYear+1 or if unset then any year. There is no way to disallow year selection, although it is necessary for many use cases.

**Comment by wdullaer** [comment]
I think the functionality you're looking for is `setMinDate()` and `setMaxDate()`
However, if you swap the year it will still allow you to select an unacceptable date.

I've changed the input validation on `setYearRange()` to allow `setYearRange(curYear,curYear)`.
This won't disable the year picker, but will solve your issue.

Should be available in the next release.
