### ISSUE TITLE
error in dependency build.gradle  

### ISSUE THREAD

**Issue by dondeepak** [wdullaer/MaterialDateTimePicker#400]
when is use dependency in my build.gradle
  compile 'com.wdullaer:materialdatetimepicker:3.3.0'
i am getting error 
![datepick](https://user-images.githubusercontent.com/24863950/30149413-1fb6c734-93c5-11e7-8fd4-4cb034bd71b2.png)
how do i fix this please

**Comment by wdullaer** [comment]
As of v26.x.x, the support library is no longer supplied as a download in android studio, but made available through a google hosted maven repository.
https://developer.android.com/topic/libraries/support-library/setup.html#add-library

You'll need to add the following to your application's `build.gradle` file

```groovy
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}
```

**Comment by Farhad2015** [comment]
```
maven {
     url "https://maven.google.com"
 }
```
after add this line of code, I get this error- 
![capture](https://user-images.githubusercontent.com/10769565/30807471-c86b1506-a21b-11e7-86a3-7d93113954c4.PNG)

(I am using Clean Project and Rebuild Project - but nothing happen)

**Comment by wdullaer** [comment]
Good, it is now loading the support library from the google maven repository.
If you read the error message, you'll see that it says that you are trying to load two different versions of the support library (and therefore, it doesn't know which one to pick).
If you look in the FAQ of this library, you'll see how to fix that:
https://github.com/wdullaer/MaterialDateTimePicker#how-do-i-use-a-different-version-of-the-support-library-in-my-app

**Comment by Farhad2015** [comment]
I create a brand new project and add this library according to FAQ. I appear new problem now. 

![capture](https://user-images.githubusercontent.com/10769565/30897754-c01b2b98-a379-11e7-8cdc-52f3b31da826.PNG)

**Comment by wdullaer** [comment]
This library also depends on support.design which you have not declared in your top level dependencies.
Please take a closer look at how gradle version management works
https://docs.gradle.org/current/userguide/dependency_management.html#sub:version_conflicts

**Comment by Farhad2015** [comment]
Thank you @wdullaer  for your answer. I resolve that error just **compile 'com.android.support:appcompat-v7:26.0.1'** instead of **compile 'com.android.support:appcompat-v7:26.+'**.
