### ISSUE TITLE
Hiding year

### ISSUE THREAD

**Issue by NeerajaReddyKomma** [wdullaer/MaterialDateTimePicker#401]
How can i hide year selection when i use DateRange Limitter? 
Ex: I have limited calendar to april 2017 to March 2018. Then it is showing both 2017 and 2018 years. On selecting 2018 nothing happend. So, I wanted to hide year selection

**Comment by wdullaer** [comment]
When you select a different year, it should round the selection to the nearest acceptable one. (31st of march most likely in this case)
If it doesn't do that, it's a bug.

**Comment by NeerajaReddyKomma** [comment]
How to set that can u let me know.. I dnt want to display the year itself

**Comment by wdullaer** [comment]
The year cannot be hidden
