### ISSUE TITLE
Query: Is there any method to disable recurring days?

### ISSUE THREAD

**Issue by perrygarg** [wdullaer/MaterialDateTimePicker#402]
Is there any way by which I can tell this library to disable all Wednesdays coming in future?

Thanks.

**Comment by wdullaer** [comment]
Not out of the box.
You can pass in your own implementation of `DateRangeLimiter` easily though.
Do please take a look at the annotation on the interface definitions. You are also on the hook to make sure the different methods there are internally consistent.

**Comment by perrygarg** [comment]
Hi @wdullaer ,

Thanks for response. I was not able to disable recurring days. However, I am able to disable specific days in coming 2 months/3 months but not all days in future. Can you please demonstrate by giving an code snippet example? Thanks in advance.

**Comment by wdullaer** [comment]
Like I said, this is not supported out of the box.
The way to go is to override the default implementation of DateRangeLimiter by supplying a class that implements the interface
https://github.com/wdullaer/MaterialDateTimePicker/blob/master/library/src/main/java/com/wdullaer/materialdatetimepicker/date/DateRangeLimiter.java

The names of the methods should be self explanatory (but I'll write some additional comments nonetheless)

You then set your implementation to the DatePicker. Pseudocode:

```java
Calendar now = Calendar.getInstance();
DatePickerDialog dpd = DatePickerDialog.newInstance(
    new DatePickerDialog.OnSelectedListener() {},
    now.get(Calendar.YEAR),
    now.get(Calendar.MONTH),
    now.get(Calendar.DAY_OF_MONTH)
);
dpd.setDateRangeLimiter(new DateRangeLimiter() {
     int getMinYear() {
         // Your implementation here
     };

    int getMaxYear(){
        // Your implementation here
    };

    @NonNull Calendar getStartDate() {/*Your implementation here*/};

    @NonNull Calendar getEndDate() {/*Your implementation here*/};

    boolean isOutOfRange(int year, int month, int day) {
        // Check if it's a Wednesday here and return false if so (you might want to keep a instance level calendar and recycle that for performance)
    };

    @NonNull Calendar setToNearestDate(@NonNull Calendar day) {
        // Decide what happens if a user does select a Wednesday (eg changing the year). You could for example round down and return the nearest Tuesday
    };
});
```
You can look at the `DefaultDateRangeLimiter` class for inspiration.

It's a semi advanced feature, so I expect people to know enough java to implement an interface.
