### ISSUE TITLE
gradle build failed when using support library 26.0.2

### ISSUE THREAD

**Issue by lukibeni** [wdullaer/MaterialDateTimePicker#405]
When using support library version 26.0.2 and materialdatetimepicker version 3.3.0 I get the following error during gradle build:
```
Error:Execution failed for task ':app:processDevelopmentDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.1) from [com.android.support:design:26.0.1] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:appcompat-v7:26.0.2] AndroidManifest.xml:28:13-35 value=(26.0.2).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.
```

**Comment by wdullaer** [comment]
If you want to use a different version of the support library, you need to tell gradle not to download the one referred by this library
https://github.com/wdullaer/MaterialDateTimePicker#how-do-i-use-a-different-version-of-the-support-library-in-my-app
