### ISSUE TITLE
Library override my font

### ISSUE THREAD

**Issue by forfiter9** [wdullaer/MaterialDateTimePicker#406]
I use this class to set fonts to whole app:

    public static void setDefaultFont(Context context, String staticTypefaceFieldName, String fontAssetName){
        Typeface regular = Typeface.createFromAsset(context.getAssets(),
                fontAssetName);
        replaceFont(staticTypefaceFieldName, regular);
    }

    private static void replaceFont(String staticTypefaceFieldName, Typeface newTypeface) {
        try {
            Field staticField = Typeface.class.getDeclaredField(staticTypefaceFieldName);
            staticField.setAccessible(true);
            staticField.set(null, newTypeface);
        } catch (NoSuchFieldException e ) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
    }

And set it in GlobalApplication like this :
`FontsCreator.setDefaultFont(this,"MONOSPACE","fonts/ptsansregular.ttf");`

It was working but when i download Your library it is overriding. Have you any idea how can I set my  fonts as default?

**Comment by forfiter9** [comment]
I found that 
`        maven {
            url "https://maven.google.com"
        }` is fould

**Comment by wdullaer** [comment]
This library loads roboto-medium for the buttons, but this is handled transparently. It doesn't override anything.

I do not understand your second post.
