### ISSUE TITLE
How to convert the selected date and time from local time zone to UTC time zone? 

### ISSUE THREAD

**Issue by zeeshansardar61** [wdullaer/MaterialDateTimePicker#408]

**Comment by wdullaer** [comment]
The callback returns the individual pieces of the date and time, not a Calendar, so you can easily handle this in your application no?

**Comment by zeeshansardar61** [comment]
I need to send the selected time and date from UTC +5:00 to UTC 0:00, how do I achieve this for selected? for time it is a piece of cake, but for date it is not returning time with it that i can identify rather I have to change the selected date to (date-1) or (date+1)

**Comment by wdullaer** [comment]
I don't see how you expect this picker to do that.
I mean, the datepicker just selects a date, it by design does not give you any time information.
If you need these to be UTC, then you make these UTC. It's your UI that should make this clear.
