### ISSUE TITLE
Option to "reverse" hours

### ISSUE THREAD

**Issue by mgohin** [wdullaer/MaterialDateTimePicker#411]
Hi,

in Android N/O the timepicker places hours <= 12 outside the circle and hours > 12 inside the circle.
The MaterialDateTimePicker does the opposite.
Did I miss an option ? If not, is it possible to get this option ?

Thanks ;)

Android O :
<img src="https://user-images.githubusercontent.com/3430304/31338866-35646f6e-ad01-11e7-8bfa-1a0794463089.jpg" width="200px" />

MaterialDateTimePicker
<img src="https://user-images.githubusercontent.com/3430304/31338861-3045b42a-ad01-11e7-9462-7fb93c14a8a1.jpg" width="200px" />

**Comment by wdullaer** [comment]
This is not supported at the moment. I'll see if this can be added to the version 2 layout at some point
