### ISSUE TITLE
Can i change locale of the calendar?

### ISSUE THREAD

**Issue by sairajkishore** [wdullaer/MaterialDateTimePicker#419]
I want to change locale to US irrespective of locale change ? is it possible?

**Comment by wdullaer** [comment]
Not at the moment.
There's an open PR for it, but it's trickier than I would like.

**Comment by DaRolla** [comment]
Well, I found a workaround which works for me. Maybe you need to restore your old locale in the demiss listener.

I only set the locale before calling show().

Setting the locale is kind of compicated, but this code helped me:

    public Context setLocale(Context context, String language) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            return updateResources(context, language);
        }

        return updateResourcesLegacy(context, language);
    }

    @TargetApi(Build.VERSION_CODES.N)
    private Context updateResources(Context context, String language) {
        Locale locale = new Locale(language);
        Locale.setDefault(locale);

        Configuration configuration = context.getResources().getConfiguration();
        configuration.setLocale(locale);
        configuration.setLayoutDirection(locale);

        return context.createConfigurationContext(configuration);
    }

    @SuppressWarnings("deprecation")
    private Context updateResourcesLegacy(Context context, String language) {
        Locale locale = new Locale(language);
        Locale.setDefault(locale);

        Resources resources = context.getResources();

        Configuration configuration = resources.getConfiguration();
        configuration.locale = locale;
        configuration.setLayoutDirection(locale);

        resources.updateConfiguration(configuration, resources.getDisplayMetrics());

        return context;
    }
