### ISSUE TITLE
How can i use it in android.support.v4.app.Fragment?

### ISSUE THREAD

**Issue by kukiss** [wdullaer/MaterialDateTimePicker#42]
i had problem that i can't use it in android.support.v4.app.Fragment,
my code is :
Calendar now = Calendar.getInstance();
				DatePickerDialog dpd = DatePickerDialog.newInstance(
						new DatePickerDialog.OnDateSetListener() {
							@Override
							public void onDateSet(DatePickerDialog datePickerDialog, int i, int i1, int i2) {

							}
						},
						now.get(Calendar.YEAR),
						now.get(Calendar.MONTH),
						now.get(Calendar.DAY_OF_MONTH)
				);
				dpd.show(getFragmentManager(), "dialog");

that dpd.show(...) method raise a problem.

**Comment by wdullaer** [comment]
This looks just fine.
Can you show me the stacktrace of the exception?

**Comment by kukiss** [comment]
i think i found the answer , the method getFragmentManager() in v4.app.Fragment returns v4.app.FragmentManager, but the MaterialDateTimePicker view extends app.DialogFragment.
 i replaced it with "dpd.show(getActivity().getFragmentManager(), "dialog");" and it works ^.^
but i think it'll be better if there is a view that extends v4.app.DialaogFragment.
cause i have to use support-v4 to adapter android2.3

**Comment by wdullaer** [comment]
I'm glad you sorted it out. :-)

I don't intend to convert these to support fragments. That would break the API for all users and would require everyone to use support Fragments. Android versions prior 4.0 make up a marginal part of the market and I don't intend to support them with this library.
You can take a look at #8 for more information.

**Comment by elhamzaouiaymen** [comment]
@kukiss u made it man , thanks

**Comment by demonsantosh** [comment]
its still not working  after updating compile version to 26 in android studio 3.1 what could be solution ..
I followed this answer still not working 

https://stackoverflow.com/questions/27225815/android-how-to-show-datepicker-in-fragment

**Comment by metrel** [comment]
Fragments are [deprecated as of API 28](https://developer.android.com/reference/android/app/Fragment).  Support Fragments are not. Do you plan on changing the Fragment type in the near future?

**Comment by wdullaer** [comment]
See #451
