### ISSUE TITLE
Custom implementation of DateRangeLimiter

### ISSUE THREAD

**Issue by gssinghgautam** [wdullaer/MaterialDateTimePicker#427]
I am getting this error

Error:(114, 12) error: cannot find symbol method setDateRangeLimiter(new DateLimiter())'
Error:(115, 40) error: cannot find symbol variable Version

and this is my DateLimiter class;

 private class DateLimiter implements DateRangeLimiter {

        DateLimiter() {
        }

        DateLimiter(Parcel in) {
        }

        @Override
        public int getMinYear() {
            return startCalendar.get(Calendar.YEAR);
        }

        @Override
        public int getMaxYear() {
            return endCalendar.get(Calendar.YEAR);
        }

        @NonNull
        @Override
        public Calendar getStartDate() {
            return startCalendar;
        }

        @NonNull
        @Override
        public Calendar getEndDate() {
            return endCalendar;
        }

        @Override
        public boolean isOutOfRange(int year, int month, int day) {
            return false;
        }

        @NonNull
        @Override
        public Calendar setToNearestDate(@NonNull Calendar day) {
            return day;
        }

        @Override
        public int describeContents() {
            return 0;
        }

        @Override
        public void writeToParcel(Parcel parcel, int i) {

        }

        public final Creator<DateLimiter> CREATOR = new Creator<DateLimiter>() {
            @Override
            public DateLimiter createFromParcel(Parcel source) {
                return new DateLimiter(source);
            }

            @Override
            public DateLimiter[] newArray(int size) {
                return new DateLimiter[size];
            }
        };
    }

**Comment by wdullaer** [comment]
Sounds like a problem with your imports or maven dependency resolution.
Have you tried a clean build?
If that does not resolve it, can you post a full stacktrace?

**Comment by gssinghgautam** [comment]
Sorry I was using older version
