### ISSUE TITLE
compile version 3.4.0

### ISSUE THREAD

**Issue by faelchristofano** [wdullaer/MaterialDateTimePicker#428]
I could not sync compile 'com.wdullaer:materialdatetimepicker:3.4.0', only the version 1.4.1. I saw about this in outher article. When I try to complie the version 3.4.0 show the error:

> Error:Failed to resolve: com.android.support:support-v4:27.0.0
> <a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:C:/Users/rafael/Desktop/MEGA/arquivos/MESTRADO/DESIGN INTERFACES/projetos/MultiWayApp/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
> Error:Failed to resolve: com.android.support:design:27.0.0
> <a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:C:/Users/rafael/Desktop/MEGA/arquivos/MESTRADO/DESIGN INTERFACES/projetos/MultiWayApp/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
> Error:Failed to resolve: com.android.support:support-v13:27.0.0
> <a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:C:/Users/rafael/Desktop/MEGA/arquivos/MESTRADO/DESIGN INTERFACES/projetos/MultiWayApp/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Also, I can´t to create a new instance using the constat DatePickerDialog.newInstance. Show that cannot resolve the symbol

**Comment by wdullaer** [comment]
You need to add the google maven repository to your `build.gradle` so that it can fetch the support library.

https://developer.android.com/topic/libraries/support-library/setup.html#add-library

**Comment by faelchristofano** [comment]
I followed your orientation e the issue persists
![Uploading suport.png…]()
![Uploading erro.png…]()

**Comment by wdullaer** [comment]
I can't really help you any further without additional information.
The error messages you've posted literally tell you what's wrong and how to fix it.
