### ISSUE TITLE
Problem with set max date

### ISSUE THREAD

**Issue by gorevev** [wdullaer/MaterialDateTimePicker#43]
My code:
DatePickerDialog dialog = new DatePickerDialog();
dialog.setMaxDate(Calendar.getInstance());
dialog.setOnDateSetListener(new DatePickerDialog.OnDateSetListener() {
                    @Override
                    public void onDateSet(...) {
                        ...
                    }
                });
dialog.setCancelable(true);
dialog.show(getFragmentManager(), "BirthdayDatePicker");

And i can see disabled dates after current date and i can't set day bigger then current day, but i can set year bigger then current and click ok.

**Comment by wdullaer** [comment]
1. Make sure you have the latest version (it contains some fixes for this)
2. Use `setYearRange` to restrict the selection of the year to maximum the current year.

**Comment by gorevev** [comment]
Yes, i have latest version and i use setYearRange, but i think method setMaxDate work not correct :)


Среда, 10 июня 2015, 1:53 -07:00 от wdullaer <notifications@github.com>:

**Comment by wdullaer** [comment]
I'm aware of it, it's a bug that present in the original code from google's.

it's not easy to fix and the workaround I posted before prevents people from selecting a year outside your acceptable date range, effectively fixing the problem.

Thanks for pointing it out though :-)

**Comment by narendrakothamire** [comment]
serMaxDate does not work
