### ISSUE TITLE
Broken TimePickerDialog UI

### ISSUE THREAD

**Issue by tmelko** [wdullaer/MaterialDateTimePicker#436]
![screenshot_20171213-185426](https://user-images.githubusercontent.com/26436202/33951336-5f56ea72-e037-11e7-92d6-05cae23c792e.png)

**Comment by wdullaer** [comment]
This renders just fine on both API 26 and 27 in the emulator.
It looks like the device you tested this on has a heavily modified system theme, I can't really take all those possibilities into account.

**Comment by tmelko** [comment]
@wdullaer  already fixed within last commits (dat for background I think so).
Just need to deploy.

**Comment by wdullaer** [comment]
I released those changes over the weekend

Op di 19 dec. 2017 09:53 schreef Taras Melko <notifications@github.com>:
