### ISSUE TITLE
How to make it a year and month picker only ?

### ISSUE THREAD

**Issue by j2emanue** [wdullaer/MaterialDateTimePicker#437]
Im searching through the methods but how can i make it a year and month picker and do not offer a day picker.  For example a credit card would only have month and year.

**Comment by dgadelha** [comment]
I was just browsing the web looking for this, and as I already use this library, came to see if it supports this feature. Would be a nice addition.

**Comment by wdullaer** [comment]
This has been answered a lot times in the past.
The design of the picker does not make sense for this usecase, so it won't be added.
I'll add a section to the FAQ
