### ISSUE TITLE
Issue in the multilanguage

### ISSUE THREAD

**Issue by QumberAbbas** [wdullaer/MaterialDateTimePicker#441]
Hi I am facing issue in the arabic language. All the contents are fine except the header. Header work fine when we kill the app and restart it again. This issue is for both ar and en lang.

![pcikerissue](https://user-images.githubusercontent.com/9990138/34407611-142d6c0a-ebe1-11e7-8d12-667050b0b23e.png)

**Comment by wdullaer** [comment]
Can you give me a bit more information on what doesn't work with the title?

You also want to check out the latest version on master (I hope to release that code to maven central later today), it contains some localisation fixes specifically for arabic.
