### ISSUE TITLE
Create new Calendar instance instead of using the one passed as argument

### ISSUE THREAD

**Issue by perqin** [wdullaer/MaterialDateTimePicker#443]
The `newInstance(OnDateSetListener callback, Calendar initialSelection)` method uses the passed `initialSelection` instance directly without cloning one, and it modify that instance in `initialize(OnDateSetListener callBack, Calendar initialSelection)`, which leads to some ridiculous bugs (well, actually I use the same `Calendar` instance for displaying both date and time, and the time is reset to midnight after the date is changed). I think it's better to clone a new `Calendar` instance, as the library cannot expect the one passed in is safe to be modified.

**Comment by wdullaer** [comment]
Good catch.
I am already doing this in most other places, but seem to have forgotten in the most important one
