### ISSUE TITLE
Compatibility issue with the use of android.app.Fragment

### ISSUE THREAD

**Issue by Ashutosh-Tiwari** [wdullaer/MaterialDateTimePicker#445]
I am using the library in one of my apps. My whole app was earlier using `android.app.Fragment` type fragments. But now I am entertaining all the fragments from support library using `android.support.v4.app.Fragment`.

But the `DialogFragment` used in your library is using simple `android.app.Fragment` type fragment. Resulting into an error and I am not able to use the library anymore. Please update the library asap.
Help me on this asap @wdullaer 

Screenshot link: http://prntscr.com/i4dwxe

**Comment by wdullaer** [comment]
You can still use the regular FragmentManager to render this Dialog
https://github.com/wdullaer/MaterialDateTimePicker#why-not-use-supportdialogfragment
