### ISSUE TITLE
Whether we can save OnDateSetListener

### ISSUE THREAD

**Issue by LonelyMushroom** [wdullaer/MaterialDateTimePicker#448]
Premise: do not keep the application.
In use, A click on the button with out ` DatePickerDialog `, click ` home `, click `confirm ` doesn't work again
The reason: `mCallBack == null`

I find the most used ` DialogFragment ` lot, found that everyone is all about, I want to know whether we can save ` Listener ` , Or not working is the right design.

**Comment by wdullaer** [comment]
This behavior is detailed in the FAQ:
https://github.com/wdullaer/MaterialDateTimePicker#why-are-my-callbacks-lost-when-the-device-changes-orientation
