### ISSUE TITLE
Layout Not Proper

### ISSUE THREAD

**Issue by sunit09** [wdullaer/MaterialDateTimePicker#449]
Distortion in design observed when caller activity having a theme with parent="Theme.AppCompat.Light.Dialog".

Working fine with non dialog activity.
![screenshot_1517306602](https://user-images.githubusercontent.com/16812932/35560219-c1de4724-05d2-11e8-831a-8856a5c3bde1.png)

**Comment by wdullaer** [comment]
Are you using the latest version?

**Comment by sunit09** [comment]
Yes, its 3.5.0

**Comment by wdullaer** [comment]
Judging by the background theme, it also looks like you've been overriding some padding / margins in system themes.
I am only testing this against the default themes. If you change system themes or force the picker to use a specific theme, there's not much I can do if it looks weird.
