### ISSUE TITLE
Android P will deprecate native Fragments

### ISSUE THREAD

**Issue by joshfriend** [wdullaer/MaterialDateTimePicker#451]
It was revealed yesterday in the new android-ktx library from Google that Android P will deprecate native fragments:

> The next version of Android will deprecate the version of fragments that are part of the platform.

https://github.com/android/android-ktx/pull/161#issuecomment-363270555

In light of this, I think the decision here to use only native Fragments should be reconsidered.

**Comment by wdullaer** [comment]
When it's officially deprecated, I'll do a semver major and change this.

**Comment by dimeilof** [comment]
Since the Android P preview announcement, framework Fragments and Loaders have been officially deprecated.

[Framework Fragments and Loaders have been officially deprecated in Android P.](https://www.reddit.com/r/androiddev/comments/82rb0k/framework_fragments_and_loaders_have_been/)

**Comment by Jawnnypoo** [comment]
I would say it is worthwhile to do this now, so that others have time to migrate over to 4.0.0 of this lib before Android P is actually in public hands. Would you like me to make a PR @wdullaer ? I probably will have some time this week.

**Comment by wdullaer** [comment]
I have already done most of the changes.
I am waiting for a few things at this point:
* Google to release actual API 28 SDKs, so I can use a linter to find any potential other depreciations (I have to read through the API diff right now)
* I want to still add the arrows in the datepicker for the 3.x.x series
* I might potentially remove the version 1 layout for v4, I haven't decided yet. (It would grealy simplify the codebase)

Essentially I want to make the most of the semver major update

**Comment by joshfriend** [comment]
> I am waiting for a few things at this point: Google to release actual API 28 SDKs

Fantastic plan, thats really all I was suggesting :+1: Android P APIs wont be final and you wont be able to submit apps compiled against it to the store until DP3 in June anyways.

@Jawnnypoo if you (or anyone else) need to test with support fragments before P is final, there's already a really good fork [here (also mentioned in the README)](https://github.com/infinum/MaterialDateTimePicker).

**Comment by DagobertDokate** [comment]
Some news? Need it^^

**Comment by DagobertDokate** [comment]
I have already looked at these. Unfortunately, this version does not support 27.1.1.
Now i use this with mixed v4 and nativ Fragments. Hope i can change it befor release =)

**Comment by yanniks** [comment]
Another problem is that Google moves all Support Libraries to the new [Android extension library (AndroidX) packages](https://android-developers.googleblog.com/2018/05/hello-world-androidx.html).
So before moving everything to `com.android.support`, please consider solutions that don't break AndroidX support. With release of `beta01`, the [public API is considered stable](https://developer.android.com/topic/libraries/support-library/androidx-rn).

**Comment by wdullaer** [comment]
I am aware and tracking that.
It is not something that should cause issues. It does not modify the api in any way, so it can be done at any point in time.

Hopefully I can do this together with a v4 release, but if that doesn't work out, it'll happen later, but will be transparent for most / all users of the library

**Comment by eugeneroz** [comment]
Do you have any progress?

**Comment by wdullaer** [comment]
Fixed in v4.0.0
