### ISSUE TITLE
good, when I try to add this library in my app.gradle I get the following error

### ISSUE THREAD

**Issue by orlando9006** [wdullaer/MaterialDateTimePicker#453]
Error:(41, 13) Failed to resolve: com.wdullaer:materialdatetimepicker:3.5.1
apply plugin: 'com.android.application'
this is my gradle.
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.trabajo.plataformaintegral"
        minSdkVersion 17
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://dl.bintray.com/drummer-aidan/maven" }
        maven { url 'https://jitpack.io' }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'it.neokree:MaterialTabs:0.11'
    compile 'com.github.vatsaldesai92:MyDynamicCalendarLibrary:1.0.1'
    compile 'com.github.satyan:sugar:1.5'
    compile 'com.afollestad.material-dialogs:core:0.9.4.0'
    compile 'com.gordonwong:material-sheet-fab:1.2.1'
    compile 'com.afollestad.material-dialogs:commons:0.9.4.5'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.wrapp.floatlabelededittext:library:0.0.6'
    compile 'com.wdullaer:materialdatetimepicker:3.5.1'
}

**Comment by wdullaer** [comment]
The artifact is properly available on maven central.
https://search.maven.org/#search%7Cga%7C1%7Cmaterialdatetimepicker
There's not much more I can do here.
