### ISSUE TITLE
Disable set of dates

### ISSUE THREAD

**Issue by burugular** [wdullaer/MaterialDateTimePicker#454]
I am using materialdatetimepicker to customise my calendar. My requirement is I want to disable all dates from today and next 31 days.

What I have tried.

1 - Set the minimum date to Today - datePickerDialog.setMinDate(now);

2 - Maximum date to 31 days from today. - datePickerDialog.setMaxDate(cal);

3 - Disabled the dates in between. datePickerDialog.setDisabledDays(otherCalendars);

When I do step 1 2 and 3 together, the Calendar is not opened at all and app freezes.

When I do the steps (1,2) and 3 seperately I get the correct results. But I only want to display next 31days from now and disable them all.

Here is the code which I have tried.

Where am I getting this wrong? any help is much appreciated.

```
        private DatePickerDialog datePickerDialog;

        DateTime startDateTime = new DateTime();
        DateTime endDateTime = new DateTime();
        endDateTime = endDateTime.plusDays(31);

        List<DateTime> otherDays = new ArrayList<>();
        while (startDateTime.isBefore(endDateTime)) {
            otherDays.add(startDateTime);
            startDateTime = startDateTime.plusDays(1);
        }

        Calendar[] otherCalendars = new Calendar[otherDays.size()];
                for (int count = 0; count < otherDays.size(); count++) {
                    otherCalendars[count] = otherDays.get(count).toGregorianCalendar();
                }

         datePickerDialog.setMinDate(now);
         Calendar cal = Calendar.getInstance();
         Date ddd = endDateTime.toDate();
         cal.setTime(ddd);
         datePickerDialog.setMaxDate(cal);
         datePickerDialog.setDisabledDays(otherCalendars);
```
Thanks R

**Comment by wdullaer** [comment]
You are effectively disabling all dates. When you perform all 3 steps there are no acceptable selections the user can make. The behaviour of the picker is undefined in this case.

What do you expect to happen in this case?

If the purpose is not that the user selects a date, you should probably be using a calendar widget rather than these pickers.
