### ISSUE TITLE
hello I would like to collaborate with your project serving as a translator to Spanish which is my native language

### ISSUE THREAD

**Issue by LuigiBaute** [wdullaer/MaterialDateTimePicker#456]

**Comment by wdullaer** [comment]
Which parts aren't properly translated into Spanish?
I'm open to PRs

**Comment by LuigiBaute** [comment]
I'm talking about the readme.md files I don't see any translated file to spanish if so that's ok, if you're interested in my contribution let me know.

**Comment by wdullaer** [comment]
Like  I said, I'll except decent PRs :-)
