### ISSUE TITLE
Change dialog fonts typeface from XML

### ISSUE THREAD

**Issue by kenumir** [wdullaer/MaterialDateTimePicker#457]
Support library 26+
Fonts in XML: https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml.html

**Comment by wdullaer** [comment]
Thanks for the headsup.
Unfortunately the min API level is 14, and even the support library version of this has min level 16.
This makes it a breaking change.

I'll keep this on the list and evaluate it when I do the next semver major release

**Comment by plastiv** [comment]
I think documentation is misleading. I have checked support fonts in xml the week before and it is working on api 14. Plus Downloadable fonts https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts.html don't have minSdk=16 restriction and practically is calling same `ResourcesCompat.getFont` implementation.

**Comment by wdullaer** [comment]
If google doesn't mark it as compatible with API 14, it is essentially undocumented behaviour that can change at any point in time.
I prefer to be conservative for this library, which is more popular than I ever anticipated.

Given that there are strong indications that google will deprecate framework fragments in android P, a semver major upgrade to this library isn't that far out anyway.
