### ISSUE TITLE
i am using this time/date picker but the problem is that when i try to set value in my edittextview from onDateSet method it thrrows nullpointer exception . please help me because i am stuck witht his from last 3 days . please help me 

### ISSUE THREAD

**Issue by uaziz2014** [wdullaer/MaterialDateTimePicker#458]
it shows following error when i try to set value of editextview in my OnSetDate method

Process: com.example.anonymous.ghar_ka_khana, PID: 21651
                                                                                     java.lang.NullPointerException
                                                                                         at com.example.anonymous.ghar_ka_khana.Selling_item_detail.onDateSet(Selling_item_detail.java:158)
                                                                                         at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.notifyOnDateListener(DatePickerDialog.java:1140)
                                                                                         at com.wdullaer.materialdatetimepicker.date.DatePickerDialog$1.onClick(DatePickerDialog.java:409)
                                                                                         at android.view.View.performClick(View.java:4466)
                                                                                         at android.view.View$PerformClick.run(View.java:18542)
                                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5097)
                                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                         at dalvik.system.NativeStart.main(Native Method)

here is my code of the fragment in which date/time dialogue appears when the button is pressed

package com.example.anonymous.ghar_ka_khana;

import android.content.Context;
import java.util.Calendar;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.app.Fragment;
import android.support.annotation.RequiresApi;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.TimePicker;

import com.wdullaer.materialdatetimepicker.date.DatePickerDialog;
import com.wdullaer.materialdatetimepicker.time.TimePickerDialog;

/**
 * A simple {@link Fragment} subclass.
 * Activities that contain this fragment must implement the
 * {@link Selling_item_detail.OnFragmentInteractionListener} interface
 * to handle interaction events.
 * Use the {@link Selling_item_detail#newInstance} factory method to
 * create an instance of this fragment.
 */
public class Selling_item_detail extends Fragment implements DatePickerDialog.OnDateSetListener,TimePickerDialog.OnTimeSetListener{
    // TODO: Rename parameter arguments, choose names that match
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
    private static final String ARG_PARAM1 = "param1";
    private static final String ARG_PARAM2 = "param2";

    EditText timetext;
    EditText datetext;
    int hours;
    View v;

    // TODO: Rename and change types of parameters
    private String mParam1;
    private String mParam2;

    private OnFragmentInteractionListener mListener;

    public Selling_item_detail() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment Selling_item_detail.
     */
    // TODO: Rename and change types and number of parameters
    public static Selling_item_detail newInstance(String param1, String param2) {
        Selling_item_detail fragment = new Selling_item_detail();
        Bundle args = new Bundle();
        args.putString(ARG_PARAM1, param1);
        args.putString(ARG_PARAM2, param2);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);
        }
    }

    @RequiresApi(api = Build.VERSION_CODES.N)
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        v =inflater.inflate(R.layout.fragment_selling_item_detail, container, false);
        timetext = (EditText)v.findViewById(R.id.time);
        datetext = (EditText)v.findViewById(R.id.date);

        Log.i("timecontext",timetext+"");
        Log.i("datecontext",datetext+"");

        ImageButton calendarbutton =(ImageButton)v.findViewById(R.id.dateButton);
        calendarbutton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Calendar now = Calendar.getInstance();
                DatePickerDialog dpd = DatePickerDialog.newInstance(
                        new Selling_item_detail(),
                        now.get(Calendar.YEAR),
                        now.get(Calendar.MONTH),
                        now.get(Calendar.DAY_OF_MONTH)
                );
                dpd.show(getFragmentManager(), "Datepickerdialog");
            }
        });

        ImageButton timebutton =(ImageButton)v.findViewById(R.id.timeButton);
        timebutton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view)
            {
                Calendar now = Calendar.getInstance();
                TimePickerDialog dpd = TimePickerDialog.newInstance(
                        new Selling_item_detail(),
                        now.get(Calendar.HOUR_OF_DAY),
                        now.get(Calendar.MINUTE),
                        now.isLenient()
                );
                dpd.show(getFragmentManager(), "Datepickerdialog");
            }
        });

        return  v;
    }

    // TODO: Rename method, update argument and hook method into UI event
    public void onButtonPressed(Uri uri) {
        if (mListener != null) {
            mListener.onFragmentInteraction(uri);
        }
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context instanceof OnFragmentInteractionListener) {
            mListener = (OnFragmentInteractionListener) context;
        } else {
            throw new RuntimeException(context.toString()
                    + " must implement OnFragmentInteractionListener");
        }
    }

    @Override
    public void onDetach() {
        super.onDetach();
        mListener = null;
    }

    @Override
    public void onDateSet(DatePickerDialog view, int year, int monthOfYear, int dayOfMonth)
    {

        datetext.setText("umair");
      //  hours=year;

        Log.i("tareekh",dayOfMonth+"-"+monthOfYear+"-"+year);

    }

    @Override
    public void onTimeSet(TimePickerDialog view, int hourOfDay, int minute, int second)
    {
      //  timetext.setText(hourOfDay+":"+second+":"+minute);
        Log.i("waqt",hourOfDay+":"+second+":"+minute);
    }

    /**
     * This interface must be implemented by activities that contain this
     * fragment to allow an interaction in this fragment to be communicated
     * to the activity and potentially other fragments contained in that
     * activity.
     * <p>
     * See the Android Training lesson <a href=
     * "http://developer.android.com/training/basics/fragments/communicating.html"
     * >Communicating with Other Fragments</a> for more information.
     */
    public interface OnFragmentInteractionListener {
        // TODO: Update argument type and name
        void onFragmentInteraction(Uri uri);
    }
}

here is the xml of that fragment

<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginTop="?attr/actionBarSize"
    xmlns:fab="http://schemas.android.com/apk/res-auto">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:padding="24dp">

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="220dp"
            >

            <com.mikepenz.materialdrawer.view.BezelImageView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:src="@drawable/header"
                android:id="@+id/seelingfoodimage"/>

            <com.scalified.fab.ActionButton
                android:id="@+id/cambutton"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="bottom|start"
                fab:button_color="#ffffff"
                fab:button_colorPressed="#FF0000"
                fab:image="@drawable/cam"
                fab:image_size="34dp" />

        </FrameLayout>

        <com.github.florent37.materialtextfield.MaterialTextField
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            app:mtf_openKeyboardOnFocus="true"
            app:mtf_labelColor="#666"
            app:mtf_image="@drawable/food"
            >

            <EditText
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/foodname"
                android:hint="Foodname"
                android:layout_marginTop="10dp"
                android:textColor="#333"
                android:textSize="15sp" />

        </com.github.florent37.materialtextfield.MaterialTextField>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:orientation="horizontal">

            <com.github.florent37.materialtextfield.MaterialTextField
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:mtf_labelColor="#666"
                android:id="@+id/cal"
                app:mtf_image="@drawable/calendar"
                app:mtf_openKeyboardOnFocus="true"
                >

                <EditText
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:id="@+id/date"
                    android:hint="Selling Location"
                    android:textColor="#333"
                    android:textSize="15sp" />

            </com.github.florent37.materialtextfield.MaterialTextField>

            <ImageButton
                android:id="@+id/dateButton"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="40dp"
                android:layout_marginLeft="5dp"
                android:src="@drawable/calendar"/>

        </LinearLayout>

        

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:orientation="horizontal">

            <com.github.florent37.materialtextfield.MaterialTextField
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:mtf_labelColor="#666"
                app:mtf_image="@drawable/time"
                app:mtf_openKeyboardOnFocus="true"
                >

                <EditText
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:id="@+id/time"
                    android:hint="Selling Location"
                    android:textColor="#333"
                    android:textSize="15sp" />

            </com.github.florent37.materialtextfield.MaterialTextField>

            <ImageButton
                android:id="@+id/timeButton"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="40dp"
                android:layout_marginLeft="5dp"
                android:src="@drawable/time"/>

        </LinearLayout>

        

        <com.github.florent37.materialtextfield.MaterialTextField
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:mtf_labelColor="#666"
            android:layout_marginTop="10dp"
            app:mtf_image="@drawable/plate"
            app:mtf_openKeyboardOnFocus="true"
            >

            <EditText
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/plate"
                android:hint="Number Of Plates"
                android:layout_marginTop="10dp"
                android:textColor="#333"
                android:textSize="15sp" />

        </com.github.florent37.materialtextfield.MaterialTextField>

        <com.github.florent37.materialtextfield.MaterialTextField
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:mtf_labelColor="#666"
            android:layout_marginTop="10dp"
            app:mtf_image="@drawable/money"
            app:mtf_openKeyboardOnFocus="true"
            >

            <EditText
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/money"
                android:hint="Price Per Plate"
                android:layout_marginTop="10dp"
                android:textColor="#333"
                android:textSize="15sp" />

        </com.github.florent37.materialtextfield.MaterialTextField>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="10dp"
        android:orientation="horizontal">

        <com.github.florent37.materialtextfield.MaterialTextField
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:mtf_labelColor="#666"
            app:mtf_image="@drawable/location"
            app:mtf_openKeyboardOnFocus="true"
            >

            <EditText
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/location"
                android:hint="Selling Location"
                android:textColor="#333"
                android:textSize="15sp" />

        </com.github.florent37.materialtextfield.MaterialTextField>

        <EditText
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:id="@+id/umair"/>

        <ImageButton
            android:id="@+id/mapButton"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="40dp"
            android:layout_marginLeft="5dp"
            android:src="@drawable/map"/>

    </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:layout_marginTop="20dp">

            <Button
                android:layout_width="0dp"
                android:layout_weight="1"
                android:layout_height="wrap_content"
                android:text="OK"
                android:textColor="#ffffff"
                android:id="@+id/ok"
                android:background="@drawable/rounded_button_selector" />
            <LinearLayout
                android:layout_width="0dp"
                android:layout_weight="1"
                android:layout_height="wrap_content">

            </LinearLayout>

            <Button
                android:layout_width="0dp"
                android:layout_weight="1"
                android:layout_height="wrap_content"
                android:text="Cancel"
                android:textColor="#ffffff"
                android:id="@+id/cancel"
                android:background="@drawable/rounded_button_selector" />

        </LinearLayout>

    </LinearLayout>
</ScrollView>

    

while my gradle is like this
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.example.anonymous.ghar_ka_khana"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.google.firebase:firebase-database:11.8.0'
    //11.0.4
    implementation 'com.android.support:support-v4:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation 'com.google.android.gms:play-services:11.8.0'
    implementation 'com.firebaseui:firebase-ui-auth:3.1.3'
    // FirebaseUI for Firebase Auth
    implementation 'com.firebaseui:firebase-ui-database:3.1.3'
    // FirebaseUI for Firebase Realtime Database
    implementation 'com.firebaseui:firebase-ui-firestore:3.1.3'
    // FirebaseUI for Cloud Firestore
    compile 'com.google.firebase:firebase-firestore:11.8.0'
    //Firestore dependency
    implementation 'com.firebaseui:firebase-ui-storage:3.1.3'
    // FirebaseUI for Cloud Storage
    implementation 'com.facebook.android:facebook-login:4.29.0'
    // Required only if Facebook login support is required
    // Find the latest Facebook SDK releases here: https://goo.gl/Ce5L94
    implementation('com.twitter.sdk.android:twitter-core:3.1.1') { transitive = true }
    // Find the latest Twitter SDK releases here: https://goo.gl/E5wZvQ
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    implementation 'com.github.florent37:materialtextfield:1.0.7'
    compile 'com.scalified:fab:1.1.3'
    compile 'com.google.firebase:firebase-storage:11.8.0'
    compile 'com.google.firebase:firebase-auth:11.8.0'
    compile 'com.github.glomadrian:Grav:1.1'
    implementation('com.mikepenz:materialdrawer:6.0.6@aar') {
        transitive = true
    }
    compile 'com.wdullaer:materialdatetimepicker:3.5.1'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support:recyclerview-v7:26.1.0'
    implementation 'com.android.support:support-annotations:26.1.0'
}
apply plugin: 'com.google.gms.google-services'
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '26.1.0'
            }
        }
    }
}

**Comment by wdullaer** [comment]
This is not a bug with this library. I just don't have the time to debug everybody's code just because they happened to use this library.
I suggest attaching a debugger and looking at the state of your class when onDateSet gets triggered.

**Comment by uaziz2014** [comment]
ok then let me debug it now and then i will tell you about status
