### ISSUE TITLE
Problem with setMax and setMin on rotation

### ISSUE THREAD

**Issue by jssingh** [wdullaer/MaterialDateTimePicker#46]
If you provide a setMax on the date, it works nicely that is it doesn't allow for selecting the greyed out dates. 

Except, if you rotate the screen. The greyed out dates become clickable again.

Its a minor issue I would say and let me see if I can issue a pull request for you.

**Comment by jssingh** [comment]
Thanks for attempt to fix this issue, unfortunately it hasn't been fixed. As an example, if the current date is what is set as max (so future dates can't be selected), open the calendar and rotate the screen. All dates are now clickable, including the ones in the future. Using 1.4.1.

**Comment by wdullaer** [comment]
I just tried out a few different cases here and it works just fine on all my test devices.

Are you certain you did a full rebuild and pulled in the latest version?
