### ISSUE TITLE
Disable backward dates form start date

### ISSUE THREAD

**Issue by hamsoft-uganda** [wdullaer/MaterialDateTimePicker#462]
I want to disable all the back dates from the start date when the user is choosing the end date. The end date should not be greater than the start date. How can I do this?

Check on this gif
![disable_back_dates](https://user-images.githubusercontent.com/11741247/37338040-243e4620-26ae-11e8-9645-ba8c5b60006f.gif)
 bellow

**Comment by wdullaer** [comment]
From the screenshot, it seems like you are using this library: https://github.com/borax12/MaterialDateRangePicker

**Comment by hamsoft-uganda** [comment]
Thanks so much,, I didn't double check to which page to post.

**Comment by wdullaer** [comment]
No worries, you're not the first, and I doubt you'll be the last :-)
