### ISSUE TITLE
Cannot use together MaterialDateTimePicker and Borax DateRangePicker

### ISSUE THREAD

**Issue by federicoteddy** [wdullaer/MaterialDateTimePicker#470]
error : No static field mdtp_date_picker_month of type I in class Lcom/wdullaer/materialdatetimepicker/R$id; or its superclasses (declaration of 'com.wdullaer.materialdatetimepicker.R$id

how to use together datetimepicker and daterangepicker?

**Comment by wdullaer** [comment]
The borax daterangepicker is a fork of this library. There's little I can do with the incompatibilities that causes.
Are you sure you're using the latest version of both libraries?

**Comment by federicoteddy** [comment]
using borax daterangepicker 
compile 'com.borax12.materialdaterangepicker:library:1.9'

using datetimepicker
compile 'com.wdullaer:materialdatetimepicker:3.5.1'

it is last version?

**Comment by wdullaer** [comment]
There isn't much I can do here
Other than using the latest versions, doing a clean build, I don't really have any other advice

**Comment by wdullaer** [comment]
I created this PR https://github.com/borax12/MaterialDateRangePicker/pull/99 on MaterialDateRangePicker which resolves the incompatibility.

If the owner does not merge it, I will probably publish a wdullaer:MaterialDateRangePicker that can be used instead.
