### ISSUE TITLE
Deprecation of native fragments in Android P

### ISSUE THREAD

**Issue by tsherdiwala** [wdullaer/MaterialDateTimePicker#471]
With the release of the developer version of Android P, they have updated the [Fragment](https://developer.android.com/reference/android/app/Fragment.html) documentation to include the following note:

> This class was deprecated in API level P.
Use the Support Library Fragment for consistent behavior across all devices and access to Lifecycle.

Should we consider moving to the support fragment?

**Comment by wdullaer** [comment]
This is being tracked in #451
