### ISSUE TITLE
Error when building apk using this library

### ISSUE THREAD

**Issue by asknask** [wdullaer/MaterialDateTimePicker#473]
I get this error

`Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v13/view/inputmethod/InputConnectionCompat$1;`

I believe I have to exclude a particular component of this library. How do I find the one that needs to be excluded?

**Comment by asknask** [comment]
exclude group: 'com.android.support', module: 'support-v13'

This is what's needed.

**Comment by wdullaer** [comment]
This is already mentioned in the FAQ
https://github.com/wdullaer/MaterialDateTimePicker#how-do-i-use-a-different-version-of-the-support-library-in-my-app
