### ISSUE TITLE
.newInstance is not working for me.

### ISSUE THREAD

**Issue by coderabsolute** [wdullaer/MaterialDateTimePicker#475]
Not sure whether newInstance is depreciated? Am trying to use this component on the fragment and not activity. Here is my code, the name of the fragment is NewMessageFragment. Can someone please help me. Thanks in advance!

Calendar now = Calendar.getInstance();
DatePickerDialog dpd = DatePickerDialog.newInstance(
		new NewMessageFragment(),
		now.get(Calendar.YEAR),
		now.get(Calendar.MONTH),
		now.get(Calendar.DAY_OF_MONTH)
);
dpd.show();
My Gradle Setting is implementation 'com.wdullaer:materialdatetimepicker:3.5.1'

**Comment by wdullaer** [comment]
The first argument of newInstance is a reference to an object that implements `OnDateSetListener`

I suggest you take a look at how the sample app works.
