### ISSUE TITLE
setSelectableDays not working on pre lolipop

### ISSUE THREAD

**Issue by Krohajah** [wdullaer/MaterialDateTimePicker#476]
Hi!
I use the library to limit the number of days displayed. I pass the list of dates and install them using the secelostableDays method. On devices with postLolipop OS everything is displayed correctly, but on preLolipop this method does not seems to work

snippet for creating available days:

```
List<String> dayReport = dayReportList.getDays();
        Calendar[] calendars = new Calendar[dayReport.size()];
        ArrayList<Calendar> calrsList = new ArrayList<>();
        try {
            for (int i = 0; i < dayReport.size(); i++) {
                Calendar calendar = DateUtils.newCalendar();
                calendar.setTime(simpleDateFormatThreadLocal.get().parse(dayReport.get(i)));
                calrsList.add(calendar);
            }
            calrsList.toArray(calendars);
        } catch (ParseException e) {
            e.printStackTrace();
        }
```
snipet to setSelectableDays:

```
 DatePickerDialog existingFragment = (DatePickerDialog) activity.getFragmentManager().findFragmentByTag(F_TAG_DATE_PICKER);
        if (existingFragment == null) {
            this.datePickerDialog = DatePickerDialog.newInstance(
                    (view, year1, monthOfYear1, dayOfMonth1) -> onDateSetListener.onDateSet(year1, monthOfYear1, dayOfMonth1),
                    year,
                    monthOfYear,
                    dayOfMonth
            );

            datePickerDialog.setSelectableDays(selectableDays);
```
preLolipop Image
![image](https://user-images.githubusercontent.com/22335458/38611404-4162d956-3d8c-11e8-896e-cee327b3890e.png)
post lolipop
![image](https://user-images.githubusercontent.com/22335458/38613751-8f9b1ab4-3d93-11e8-82af-d05497e974cf.png)

Any advise would be apprisiated! Tnx

**Comment by wdullaer** [comment]
There is no API specific logic in the DateLimiter.
However looking at your code, it seems that you are parsing the dates from Strings using SimpleDateFormat. There were quite some changes in that class in Lollipop.
Use a debugger to check the actual content of the input to setSelectableDays, I'm pretty sure the parser is not returning the results you expect.

**Comment by Krohajah** [comment]
Seems like there are some changes in TimeZone on post lollipop OS. Taking instance without TimeZone fix the problem.

**Comment by wdullaer** [comment]
I'm glad you figured it out ☺️
