### ISSUE TITLE
Minutes Interval Support ?

### ISSUE THREAD

**Issue by mobilegeekkk** [wdullaer/MaterialDateTimePicker#477]
Does MaterialDateTimePicker supports minutes interval in time picker ?

**Comment by wdullaer** [comment]
I'm not sure I understand your question.
By default the resolution is a single minute of the selection.

**Comment by mobilegeekkk** [comment]
@wdullaer I need 15,30,45 minutes interval in my application. Does this lib supports minutes interval ?

**Comment by wdullaer** [comment]
`setTimeInterval`
https://github.com/wdullaer/MaterialDateTimePicker#additional-options

**Comment by mobilegeekkk** [comment]
@wdullaer  Thanks man, I'll follow your guidelines.
