### ISSUE TITLE
set highlighted days for CalendarView

### ISSUE THREAD

**Issue by yaseen-homage** [wdullaer/MaterialDateTimePicker#480]
Is there any way I can set highlighted days for CalendarView?

Is there a way to deselect a particular date on CalendarView and clear all the selected dates? (documenting this will be helpful)
I'm  also requesting a feature to change the background color for highlighted Items for calendarView.

**Comment by wdullaer** [comment]
Please read the documentation: There is a method literally called `setHighlightedDays()`
https://github.com/wdullaer/MaterialDateTimePicker#additional-options

You can't select multiple days, so clearing and unselecting do not make any sense.

And I do not intend to offer more customization options for the highlighted days. If you have advanced features it should be easy enough to customize the `SimpleMonthView` class yourself with the behaviour you want.
