### ISSUE TITLE
Is there any option to hide ok and cancel button?

### ISSUE THREAD

**Issue by yusufaw** [wdullaer/MaterialDateTimePicker#481]
I have already using autoDismiss on the date picker, but the ok and cancel button are still visible. How to hide them?
Thank you.

**Comment by wdullaer** [comment]
If you hide the OK button there is no way for the callback to get triggered and the user selection to passed on to your application.

If you use the pickers as Fragments, the dialog buttons will not be shown, but this well require subclassing to ensure that the selection is accessible to your application logic.

**Comment by yusufaw** [comment]
Thank you.
I've just forked this and added some my own code to hide ok cancel button when auto dismiss is true.
`view.findViewById(R.id.mdtp_done_background).setVisibility(mAutoDismiss ? View.GONE : View.VISIBLE);`
https://github.com/skyshi-labs/MaterialDateTimePicker/commit/016a6825fc9466ef327c7c600d49200df007942f
