### ISSUE TITLE
how to use custom font?

### ISSUE THREAD

**Issue by Mithun1990** [wdullaer/MaterialDateTimePicker#482]
How can i use custom font instead of library default Roboto font, for all text?

**Comment by wdullaer** [comment]
The library will use whatever fonts are set as default.
On older API versions it will load roboto medium for buttons. The font which is loaded is configured through a resource which you could overwrite in your app.

I do not intend to make any changes to this.

**Comment by magnusfernandes** [comment]
@wdullaer it would be great if you add a method to change the typeface.

datePickerDialog.setTypeface(customTypeface)

**Comment by wdullaer** [comment]
I still don't intend to enable this.
There are way too many ways this can mess up the layout.

You can always fork it and make the modifications yourself.
