### ISSUE TITLE
TimePickerDialog - landscape - missing buttons "OK", "Cancel"

### ISSUE THREAD

**Issue by MaciekZ-NHM** [wdullaer/MaterialDateTimePicker#484]
Hello, I have problem with TimePicker Dialog. On portrait mode I see time picker component and two buttons "OK" and "Cancel", but when I rotate screen to landscape mode, bottom buttons disappear. 

Tested device: Samsung Galaxy S6 (SM-G920F) - Android 7.0

Additional info:
I have also tested on Samsung Galaxy Tab A (2016) (SM-T585) and bottom buttons are visible on portrait and landscape mode

**Comment by wdullaer** [comment]
Are you sure you're using the latest version.
I fixed #461 in the latest release

**Comment by MaciekZ-NHM** [comment]
I used version 3.5.1
in 3.5.2 buttons are now correctly displayed
the Setup section introduced me in error, there is 3.5.1

thanks for quick reply

by the way: good job :)

**Comment by wdullaer** [comment]
There are a few issues in 3.5.2 as well.
I should have 3.6.0 out by the end of the month with fixes and some other goodies.

I'm happy you find this useful :-)
