### ISSUE TITLE
Month Not matching

### ISSUE THREAD

**Issue by TheFinestArtist** [wdullaer/MaterialDateTimePicker#49]
After new release the month showing upper part of Date Picker and lower part of Date Picker is miss-maching. Actually, the calendar view shows wrong month!

I think there is mistake like sending decremented month value which already been decremented before.

**Comment by wdullaer** [comment]
This sounds very similar to #44 
A build clean seems to have fixed it for that person.

I cannot reproduce this issue myself. If you can provide me with a code snippet that reliably reproduces the issue, please reopen this issue.
