### ISSUE TITLE
Pre-set the time on TimePicker

### ISSUE THREAD

**Issue by Nir158** [wdullaer/MaterialDateTimePicker#491]
I am working with Time Picker. I have used it to create events. User can pick time of the event via this Time Picker and it perfectly fine. But issue is with edit functionality. When my user goes to Edit the event and reclick the time field, I am having issues with presetting the time in picker. I am using following code. I have time in format of **hh:mm aa** (For ex : 05:45 PM)

```
String[] time = edtTimeimeEvent.getText().toString().split(":");

        int hourTime = Integer.parseInt(time[0]);
        int minuteTime = Integer.parseInt(time[1].split(" ")[0]);

        TimePickerDialog timePickerDialog = TimePickerDialog.newInstance(
                new TimePickerDialog.OnTimeSetListener() {
                    @Override
                    public void onTimeSet(RadialPickerLayout view, int hourOfDay, int minute, int second) {
                        // performing my task
                    }
                },
                hourTime,
                minuteTime,
                false);
```

Now the issue here is that I dont know how to pre-set AM/PM when opening the picker. Every time I open picker, AM is selected by default.
Can you help me out please?

**Comment by wdullaer** [comment]
You are making this way too hard on yourself.
The initial selection is passed in as an argument to the `newInstance()` method.
So you when the user clicks the edit button, you parse the time and create a new instance.

If you wish to reuse the picker instance you can call the `initialize` method on it.

Take a look at the included sample app: https://github.com/wdullaer/MaterialDateTimePicker/blob/master/sample/src/main/java/com/wdullaer/datetimepickerexample/TimePickerFragment.java
