### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by ShengjieGeng** [wdullaer/MaterialDateTimePicker#492]
give me a hand please!
it occured a ANR in Android 5.0
![error](https://user-images.githubusercontent.com/18364968/40834885-9e15b0aa-65c4-11e8-9d64-69c22e1c9db7.png)

**Comment by ShengjieGeng** [comment]
I got the log
![anr1](https://user-images.githubusercontent.com/18364968/40895008-a4ad6ff8-67df-11e8-8a43-63e2865f6364.png)

**Comment by wdullaer** [comment]
I'm sorry, but this does not look related to this library at all.

**Comment by ShengjieGeng** [comment]
thanks all the same.
Actually,it was my faults that I added the `<item name="android:fontFamily">sans-serif</item>` in my AppTheme. it could run normally after I deleted the item.

**Comment by wdullaer** [comment]
Glad you figured it out
