### ISSUE TITLE
It is not showing PM in 12 hour format

### ISSUE THREAD

**Issue by deepbhavsar** [wdullaer/MaterialDateTimePicker#496]
Hello,

I my device time is 4:45 PM but it is showing selected AM.

It should select PM. What is wrong in it?

```

Calendar calendar = Calendar.getInstance();
TimePickerDialog timePickerDialog = TimePickerDialog.newInstance(new TimePickerDialog.OnTimeSetListener() {
            @Override
            public void onTimeSet(TimePickerDialog view, int hourOfDay, int minute, int second) {

            }
        }, calendar.get(Calendar.HOUR), calendar.get(Calendar.MINUTE), false);

timePickerDialog.show(activity.getFragmentManager(), "");
```

**Comment by wdullaer** [comment]
I don't see anything wrong with that snippet.
Maybe try to ensure the Calendar used in the initialization is in the correct timezone?

**Comment by deepbhavsar** [comment]
@wdullaer 
Hi, I have tried couple of hours and after I got the solution. May be it was silly mistake

it is working fine with `calendar.get(Calendar.HOUR_OF_DAY)`
