### ISSUE TITLE
how to show year only? date picker

### ISSUE THREAD

**Issue by erlangp** [wdullaer/MaterialDateTimePicker#497]

**Comment by wdullaer** [comment]
As mentioned in the FAQ, this is not in scope of this library:
https://github.com/wdullaer/MaterialDateTimePicker#how-do-i-turn-this-into-a-year-and-month-picker

**Comment by erlangp** [comment]
ow.. thanks for your information sir :)

**Comment by wdullaer** [comment]
I have to draw the line somewhere.
You can just use a regular dropdown for the year and the library is open source, so feel free to steal the pieces you need / want :-)
