### ISSUE TITLE
Is there any way to change this to Month Picker [Question]

### ISSUE THREAD

**Issue by LOG-TAG** [wdullaer/MaterialDateTimePicker#50]
How to change this to Month picker? i e showing only month and year!!

**Comment by wdullaer** [comment]
You'll have to fork it, I'm afraid.

It's a Datepicker. The design doesn't make sense if you're not picking dates.
I don't intend to add this.

**Comment by LOG-TAG** [comment]
Thanks will do that, there is up to know there in no Month picker available, best place to contribute :+1:  !!
