### ISSUE TITLE
Month scrolling issues / questions

### ISSUE THREAD

**Issue by DvTonder** [wdullaer/MaterialDateTimePicker#500]
I'm noticing two issues that in not sure how to address

1) the month scrolling is left and right vs. Up and down and 
2) the left and right month toggle arrows are not styled correctly with the dark mode. 

You can see both issues in the attached screenshot. 

https://www.dropbox.com/s/0bvw277vu9xr1jm/Screenshot_20180701-145814.png?dl=0

**Comment by wdullaer** [comment]
The first one can be changed with a method call (which I seem to have not detailed in the README yet)
The second one is a bug I've solved this morning.
I'll try to publish a release this evening.
