### ISSUE TITLE
Date and Time fragment do not use custom colorAccent

### ISSUE THREAD

**Issue by hearbeathorror** [wdullaer/MaterialDateTimePicker#501]
Hi,

I tried updating the library and now use the latest version, added support for version2 using setVersion method, added a custom color in my color.xml file for colorAccent, also set up custom values mdtp_accent_color and mdtp_accent_color_dark, used setAccentColor method, but none of these reflects the custom color i am wanting to use.

Please assist.
Thanks

**Comment by wdullaer** [comment]
I can't immediately reproduce this. `setAccentColor` should do the job.

Keep in mind that you need to give it an actual color, not a resource.
```
dpd.setAccentColor(Color.parseColor("#9C27B0"));
```
or if you have the color in a resource
```
dpd.setAccentColor(ContextCompat.getColor(getActivity, R.color.my_accent_color));
```
