### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by webleaf** [wdullaer/MaterialDateTimePicker#504]
On my Samsung with Android 7.0 `android.app.DatePickerDialog` with `android.app.AlertDialog.THEME_DEVICE_DEFAULT_LIGHT` are displayed with such style:

<img src="http://preview.ibb.co/dag2K8/image.png" width="40%" height="40%">

It looks nice with rounded corners. Is it possible to make ability for control radius of corners in this library?

**Comment by wdullaer** [comment]
The goal is to emulate the material design pickers.

That said, you can probably get this look by overriding some default android resources so that dialogs use rounded corners in general.

**Comment by LaserStony** [comment]
Interesting... @wdullaer, can you shine some light on that?

**Comment by wdullaer** [comment]
As of v4.2.0 you can set the `dialogCornerRadius` attribute in your application theme. (See the sample app for an example).

In previous releases of the v4 series you can use the API 28 attribute `android:dialogCornerRadius`
