### ISSUE TITLE
Somethings wrong when implement both "setTimeInterval" and "setDisabledTimes"

### ISSUE THREAD

**Issue by bnkhoi** [wdullaer/MaterialDateTimePicker#505]
Please help. From the sample code on github. I edited few lines like these:

tpd.setTimeInterval(1, 30);

Timepoint[] disableTimes = new Timepoint[]{
                    new Timepoint(10),
                    new Timepoint(11,30),
                    new Timepoint(12)
            };
tpd.setDisabledTimes(disableTimes);

==> I still can choose the time at :  10:00 , 11:30 and 12:00. But when I deleted the setTimeInterval line then the disableTimes worked again.

Thanks for reading.

**Comment by wdullaer** [comment]
Try using `setTimeInterval(1, 30, 60)`
Internally it always uses seconds. I should probably change the default values of seconds and minutes to 60 rather than 1.

**Comment by bnkhoi** [comment]
It worked. Thank you so much.

**Comment by wdullaer** [comment]
👍
