### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by abolfazlsalmani** [wdullaer/MaterialDateTimePicker#507]
java.lang.NullPointerException: Attempt to invoke interface method 'com.wdullaer.materialdatetimepicker.time.TimePickerDialog$Version com.wdullaer.materialdatetimepicker.time.TimePickerController.getVersion()' on a null object reference

this is my error. i add only xml , test on api 23 emulator

**Comment by wdullaer** [comment]
You cannot add this picker to your project through XML.

It is supposed to be instantiated in your code (it is a modal Dialog popup, not a plain View).
Please take a look at the README.

If you really want to reuse the Views individually, you are in not supported territory.
