### ISSUE TITLE
DatePicker Orientation

### ISSUE THREAD

**Issue by AntoniusAnt** [wdullaer/MaterialDateTimePicker#516]
![1](https://user-images.githubusercontent.com/17191906/43765613-910e410e-9a5a-11e8-8126-81ae4fbc73b6.png)

The datepicker can not open perfectly on landscape orientation using xiaomi redmi note 5, android version 8.1

**Comment by wdullaer** [comment]
Does this happen with the included sample app as well?
Have you overwritten any specific values?

**Comment by nibblesoftworks** [comment]
It works perfectly on sample. 
My bad not to check the sample first. Lol
Ty for ur reply.

**Comment by wdullaer** [comment]
Glad it all worked out :-)
