### ISSUE TITLE
setSelectableDays Not Working

### ISSUE THREAD

**Issue by LaserStony** [wdullaer/MaterialDateTimePicker#519]
I set the Selectable Days using the Function setSelectableDays and it's not working as intended.
It disables every date. The Same outcome is with the setSelectableTimePoints. I made sure that the arrays were not empty and similarly the timepoints and date were rounded off. (i.e simple formats)

**Comment by LaserStony** [comment]
@wdullaer Here: I have pasted the implementation to both the `setSelectableDays` and `setSelectableTimePoints`.

### Initializing Both Pickers as:
```
appointmentDatePicker = DatePickerDialog.newInstance(this);
appointmentTimePicker = TimePickerDialog.newInstance(this, true);
```
### The Setting the Selectable Days and TimePoints
```
ArrayList<Calendar> selectableDays = new ArrayList<>();
ArrayList<Timepoint> selectableTimePoints = new ArrayList<>();
for (ConsultantDaysItem cdi : consultantTimings.getConsultantDays()) 
{
              try {
                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                            Calendar cal = Calendar.getInstance();
                            cal.setTime(sdf.parse(cdi.getDate()));

                            selectableDays.add(cal);

                            SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
                            Calendar cal1 = Calendar.getInstance();
                            cal.setTime(format.parse(cdi.getStartTime()));
                            Timepoint t = new Timepoint(cal1.get(Calendar.HOUR), cal1.get(Calendar.MINUTE));

                            Calendar cal2 = Calendar.getInstance();
                            cal.setTime(format.parse(cdi.getEndTime()));
                            Timepoint t2 = new Timepoint(cal1.get(Calendar.HOUR), cal2.get(Calendar.MINUTE));

                            selectableTimePoints.add(t);
                            selectableTimePoints.add(t2);
             } catch (java.text.ParseException e1) {
                            e1.printStackTrace();
             }
}
Calendar[] selectableDaysArr = new Calendar[selectableDays.size()];
Timepoint[] selectableTimePointArr = new Timepoint[selectableTimePoints.size()];
appointmentDatePicker.setSelectableDays(selectableDays.toArray(selectableDaysArr));
selectableDays.toArray(selectableDaysArr);
selectableTimePoints.toArray(selectableTimePointArr);
appointmentDatePicker.setHighlightedDays(selectableDaysArr);
appointmentDatePicker.setSelectableDays(selectableDaysArr);
appointmentTimePicker.setSelectableTimes(selectableTimePointArr);

```

**Comment by wdullaer** [comment]
I'm guessing the following is happening:
* The parsing of your date is failing, setting the Calendar to EPOCH 0 (which is Jan 1st in 1970)
* The start time and end time of that structure are the same, making it the only viable selection in the Timepicker.

I suggest you inspect the content of the arrays with a debugger to see that the values in there are what you expect.
Alternatively, try to isolate the problem by passing some known good Calendars and Timepoints into the pickers.

**Comment by LaserStony** [comment]
As you weren't replying and the deadline was getting near so I went into it full on with a clread mindset and pretty much did what ypu implied up above... And finally found the solution... Thanks for this Amazing Lib...

**Comment by LaserStony** [comment]
As you weren't replying and the deadline was getting near so I went into it full on with a clread mindset and pretty much did what ypu implied up above... And finally found the solution... Thanks for this Amazing Lib...

**Comment by wdullaer** [comment]
I'm happy you sorted it out.
I'm sorry for the late reply. This is a spare time project, and spare time is eternally scarce unfortunately.

**Comment by LaserStony** [comment]
Yeah... I know what its Like.. No Worries... And Thanks again for this great Lib...
