### ISSUE TITLE
Haptic feedback

### ISSUE THREAD

**Issue by jnordstrom90** [wdullaer/MaterialDateTimePicker#52]
Hi!

I see some code related to haptic feedback for the pickers (like the stock pickers have), is it possible to get that integrated?

**Comment by wdullaer** [comment]
For some reason the vibrate duration was set to 5 ms which is too short to trigger a vibrate it seems. I increased the duration. I'll release a version with the bugfix soon

**Comment by jnordstrom90** [comment]
Cheers :)
