### ISSUE TITLE
Please don't convert the title to uppercase!

### ISSUE THREAD

**Issue by chdh** [wdullaer/MaterialDateTimePicker#526]
In our app it's very disturbing when the title is automatically converted to uppercase. When we want an all-uppercase title, we can convert it ourselves.

**Comment by wdullaer** [comment]
That's the way the design is for now.
Feel free to fork it, so you can tailor it completely to your specific needs.

**Comment by chdh** [comment]
The problem is that it's done with a `toUpperCase()` hard-coded in Java and not with `textAllCaps=true` in the styles definition, like for `mdtp_ActionButton.Text`. The best solution would be to use a variable (attribute reference) in the styles for all occurences of `textAllCaps`.

**Comment by wdullaer** [comment]
I'll add an mdtp_ scoped bool attribute which will set the `textAllCaps`.
You can overwrite this in your app or add it to a theme.

**Comment by chdh** [comment]
@wdullaer Thanks, I will use that.
