### ISSUE TITLE
Add `setMinDate()` and `setMaxDate()` to the docs

### ISSUE THREAD

**Issue by NicoWeio** [wdullaer/MaterialDateTimePicker#528]
So I figured I could use `dpd.setMinDate(Calendar.getInstance());` to achieve that, but
1. `setMinDate()` is only mentioned indirectly in the README: 

> It takes precedence over `setMinDate(Calendar day)`

2. If `setMinDate(Calendar day)` is the correct way, why not add it to the functions list?
3. Maybe it's worth adding a hint to the correct way of doing it in the FAQ section of the README
4. Or even add an extra wrapper to only allow future dates?

**Comment by wdullaer** [comment]
As you have figured out, `setMinDate()` is the correct way to do this.
If you use any decent IDE, it'll show you this method with some docs as well
