### ISSUE TITLE
Support libraries v.28.0.0

### ISSUE THREAD

**Issue by SCpRoION** [wdullaer/MaterialDateTimePicker#529]
Tell me please, are you planning to increase support libraries versions from 27.1.1 to 28.0.0? And when, if you are?

Thanks for your answer and the library!

**Comment by wdullaer** [comment]
I will upgrade the support library versions shortly.
Please also take a look at this FAQ entry: https://github.com/wdullaer/MaterialDateTimePicker#how-do-i-use-a-different-version-of-the-support-library-in-my-app
