### ISSUE TITLE
Leapyear rules in Utils.getDaysInMonth(...)

### ISSUE THREAD

**Issue by Felix246** [wdullaer/MaterialDateTimePicker#53]
In the `getDaysInMonth(...)` method this code is used to determine wether the year is a leap year or not:

```java
case Calendar.FEBRUARY:
    return (year % 4 == 0) ? 29 : 28;
```

With this the year 1700, 1800, 1900, 2000, 2100, ... would all be leap years, but according to [the rules of leap years](http://www.wwu.edu/skywise/leapyear.html):
> There is a leap year every year whose number is perfectly divisible by four - except for years which are both divisible by 100 and not divisible by 400.

the years 1700, 1800, 1900, 2100, ... are *not* leap years. Only 2000, 2400 and so on are leap years.
The code should therefore be something like

```java
case Calendar.FEBRUARY:
    return ( ((year % 4 == 0) && (year % 100 != 0)) || (year % 400 == 0) ) ? 29 : 28;
```

**Comment by wdullaer** [comment]
Which gives me about 85 years (80 if you're working in the automotive sector) to fix this right ;-)

I'll squeeze something in the next time I work on the library.

**Comment by Felix246** [comment]
cool! I was just thinking that when people are selecting dates in the distand past / future they might stumble upon this :D
