### ISSUE TITLE
Can I set time format to 24 hour

### ISSUE THREAD

**Issue by ProIceZa** [wdullaer/MaterialDateTimePicker#531]
**For the TimePicker, Can I change from AM/PM format to 24-hour format?**
**Is your library have something like setIs24HourView(true) of google TimePicker?**
**If you have, Can you show me an example to change the time format?**
Because in my country mostly use 24-hour format. 

Thank.

**Comment by wdullaer** [comment]
It is part of the `newInstance()` method
https://github.com/wdullaer/MaterialDateTimePicker/blob/cbcdf543d16dc800610a44dc1825de836b69a593/library/src/main/java/com/wdullaer/materialdatetimepicker/time/TimePickerDialog.java#L188
