### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by bagus-setyawan** [wdullaer/MaterialDateTimePicker#538]
Implement to version 4.0.1, give me an aapt error while syncing with gradle. It was fine before when i was using 3.2.0 in my project apps.

> Android resource linking failed
> Output:  D:\AndroidStudioProjects\AndroidStudioProjects.bak\Megatrik\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
> D:\AndroidStudioProjects\AndroidStudioProjects.bak\Megatrik\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
> D:\AndroidStudioProjects\AndroidStudioProjects.bak\Megatrik\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:793: error: resource android:attr/fontVariationSettings not found.
> D:\AndroidStudioProjects\AndroidStudioProjects.bak\Megatrik\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:793: error: resource android:attr/ttcIndex not found.
> error: failed linking references.

I am in Android studio 3.2.1 with Gradle version 4.6 and Android plugin version 3.2.1. 
Any help should be appreciated !

**Comment by wdullaer** [comment]
Looking at that error, the build system is complaining that it can't find API 28 platform resources.
I am guessing your app is not using API level 28 as its target API?

**Comment by bagus-setyawan** [comment]
Thanks for your reply and your beautiful project, so this is a compatibility issue. I am targeting sdkVersion 27 and i am using the 3.6.4 release, its work. Will be using the latest for next project. Cheers... !

**Comment by wdullaer** [comment]
I don't think there's any harm targeting API 28.
In fact I think google requires this now for new apps or updates to existing ones.

In any case, I'm happy this resolved the issue.

**Comment by roakoth** [comment]
I am also experiencing the same error. I have minSdkversion 15. And am using 'com.wdullaer:materialdatetimepicker:3.6.4' it builds well but whenever i run the project i get error of android resource linking failed.
How do i solve this?

**Comment by wdullaer** [comment]
Please create a new issue, rather than commenting on old closed ones.

Based on that comment, there's not much I can do.

**Comment by roakoth** [comment]
I was experiencing the same problem yesterday.
Its okay

**Comment by sudhakar-r08** [comment]
This line of code solved my issue. 

configurations.all {
    resolutionStrategy {
        force 'androidx.appcompat:appcompat:1.1.0-beta01'
    }
}

**Comment by ManushreeVis** [comment]
> 
> 
> This line of code solved my issue.
> 
> configurations.all {
> resolutionStrategy {
> force 'androidx.appcompat:appcompat:1.1.0-beta01'
> }
Please may I know, as to where to add this section of code?

**Comment by Mouneshwara** [comment]
I am also getting same error just i removed layout.
In this Line.
    android:layout_orientation="horizontal"
Then i get .
<androidx.appcompat.widget.LinearLayoutCompat
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:layout_orientation="horizontal">
</androidx.appcompat.widget.LinearLayoutCompat>
