### ISSUE TITLE
JalaliDatePicker

### ISSUE THREAD

**Issue by FarajiMehrdad** [wdullaer/MaterialDateTimePicker#54]
I want contribute in  MaterialDateTimePicker to create  jalali Calendar(https://en.wikipedia.org/wiki/Jalali_calendar
) , but I don't know 
how I can do this!
can you help me how can start this?

**Comment by wdullaer** [comment]
I'm not sure what you want me to do here.
I do not know this calendar system, or how it is visualised. This library is relying on the built-in java Calendar classes. If they do not have support for this calendar system, then it will be hard to add support. If they do, then the native android localisation should take care of it mostly.

**Comment by FarajiMehrdad** [comment]
I write jalali calendar  and I know how is work,
but I don't know which class and which function in MaterialDateTimePicker should change?!
if you pleasure and guide me how can change calendar , I can do this.
thank you

**Comment by wdullaer** [comment]
I don't know this calendar system, nor how it is visualised, so I have no idea what you need to change.

The library relies heavily on the default java calendar classes, so unless those offer out of the box support, I'm afraid this will be a large undertaking.

**Comment by Suall1969** [comment]
@FarajiMehrdad It is simple, You just need to import the module into your Android Studio project, and change the Month strings to the "Farvardin", "Ordibehesht", ... then, make use of the JDF class to convert Julian dates to Persian dates as described here: http://stackoverflow.com/a/18076919

BTW, you can just use the https://github.com/alirezaafkar/SunDate_Picker if you want to preserve your time.

@wdullaer Thanks for the great design of pickers.

**Comment by wdullaer** [comment]
If you can make it a pull request, I can try to incorporate this into the library.

**Comment by Suall1969** [comment]
Pleasure, but then it would not support Julian dates anymore.

**Comment by wdullaer** [comment]
That depends on how you've done it I guess.

In any case, I'm happy people are getting good use out of this :-)

**Comment by FarajiMehrdad** [comment]
YA , tanks Saull , I do it

**Comment by SaeedZhiany** [comment]
@wdullaer 

I have started to compare the two repositories and add the codes that related to Jalali calendar system into your codes. but because the other library in not up-to-date, in some situations I can't recognize which line is for codes and which line is not. can you also help with this to me?
you know your codes and you can easily find out which lines in the other library is not up-to-date according to your current repository.

**Comment by wdullaer** [comment]
Thanks for taking the time to look into this.

I haven't had a lot of time to work on this library in the last year. I am doing basic maintenance, but that's really all I have time for at this time.
I will try to review your PR's and help with structure and design. As long as you're willing to incorporate feedback, your PR doesn't need to be perfect.

**Comment by SaeedZhiany** [comment]
Thank you for you great library, recently I tried and merge the other library into yours and fixed some of  its bug causing by merge them together (that already has not been resolved yet in @mohseneo's [repository](https://github.com/mohseneo/JalaliMaterialDateTimePicker))
it currently works great, but I like to have locales for Jalali calendar as well (Persian and English at least) but it's so hard to manage the code with the current structure of code. so maybe I send my current in the next few days and start to implement the calendar system from scratch. I already have found a great library called [Time4A](https://github.com/MenoData/Time4A) by @MenoData that does support many calendar systems around the world with many locales for each calendar system. by that this library can support many calendar systems automatically.

I don't know how much time I can spend on this so anyone that can help please let me know to work together.

**Comment by SaeedZhiany** [comment]
Thank you for you great library, recently I tried and merge the other library into yours and fixed some of  its bug causing by merge them together (that already has not been resolved yet in @mohseneo's [repository](https://github.com/mohseneo/JalaliMaterialDateTimePicker))
it currently works great, but I like to have locales for Jalali calendar as well (Persian and English at least) but it's so hard to manage the code with the current structure of code. so maybe I send my current branch as a separated PR in the next few days and start to replace Android's built-in calendar system. I already have found a great library called [Time4A](https://github.com/MenoData/Time4A) by @MenoData that does support many calendar systems around the world with many locales for each calendar system. by that this library can support many calendar systems automatically.

I don't know how much time I can spend on this so anyone that can help please let me know to work together.
