### ISSUE TITLE
support & androidx

### ISSUE THREAD

**Issue by xiaojiade** [wdullaer/MaterialDateTimePicker#543]
Sorry,my English is not very good.
I change the library version to 4.0.0. But the error still persists.
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
How can I solve this problem?
Look forward to your answer.

**Comment by PedroBarbosaPT** [comment]
Read the first answer:

(Specially the refactor part)

https://stackoverflow.com/questions/50782435/android-design-support-library-for-api-28-p-not-working#50800801
