### ISSUE TITLE
Unable to use library

### ISSUE THREAD

**Issue by pmandroid** [wdullaer/MaterialDateTimePicker#546]
AGPBI: {"kind":"error","text":"error: resource android:attr/fontVariationSettings not found.","sources":[{"file":"C:\\Users\\prashant.mishra\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-27.1.0.aar\\893513250a852d76ee1e347191cb5cac\\res\\values\\values.xml","position":{"startLine":250,"startColumn":4,"startOffset":27058,"endColumn":68,"endOffset":27122}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/ttcIndex not found.","sources":[{"file":"C:\\Users\\prashant.mishra\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-27.1.0.aar\\893513250a852d76ee1e347191cb5cac\\res\\values\\values.xml","position":{"startLine":250,"startColumn":4,"startOffset":27058,"endColumn":68,"endOffset":27122}}],"original":"","tool":"AAPT"}
:app:processDevDebugResources
error: failed linking references.
:app:processDevDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDevDebugResources'.

I am using below library.
implementation ('com.wdullaer:materialdatetimepicker:4.0.1') {
        exclude group: 'androidx.appcompat'
    }

gradle file :: 
 apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion 27
    buildToolsVersion '28.0.0'
    defaultConfig {
        applicationId "com.sew.swg"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 12
        versionName "1.0.11"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

please help.

**Comment by bagus-setyawan** [comment]
#538 Maybe same of my issue here, just target the 28 sdkVersion

**Comment by TylerMcCraw** [comment]
You need to move the `compileOptions` block to the inside of your `android` block.

Also, do you have the following options set in your gradle.properties file?
```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by wdullaer** [comment]
I'm going to assume that @TylerMcCraw comment solved the issue and close this :-)
