### ISSUE TITLE
Turn off vibration

### ISSUE THREAD

**Issue by chongivan** [wdullaer/MaterialDateTimePicker#55]
Hey, could we have a method to turn off vibrations please?

Thanks!

**Comment by wdullaer** [comment]
I should have seen this one coming.
I'll add it to the list

**Comment by chongivan** [comment]
Thanks @wdullaer =)
Love the work!

**Comment by chongivan** [comment]
It works well, @wdullaer. Appreciate your efforts =)

**Comment by CoolMind** [comment]
Hello!
Thanks for a DateTimePicker!
Why is your component vibrate? How can I turn it off?
In https://github.com/wdullaer/MaterialDateTimePicker/issues/116 it is written that a VIBRATION permission should be removed. It is not a good solution.

**Comment by CoolMind** [comment]
So, I removed that permission in Manifest and also wrote:
`            dialog.vibrate(false);
`

**Comment by chongivan** [comment]
Hey @CoolMind,

Vibrations are turned off in the code, as per the README.md:
<img width="791" alt="screen shot 2016-09-07 at 1 24 08 pm" src="https://cloud.githubusercontent.com/assets/801990/18310079/306c29c6-752f-11e6-9d65-6c69c6e494fa.png">

The instructions can be found under [Additional Options](https://github.com/wdullaer/MaterialDateTimePicker#additional-options)

**Comment by chongivan** [comment]
Hey @CoolMind,

The vibrations can be turned off in code as per the **README.md**, found under section [Additional Options](https://github.com/wdullaer/MaterialDateTimePicker#additional-options):
<img width="1005" alt="screen shot 2016-09-07 at 7 13 08 pm" src="https://cloud.githubusercontent.com/assets/801990/18310178/8dc74948-752f-11e6-90fb-743988a4da36.png">
