### ISSUE TITLE
when i build my app it gets error Content is not allowed in prolog.

### ISSUE THREAD

**Issue by sootood** [wdullaer/MaterialDateTimePicker#556]
the coplate of error is 
<myaddname>\app\build\intermediates\exploded-aar\com.wdullaer\materialdatetimepicker\4.0.1\res\font\robotomedium.ttf:1:1: Error: Content is not allowed in prolog.

i cleaned and rebuild it but took this error

**Comment by wdullaer** [comment]
The latest version is 4.1.0, not 4.0.1, can you try with that one.

This sounds like you have something configuration issue in your build tbh. There's not enough information in this issue to help you.

**Comment by sootood** [comment]
i tried to use 4.1.0 but it dosent work 
what information do you need to help i can send you ,
about build configuration i can share my gradle build app

**Comment by weiwenhuaming01** [comment]
same question

**Comment by wdullaer** [comment]
Judging by this https://stackoverflow.com/questions/25145539/android-studio-compile-error-content-is-not-allowed-in-prolog, it is complaining about the `res/font` folder.
This is a feature that has been added in API level 26.
I am guessing you are using a build toolchain that doesn't support this yet. Upgrading to the latest build toolchain and targeting the latest API version should resolve this.
