### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by no-body** [wdullaer/MaterialDateTimePicker#558]
this is what I have when I sync gradle with ` implementation 'com.wdullaer:materialdatetimepicker:4.1.0'`:

`Android resource linking failed
Output:  C:\...\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
C:\...\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
C:\...\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1258: error: resource android:attr/fontVariationSettings not found.
C:\...\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1259: error: resource android:attr/ttcIndex not found.
error: failed linking references.`

the configuration: buildToolVersion 28.0.3, gradle 3.2.1

I tried to add android.useAndroidX=true and android.enableJetifier=true, but I didn't get any difference

Any idea ? thanks!

**Comment by wdullaer** [comment]
Looks like you are not targeting API level 28

**Comment by wdullaer** [comment]
API 28 is required as of v4. Older versions target older APIs.

I don't think you can submit apps or app updates to the play store unless you target that API level, so it's probably worth updating.

**Comment by no-body** [comment]
I know, but I'm not working on a play store app and the device I'm using is on Android 7, so API 24..

**Comment by wdullaer** [comment]
As long as your minimum api level is <= 24 your app will be fully backwards compatible if the target API is 28.
