### ISSUE TITLE
Disabling all selection in the calendar.

### ISSUE THREAD

**Issue by 1715** [wdullaer/MaterialDateTimePicker#559]
I can see that there are options to allow some dates or to block some dates from being selected. But is there an option (or some configuration of options) to block all dates from being selected?
When I pass empty array to setSelectableDays, all days are available for selection.

**Comment by wdullaer** [comment]
What's the point of having a picker when a user can't actually pick a date?

That said, you can implement your own [DateRangeLimiter](https://github.com/wdullaer/MaterialDateTimePicker/blob/master/library/src/main/java/com/wdullaer/materialdatetimepicker/date/DateRangeLimiter.java) and do whatever you want if it isn't supported out of the box.

**Comment by 1715** [comment]
Yeah, I will be happy to implement my own, I just wanted to check with you if it's possible with your out of the box solution.
I think that there is a point in having such a functionality. In my case, I am allowing user to move around his notebook sorted by date. But the datepicker might be used as well. So in a state where the user made no notes yet the datepicker window will be inactive. Of course, you might just prevent the user from accessing datepicker when no dates are available, you are right.
Thanks for quick reply
