### ISSUE TITLE
getSupportFragmentManager() not available in 3.6.4 version

### ISSUE THREAD

**Issue by balajikarthiq** [wdullaer/MaterialDateTimePicker#560]
I'm getting cannot resolve datepickerdialog.show(getSupportFragmentManager, java.lang.string) error in 3.6.4. But when i'm changing the android.support.v4.app.fragment to android.app.fragment i make it work with getFragmentManager() method.

In latest 4.1.1 version, getSupportFragmentManager not available under the namespace android.support.v4.app.Fragment. 

And the latest api level 28 deprecated the android.app.fragment. So how to make it available in common android.support.v4.app? 
(i'm calling the datepicker from fragment)

**In which version of material datepicker getSupportFragmentManager available under the android.support.v4.app?**

**Comment by wdullaer** [comment]
I strongly suggest you take a closer look at the Android docs.
Versions < 4 use regular Fragments, and hence require you to use the regular FragmentManager
As of version 4 this library uses support fragments.
I don't maintain the support libraries themselves.

**Comment by balajikarthiq** [comment]
But supporting androidx and not android.support.v4 ?

**Comment by manikandansai** [comment]
@wdullaer  Do you have the plan to change it Android.Support.V4.App.FragmentManager?
It would be very useful.

**Comment by wdullaer** [comment]
I have no plan to change it to the old support library.
This has been deprecated by google in favor of androidx. Apart from supporting two distinct branches of the library, which I don't have the bandwidth for, there's no way to please everybody here. I will always migrate it too early for some and too late for others.
