### ISSUE TITLE
disable setSelectableDays

### ISSUE THREAD

**Issue by hossambusiness** [wdullaer/MaterialDateTimePicker#562]
setSelectableDays(Calendar[] days)with multi days in array,
And is it possible to get listener when the user click on one of the days before clicking "OK" button

**Comment by wdullaer** [comment]
If `setSelectableDays` does not do what you want, you can implement your own `DateRangeLimiter` with custom logic.

There is no callback in the public API to listen to a user click. There is an internal one, but it's use at your own risk.
