### ISSUE TITLE
Manifest Merger failed

### ISSUE THREAD

**Issue by ersps25** [wdullaer/MaterialDateTimePicker#563]
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-34:19 to override.

**Comment by wdullaer** [comment]
As of version 4, this library uses Androidx rather than the deprecated support library. You should upgrade the dependency to androidx in your own application.

**Comment by ersps25** [comment]
Can you please share the old version, so that I can use it with support library.

**Comment by wdullaer** [comment]
Versions are never retracted.

You are free to use an old version by specifying it in your build.gradle. Check the releases tab to see which ones exist
