### ISSUE TITLE
How can I use this library without migrating Androidx? Thank you.

### ISSUE THREAD

**Issue by mr-yang** [wdullaer/MaterialDateTimePicker#568]
How can I use this library without migrating Androidx? Thank you.

**Comment by wdullaer** [comment]
There's 2 options:
1. You use the latest 3.x release
2. Exclude this libraries androidx dependencies from your build, as described here: https://github.com/wdullaer/MaterialDateTimePicker#how-do-i-use-a-different-version-of-a-support-library-in-my-app
