### ISSUE TITLE
Wrong month

### ISSUE THREAD

**Issue by hearsilent** [wdullaer/MaterialDateTimePicker#57]
![Wrong month](https://cloud.githubusercontent.com/assets/5742579/8639376/b427db74-290a-11e5-95cb-0dea04aac675.png)

**Comment by wdullaer** [comment]
Duplicate of #44 

I can't reproduce this, so a code sample or instructions on how to reliably trigger this behaviour are much appreciated.

**Comment by hearsilent** [comment]
I found the bud is  occurred by timezone.
If I set the timezone is +8, then it will show the wrong month.

**Comment by hearsilent** [comment]
https://github.com/wdullaer/MaterialDateTimePicker/pull/58
