### ISSUE TITLE
Can't resolve method dpd.show

### ISSUE THREAD

**Issue by AyonAB** [wdullaer/MaterialDateTimePicker#570]
date.setOnClickListener(new View.OnClickListener() {
            @Override

            public void onClick(View v) {

                DatePickerDialog dpd = DatePickerDialog.newInstance(CreateAppointmentActivity.this,
                        cal.get(Calendar.YEAR),
                        cal.get(Calendar.MONTH),
                        cal.get(Calendar.DAY_OF_MONTH));
                dpd.show(getSupportFragmentManager(), "Datepickerdialog");
                dateLayout.setError(null);
            }
        });

I'm getting **Cannot resolve method 'show(android.support.v4.app.FragmentManager, java.lang.String)'** error. 
I'm using this in an AppCompatActivity and my imports are correct.

**Comment by wdullaer** [comment]
The library relies on androidx, not the support library.

You'll have to migrate to androidx, or use the last 3.x release (which doesn't use support fragments)
