### ISSUE TITLE
implementation 'com.wdullaer:materialdatetimepicker:4.1.2'

### ISSUE THREAD

**Issue by xyangui** [wdullaer/MaterialDateTimePicker#571]
Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]
/Users/jason/.gradle/caches/transforms-1/files-1.1/appcompat-1.0.2.aar/05c66a8d95a4637d0b57ab9873f0d7b5/res/values-v28/values-v28.xml
Error:(9, 5) error: resource android:attr/dialogCornerRadius not found.
/Users/jason/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/2582ce7d483ffb162855aeefe4cfee6d/res/values/values.xml
Error:(251, 5) error: resource android:attr/fontVariationSettings not found.
Error:(251, 5) error: resource android:attr/ttcIndex not found.
/Users/jason/Desktop/Jianghu/JianghuApp_Android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml
Error:(11) error: resource android:attr/dialogCornerRadius not found.
Error:(7) resource android:attr/dialogCornerRadius not found.
Error:(11) resource android:attr/dialogCornerRadius not found.
/Users/jason/Desktop/Jianghu/JianghuApp_Android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Error:(634) resource android:attr/fontVariationSettings not found.
Error:(634) resource android:attr/ttcIndex not found.
Error:failed linking references.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Information:BUILD FAILED in 2s
Information:12 errors
Information:0 warnings
Information:See complete output in console

**Comment by wdullaer** [comment]
Looks like you are not targeting API level 28.

Please try to make a more readable issue next time. There's not even a question in there, making it hard for me to figure out what it is you want.
