### ISSUE TITLE
Help. How to specify selectable time range

### ISSUE THREAD

**Issue by mdathersajjad** [wdullaer/MaterialDateTimePicker#574]
Is there any way to set the selectable time as range. For example i have two sets of time for a day. 7:00am-12:00 and 13:00pm-18:00pm. Is it possible to set the select the above time as selectable with this library.

**Comment by wdullaer** [comment]
You can compute an array of timepoints at the resolution you want and pass this to the picker. (You probably want minute resolution, so it shouldn't become so large that it has a noticable impact on performance).

If you find that it does impact performance, you can implement your own TimepointLimiter. This is an expert feature though. I recently wrote some documentation for it, but I'm afraid it's still hard to get right without understanding the internals of this library. Only do this as a last resort.
