### ISSUE TITLE
Hour is unselectable but not greyed out

### ISSUE THREAD

**Issue by lucastan96** [wdullaer/MaterialDateTimePicker#575]
I am facing this issue when using setDisabledTimes. I have disabled the whole hour using Timepoint(hour, minute). I am not able to select the hour, but it is not being greyed out for some reason. Please help.

**Comment by wdullaer** [comment]
Can you post some sample code that reproduces this?

The TimeLimiter code is pretty complex and it's perfectly possible that I've missed a specific edge case in the test suite. However, I haven't been able to reproduce what you're describing.
