### ISSUE TITLE
We need a real MaterialDateTimePicker as the repository name describe

### ISSUE THREAD

**Issue by CoderYellow** [wdullaer/MaterialDateTimePicker#577]
https://github.com/wdullaer/MaterialDateTimePicker/issues/350#issuecomment-300742337
It has been 2 years.Here is a [simple implementation](https://github.com/CoderYellow/NFCMeeting-Android/blob/60315d741f7a8dd6372542bc89879767d4c6dff6/app/src/main/java/com/nfcmeeting/nfcmeeting/ui/widget/DateTimePickerDialog.java).But we need an official implementation!

**Comment by wdullaer** [comment]
You can spawn a TimePickerDialog from the callback of the DatePickerDialog, just like you did in your implementation. This is simple enough and doesn't really justify any special support from this library in my opinion.

I experimented with a combined design, but didn't come up with anything that worked well. I am not pursuing it at this point.

**Comment by CoderYellow** [comment]
Another good solution
https://github.com/afollestad/material-dialogs/blob/master/documentation/DATETIME.md
