### ISSUE TITLE
Buttons come with a background when using MaterialComponents

### ISSUE THREAD

**Issue by ashley-figueira** [wdullaer/MaterialDateTimePicker#578]
When using the library with Material Components, the material components will set a background color on the OK and Cancel buttons. 

You have stated that there is not much you can do, but there actual is. All you have to do is to migrate to material components and set the style of the button to style="@style/Widget.MaterialComponents.Button.TextButton".

The TextButton style has a transparent background with colored text. Text buttons are used for low-priority actions, especially when presenting multiple options.

https://material.io/develop/android/components/material-button/

**Comment by wdullaer** [comment]
I do not intend to add an additional dependency to this library.

There is another workaround proposal over here: https://github.com/wdullaer/MaterialDateTimePicker/issues/523#issuecomment-477349333
It's a one line change to your code and avoids the support nightmare of an additional dependency for me.

**Comment by ashley-figueira** [comment]
Thank you for this. Did not notice that comment before.

**Comment by wdullaer** [comment]
No worries, I've added it to the FAQ as well
