### ISSUE TITLE
OnCancel callback

### ISSUE THREAD

**Issue by giorgioprovenzale** [wdullaer/MaterialDateTimePicker#579]
Hello, your work is great, thanks!
Maybe I do something wrong but I can't understand the difference between `setOnDismissListener` and `setOnCancelListener`, they are fired always together. 
My question is, is it possible have a callback fired **ONLY** when the `cancel` button is clicked, and not also when the dialog is dismissed clicking outside the dialog itself?

**Comment by wdullaer** [comment]
These are callbacks defined by the Dialog interface.

IIRC (and it's been a while since I touched that part of the code): hitting the cancel button triggers the OnCancelListener dialog and the Dialog is then dismissed by the framework, triggering the OnDismissListener. It's probably better to think of these as lifecycle hooks, similar to the Activity lifecycle hooks.

**Comment by giorgioprovenzale** [comment]
As I see on your code you have a CancelButton, I think could be useful have a OnClickListener to have a callback ONLY when this button is clicked

**Comment by wdullaer** [comment]
As you can see [here](https://github.com/wdullaer/MaterialDateTimePicker/blob/master/library/src/main/java/com/wdullaer/materialdatetimepicker/date/DatePickerDialog.java#L500), the callback you pass in is triggered when the framework triggers the Cancel callback on the Dialog the picker creates.

This way 'cancel' for the pickers is the same as 'cancel' for every other Dialog you interact with.
https://developer.android.com/reference/android/content/DialogInterface.OnCancelListener.html

I am sorry the frameworks' definition of "cancel" is not what you understand cancel to be, and I do agree that it is not intuitive.

**Comment by giorgioprovenzale** [comment]
Ok, I am agree that it was my misunderstanding, but I think maybe it could be useful have a callback to intercept when the user clicks on the buttons `OK` and `CANCEL`. Like you can edit the text, you can set also a callback to fire an action when these buttons are clicked.

**Comment by giorgioprovenzale** [comment]
I have imported your library and I have added the callback I need, thanks for your big work!

**Comment by wdullaer** [comment]
I am happy you managed to sort it out :-)
