### ISSUE TITLE
make thai calendar

### ISSUE THREAD

**Issue by basriumar12** [wdullaer/MaterialDateTimePicker#582]
how i change like this https://github.com/layerlre/ThaiDateTimePicker ?

**Comment by wdullaer** [comment]
I'm not sure what the question is. If that library does what you want, you should use it :-)

**Comment by basriumar12** [comment]
can i use your library to use thai / budhist calendar ?

**Comment by wdullaer** [comment]
Given that someone forked this library to create that, I'm assuming no.

I also have no intention of extending it to locales I do not know / understand.
If the library you linked doesn't meet your needs you can take a look at the changes it has made. That should give you an idea how much work it would be to apply them to the current master here.
