### ISSUE TITLE
RadialSelectorView.InvalidateUpdateListener seems to leak Context

### ISSUE THREAD

**Issue by archie94** [wdullaer/MaterialDateTimePicker#586]
Related logs can be found at https://github.com/guardianproject/haven/issues/398

**Comment by archie94** [comment]
Also: https://github.com/guardianproject/haven/issues/396

**Comment by wdullaer** [comment]
I'll take a look at that.

I'm also really happy you are using my code in haven! You are doing some great work with that.

**Comment by archie94** [comment]
I have a few other logs which shows `TimePickerDialog` to have leaked. Will post ASAP.

When are you planning the next release?

**Comment by wdullaer** [comment]
Generally a day after I fix a bug (I find it useful to sleep on a fix).
But if you have some other leaks I should take a look at, maybe I can release it all together.
