### ISSUE TITLE
dialogCornerRadius not working

### ISSUE THREAD

**Issue by ItzNotABug** [wdullaer/MaterialDateTimePicker#588]
The above attribute when added in the App theme, adds a rounded corner to every dialog,
however, this doesn't work on Time/Date Pickers..

This should be added. :)

**Comment by wdullaer** [comment]
As of v4.2.0 you can set the `dialogCornerRadius` attribute in your application theme. (See the sample app for an example).

In previous releases of the v4 series you can use the API 28 attribute `android:dialogCornerRadius`
