### ISSUE TITLE
Theme conflict

### ISSUE THREAD

**Issue by xDragonZ** [wdullaer/MaterialDateTimePicker#596]
Using this [library](https://github.com/jaredrummler/Cyanea) caused the OK and CANCEL button for date and time picker to become wrongly themed

**Comment by Jawnnypoo** [comment]
I am seeing this with just the base 4.2.0 dependency, I think it doesn't have anything to do with that library.

**Comment by Jawnnypoo** [comment]
For reference:

![Screenshot_1560068666](https://user-images.githubusercontent.com/1459320/59156758-209d7c80-8a66-11e9-82ca-5dcbcbd8008d.png)

I think this might be something weird with adding the `implementation("com.google.android.material:material:1.0.0")` dependency (moving over to AndroidX). I don't have confirmation, but this seems odd.

**Comment by Jawnnypoo** [comment]
Yep, I think it comes from making your base theme inherit from `Theme.MaterialComponents` instead of `Theme.AppCompat`

**Comment by xDragonZ** [comment]
Yea I think so, that library is using `com.google.android.material` too

**Comment by wdullaer** [comment]
This item is covered in the FAQ
https://github.com/wdullaer/MaterialDateTimePicker#why-do-the-ok-and-cancel-buttons-have-the-accent-color-as-a-background-when-combined-with-the-material-components-library
