### ISSUE TITLE
DatePicker - Day Size

### ISSUE THREAD

**Issue by andremacpereira** [wdullaer/MaterialDateTimePicker#60]
Is it possible to increase the size of the days to pick? They look incredibly small on the tablet I'm working on.

**Comment by wdullaer** [comment]
Can you show me a screenshot and let me know the resolution and physical size of the display?
I'm testing this on a 10 inch tablet and everything looks fine.

**Comment by andremacpereira** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8026858/8679245/d9bfc3bc-2a2f-11e5-88a0-20d951bc1c0b.png)

This is how it looks like on a 7 inch landscape screen. It's awesome, but the day to select is so tiny!

**Comment by wdullaer** [comment]
I'll experiment a bit. It doesn't look too different than on my 10 inch tablet here, but I can see why you'd like it a bit bigger.

I'm happy to see you using the dark layout, I didn't know how much demand there was for that.

**Comment by andremacpereira** [comment]
Just imagine old people using it.. they would probably find it difficult. Most of DatePickers work this way around. I wish I knew how to increase it's size.

I'm not using the Dark Layout for now but yes, it could be useful in the future. :-)

Excellent job, by the way!

**Comment by wdullaer** [comment]
Copyright issues on a screenshot of my library, there's something new.

I don't think I'm going to increase the font size, I'm pretty happy the way it is. If you absolutely want to you can overwrite `mdtp_day_number_size`. The default value is 12sp
