### ISSUE TITLE
Using the day night theme causes the buttons to be fully colored

### ISSUE THREAD

**Issue by droidluv** [wdullaer/MaterialDateTimePicker#600]
Using themes like Theme.MaterialComponents.DayNight.NoActionBar causes the buttons to be fully colored and the text won't be visible because of automatic conversion of all <Button> to <MaterialButton>

**Comment by wdullaer** [comment]
Did you read this item in the FAQ on combining the material components library with this library?
https://github.com/wdullaer/MaterialDateTimePicker#why-do-the-ok-and-cancel-buttons-have-the-accent-color-as-a-background-when-combined-with-the-material-components-library
