### ISSUE TITLE
Cannot resolve method 'show(android.app.FragmentManager, java.lang.String)'

### ISSUE THREAD

**Issue by spapapan** [wdullaer/MaterialDateTimePicker#608]
Inside android.app.Fragment I am using this code:

```
Calendar now = Calendar.getInstance();
        DatePickerDialog dpd = DatePickerDialog.newInstance(
                this,
                now.get(Calendar.YEAR), // Initial year selection
                now.get(Calendar.MONTH), // Initial month selection
                now.get(Calendar.DAY_OF_MONTH) // Inital day selection
        );
```

None of the below works:

` dpd.show(getActivity().getFragmentManager(), "Datepickerdialog");`
` dpd.show(getActivity().getSupportFragmentManager(), "Datepickerdialog");`

I see inside your sample code you use a function called

> requireFragmentManager()

but when I try to use it I get 

> cannot resolve method requireFragmentManager

I need help please.

**Comment by wdullaer** [comment]
What sdk version are you targeting?

**Comment by spapapan** [comment]
> What sdk version are you targeting?


27

> Also double check that the DatePickerDialog is the one provided by this library and not the framework one in your imports

I already checked it.

**Comment by wdullaer** [comment]
As of version 4 this library expects to be used with the support library. The sample doesn't use a regular activity but an AppCompatActivity.

Similarly the show method from the `AppCompatDialogFragment` that this picker extends takes the androidx FragmentManager, not the one supplied by the framework.

The recommendation from the android team is to use the support library / androidx where possible, which is what most apps do.
If you wish to use framework supplied activities and fragments, you have to use the (unsupported) versions < 4

**Comment by spapapan** [comment]
Which is the most stable version that it's <4 ?

**Comment by spapapan** [comment]
I used 3.6.4 and it worked fine. Thanks a lot, great library!
