### ISSUE TITLE
setMinTime, setMaxTime?

### ISSUE THREAD

**Issue by adammbalogh** [wdullaer/MaterialDateTimePicker#61]
Do you plan a min/max time implementation for hours and minutes?

**Comment by wdullaer** [comment]
Not immediately.
I'll keep it in the back of my head should I revisit that bit of the code

**Comment by markmooibroek** [comment]
+1 =)

**Comment by mafiu** [comment]
+1

**Comment by kenumir** [comment]
+1

**Comment by emilianobonassi** [comment]
+1
