### ISSUE TITLE
Show DateTimePicker from Activity

### ISSUE THREAD

**Issue by Grch** [wdullaer/MaterialDateTimePicker#610]
Hi! Thank you for the great library.
I can't find the way of how to `show` the DateTimePicker from the activity. The `show()` method requires a `FragmentManager` as the 1st parameter. Could you please help me?

**Comment by wdullaer** [comment]
This is explained in the first section of the readme.
You can get a reference to the SupportFragmentManager using a method on an Activity
https://developer.android.com/reference/androidx/fragment/app/FragmentActivity.html?hl=en#getSupportFragmentManager()
