### ISSUE TITLE
conflict

### ISSUE THREAD

**Issue by travellers** [wdullaer/MaterialDateTimePicker#615]
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:9:5-25:19 to override.

**Comment by maxprig** [comment]
I have same problem :c

**Comment by wdullaer** [comment]
This library relies on androidx, the successor to the support library.
They are incompatible with each other (because the jvm can only load 1 version of each class).

You either have to upgrade to androidx in your application, or use a pre v4 version of this library.
