### ISSUE TITLE
Disable current day from being highlighted

### ISSUE THREAD

**Issue by ronykrell** [wdullaer/MaterialDateTimePicker#622]
Hi, is it possible to disable the current day from being highlighted initially? I tried setting the selected day really far back so it wouldn't highlight - still highlights it :)

In MonthAdapter.java ~line 139
` protected void init() {
 mSelectedDay = new CalendarDay(0, mController.getTimeZone());
     }
`

In DayPickerView.java ~ line 85
```
protected void setController(DatePickerController controller) {
           mController = controller;
           mController.registerOnDateChangedListener(this);
           mSelectedDay = new MonthAdapter.CalendarDay(mController.getTimeZone());
           mSelectedDay = new MonthAdapter.CalendarDay(0,mController.getTimeZone());
          mTempDay = new MonthAdapter.CalendarDay(mController.getTimeZone());
          refreshAdapter();
     }
```

**Comment by wdullaer** [comment]
You change the default selection in the `newInstance()` method. I've added an example to the sample app.
The current day is always rendered in the accent color, just like it is in the framework picker
