### ISSUE TITLE
Allowed day is sporadically getting greyed out

### ISSUE THREAD

**Issue by ronykrell** [wdullaer/MaterialDateTimePicker#623]
Hi, I'm using a DateRangeLimiter to disable all days before the following week's Monday. 
There's a funny issue where sometimes the Monday is greyed out. 90% of the time it's enabled-colored (expected behavior), but 10% of the time the day is greyed out - it works appropriately if the user taps on it. It's just the initial rendering greys it out.

I've tried debugging and stepping through the code, and can tell something different is happening in the cases where it's being greyed out.

**Comment by wdullaer** [comment]
You don't need a custom `DateRangeLimiter` for this. You should use `setMinDate()` with the appropriate value.
The `DateRangeLimiter` is hard to implement with very subtle interactions between its various methods. It is highly likely you made a mistake there.

**Comment by ronykrell** [comment]
Thanks for the response. The date range limiter also disables all weekends. Is that something that can be done through alternate means as well?
