### ISSUE TITLE
time picker crashes 

### ISSUE THREAD

**Issue by kasusa** [wdullaer/MaterialDateTimePicker#638]
I have an issue !
I used datepicker and time picker on the same activity.
and if i select the time picker first. The app CRASH!
But if i select the **Date picker** first and **pick time** after that , everything will be fine?
WHY??

**Comment by kasusa** [comment]
sorry
is my fault...
```java
 fragmentManager =getSupportFragmentManager(); // <<< i forget this line!
 timePickerDialog.show(fragmentManager, "TimePickerDialog");
```

**Comment by wdullaer** [comment]
:+1:
