### ISSUE TITLE
Old datepicker layout

### ISSUE THREAD

**Issue by neokree** [wdullaer/MaterialDateTimePicker#64]
Hi, based on the current material design site, your library implements the old layout:

http://www.google.com/design/spec/components/pickers.html

This should be the new:
<img src="http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3321sZLoP_HVWZOVkdRQlJEdDg/components_pickers_date1.png" />

Please update the layout. Thanks!

**Comment by wdullaer** [comment]
duplicate of #62
