### ISSUE TITLE
Hide parts of the layout

### ISSUE THREAD

**Issue by EvertonBorges** [wdullaer/MaterialDateTimePicker#656]
Is there a way to hide some areas of the layout? If there is currently no such possibility, that's fine, it's just something I haven't found.
1) Hide the header layout that contains the selected year, month and day.
2) Is it possible to hide navigation for months and do it manually?

In the DatePickerDialog class I found the attribute "mMonthAndDayView" I believe that leaving it editable or some Boolean variable to control this would be enough or some things in that sense.

You did an excellent job on that component.

**Comment by wdullaer** [comment]
Other than the optional 'title' row you cannot hide any components.

I don't intend on supporting too much customization on this front. The layout is already very brittle as it is.
It's something that you should be able to do in your own fork.

The arrow buttons are not present in the version1 layout, but that one takes up even more vertical real estate, so I doubt it'll fit your usecase.

**Comment by EvertonBorges** [comment]
Yes, the component is very brittle, but in a project I need some customizations to meet a requirement.
So, probably do a fork is the best way.

Thanks
