### ISSUE TITLE
Minor Bug - Date picker month navigation arrows are inverted in RTL layouts

### ISSUE THREAD

**Issue by mhdwajeeh95** [wdullaer/MaterialDateTimePicker#657]
Simply fixed by adding `android:autoMirrored="true"` to both vector drawables `mdtp_ic_chevron_left_black_24dp` and `mdtp_ic_chevron_right_black_24dp.xml` for API 21 and above.

![image](https://user-images.githubusercontent.com/20627453/79472004-fdd7df00-800b-11ea-8bf9-50932d0ebf9c.png)

**Comment by wdullaer** [comment]
Thanks for the report and pointing me in the right direction :)

The min API level of this library is 16. I can't use any attributes that have a higher min API level.
I made a dedicated layout which swaps the images. This will solve it on all API versions that support RTL layouts.

**Comment by mhdwajeeh95** [comment]
Thanks. Your efforts are much appreciated. 😀

**Comment by tarek13** [comment]
this fix not include in version 4.2.3
how to get it with out import library as module in android studio

**Comment by charlieaboumoussa** [comment]
Hello, yes please this fix should be included, and there is also a weird behavior when using it in RTL locale. When changing months, sometimes it jumps suddenly to a very far date (current month if minDate is set)
