### ISSUE TITLE
Feature request: Make whole header section toggleable

### ISSUE THREAD

**Issue by stefan-niedermann** [wdullaer/MaterialDateTimePicker#658]
Hi, when using the DatePicker, i find it really hard to 1. discover the "YearPicker" and 2. actual toggle between the calendar and the year picker.

It took me 10 minutes to realize that the header view is split into two clickable areas (the little year and the bigger selected date).

It would be (IMHO) much better usability to toggle between the year and the calendar view no matter where exactly in the header area you click. Basically just make the whole header a giant toggle-button :)

Great lib btw, thank you :) It just got a few hundred endusers more.

**Comment by wdullaer** [comment]
Thanks for the compliment.

I understand your sentiment. I only found out you could toggle between these views when I initially forked this off of the google code.

However, the goal of the library is to backport the framework picker back to older version of android. So as long as the "official" picker works in this way, I'd like to keep the datepicker in this library work the same way.

**Comment by stefan-niedermann** [comment]
Pitty, but i understand your reasons... :disappointed:
