### ISSUE TITLE
DatePicker shows wrong day in certain timezones

### ISSUE THREAD

**Issue by GuillaumeDelente** [wdullaer/MaterialDateTimePicker#66]
![screen shot 2015-07-21 at 11 01 50 am](https://cloud.githubusercontent.com/assets/447889/8804061/4f31012a-2f98-11e5-851b-429974f366ab.png)

This is happening with device Time Zone set to GMT+13.

**Comment by wdullaer** [comment]
Which version are you using?

Also: did you force kill the app after changing the timezone on your device? 
The top view and calendar view have different caching strategies for the locale.

**Comment by GuillaumeDelente** [comment]
@wdullaer looks like it's a caching issue indeed - force stop did the trick.
