### ISSUE TITLE
Landscape mode - buttons are not displayed right

### ISSUE THREAD

**Issue by masztalski** [wdullaer/MaterialDateTimePicker#68]
In landscape mode buttons OK and Cancel on Lenovo A800 seem to be wrong placed:
![screenshot_2015-07-24-11-12-13](https://cloud.githubusercontent.com/assets/11578875/8873504/9c1c3452-3207-11e5-909d-07f82cecf019.png)

**Comment by mohamad-amin** [comment]
@wdullaer Should the `mdtp_done_button.xml` layout be placed below the `mdtp_date_picker_selected_date.xml` or it's a bug?
