### ISSUE TITLE
The Displayed Months Are Different

### ISSUE THREAD

**Issue by neonankiti** [wdullaer/MaterialDateTimePicker#69]
Is it a bug? When I create a instance of DatePickerDialog and pass month = 6(July) to the constructor of it, the results shows as the picture below. the calendar month is strange(June should be July)

![image](https://cloud.githubusercontent.com/assets/6552589/8896170/a0525a46-342e-11e5-9452-40dc7e3719ef.png)

**Comment by wdullaer** [comment]
Do you have the latest version?

Op ma 27 jul. 2015 00:12 schreef neonankiti <notifications@github.com>:

**Comment by neonankiti** [comment]
oh, my version was 1.3.1. updated and fixed. thank you!
