### ISSUE TITLE
Crash when "Ok" and "Cancel" are pressed at the same time

### ISSUE THREAD

**Issue by mauriDantonio** [wdullaer/MaterialDateTimePicker#71]
Sometimes, when both buttons are pressed the app crashes for a null pointer exception at line with "getDialog().cancel();". You can fix it surrounding it with "if getDialog() != null"

**Comment by wdullaer** [comment]
I tried for a few minutes and couldn't pull this off, but I'll take you on your word and put this in for the next release.

**Comment by mauriDantonio** [comment]
I know, it's not easy to reproduce, but if you try a few times you'll get the crash :)
Btw, you library it's awesome!
