### ISSUE TITLE
Change DatePickerDialog's button texts

### ISSUE THREAD

**Issue by fowah** [wdullaer/MaterialDateTimePicker#72]
Instead of overwriting the string mdtp_cancel and mdtp_ok, can I have a feature to set the button text programmatically, like normal date picker dialog does?

setButton(int whichButton,
          CharSequence text,
          DialogInterface.OnClickListener listener)

For why I ask for this is because I have different scenario that date picker dialog and time picker dialog will show different button texts serving for two different actions.

**Comment by Rainer-Lang** [comment]
+1
