### ISSUE TITLE
Dont know is AM or PM

### ISSUE THREAD

**Issue by diargegaj** [wdullaer/MaterialDateTimePicker#722]
If I have 24hour mode false and OnTimeSetListener how to know if the user select AM or PM, I checked all possible methods but can't found anything who tells.

**Comment by Hiten645** [comment]
Here hour is giving you in 24 hours format but for the user in the ui it gives you 12 format hour view so you can easily get am or pm by using if else 
`if (hourOfDay > 12){
String time = hourOfDay + "/" + minute + "pm";
}else {
String time = hourOfDay + "/" + minute + "am";
}`
