### ISSUE TITLE
Getting border/outline in the timepickerview

### ISSUE THREAD

**Issue by americosfacebook** [wdullaer/MaterialDateTimePicker#73]
Getting border/outline in the timepickerview in non lollipop Android Version devices. Need fix for this issue.Please post solution ASAP. 
Thnak you

**Comment by wdullaer** [comment]
You're going to have to do better than this, for example a screenshot of the issue would be nice.

I would also dim the attitude if you want people to solve your problems for free ...

**Comment by americosfacebook** [comment]
Hi wdullaer,

Yes, surly  do other people to solve the issue and here are the screen shots of the issue:

Border/Outline Issue in Android OS Version : 4.3,4.1.2
--------------------------------------------------------------------
![screenshot_2015-08-03-13-00-49](https://cloud.githubusercontent.com/assets/11418844/9020686/bf1665ae-3838-11e5-97c1-29d94ee8a28f.png)
--------------------------------------------------------------------
Working fine in Android OS Version: 5.0
--------------------------------------------------------------------
![screenshot_2015-10-04-10-36-15](https://cloud.githubusercontent.com/assets/11418844/9020714/519110f4-383a-11e5-94d1-02330ac6a092.png)

Thanks for your positive reply.

Regards,
Android Team

**Comment by wdullaer** [comment]
I don't think this is due to this library.
I test this on two separate pre-lollipop devices and it renders just fine.

My guess is that this is due to the theme your manufacturer applies to the device.
Do other Dialogs on the device have those insets as well?
