### ISSUE TITLE
Why dont you use android.support.v4.app.DialogFragment instead of android.app.DialogFragment?

### ISSUE THREAD

**Issue by Holoceo** [wdullaer/MaterialDateTimePicker#75]
Everyone uses support.v4.app.Fragment and AppCompatActivity. It's impossible to pass android.app.DialogFragment to your dialogs.

**Comment by wdullaer** [comment]
Please read some of the older issues on this to find out why:
a) Your statement is incorrect and this library can be used with AppCompatActivity
b) I'm not going to change it
