### ISSUE TITLE
Styling DatePicker/TimePicker

### ISSUE THREAD

**Issue by ingpeternemec** [wdullaer/MaterialDateTimePicker#77]
Very good library, thanks. But aj need styling picker dynamically. I have defined 12 color styles for my app and user can choose from them. I can style your DatePicker by 
    <color name="mdtp_accent_color">#242424</color>
    <color name="mdtp_accent_color_dark">#282828</color>
but it is static. Can I setTheme of your Dialog DatePicker ? Or set color programatically (setAccentColor, setAccentColorDark)? 
Thanks
Best regards
Peter

**Comment by wdullaer** [comment]
This is the same request as #15 

It's somewhere on the todo list, but I'll probably not get around to it in the near term.

**Comment by Jawnnypoo** [comment]
I am looking into it.
