### ISSUE TITLE
Weekday labels not fully visible under some circumstances

### ISSUE THREAD

**Issue by maniac103** [wdullaer/MaterialDateTimePicker#78]
We're using MDTP in our app and a Hebrew user complains about the day-of-week labels not being properly visible for him. The device is a 480x800 hdpi phone.

A screenshot of the issue can be found here: http://i.imgur.com/CYdyzIV.png

**Comment by wdullaer** [comment]
This is either an RTL issue or a truncate issue.

I truncated the name of the day to the first letter. I should check whether I account for RTL (I think I do). If all the names of the day start with the same character in hebrew, this is what it would look like.

(Imagine truncating to the last character in english, they'd all say 'y')

I do not speak nor read Hebrew, so there is no way for me to devise a workaround for this, without some external input. (I have merged a pull request which solves a similar issue in Chinese in the past)

**Comment by siiie** [comment]
I believe it's not a truncate issue:
* On my nexus 7, it looks the same
* Saturday appear correctly
* The other days do not use a letter char that belong to the name of the day (not the first letter)
* In Hebrew we do not use the first letter for days Sunday-Friday, we use the first six letters of the Hebrew language (ref image http://imgur.com/zGhqQnp)

**Comment by wdullaer** [comment]
This is useful information.
I suppose I'll have to make a separate case if the locale is set to hebrew.

@siiie would you be ok in testing out a feature branch of this? (once I get around to taking a look at it, which might take a few days)

**Comment by siiie** [comment]
@wdullaer No problem, i'll be glad to help

**Comment by siiie** [comment]
After some tests, I think the char we actually see is ' .
Take a look at that code:
```
Calendar calSet = Calendar.getInstance();
		calSet.set(Calendar.DAY_OF_WEEK, 1);

		SimpleDateFormat formatLetterDay = new SimpleDateFormat("EEEEE",new Locale("he-IL"));
		String letter = formatLetterDay.format(calSet.getTime());

```

That would show the short day of the week (Sunday) like that: 'א

Hope that could help you solve it

**Comment by wdullaer** [comment]
Your code didn't exactly yield the results you said, but they did put me on the right track.
I managed to make the labels look like on the imgur example.
