### ISSUE TITLE
Bug in small screen size devices

### ISSUE THREAD

**Issue by Ghostish** [wdullaer/MaterialDateTimePicker#83]
I tested it in my LG p990 whose screen size is 480*800 . The datePicker can't scroll to the other pages which means that I can only pick a date in current month.

**Comment by wdullaer** [comment]
Is that because the dialog itself scrolls? (I recently added some scrollviews around the content)

**Comment by Ghostish** [comment]
@wdullaer  Unfortunately no, the dialog doesn't scroll and the content in the dialog doesn't scroll either.

**Comment by Ghostish** [comment]
@wdullaer Maybe this time it's a OS problem ? I then tested it on a virtual device with a 720*1280 screen on Android 4.1.1 (in fact it's a virtual Galaxy Nexus) . The problem still exist . Then I tested it on a virtual Moto X whose screen size is also 720*1280 on Android 4.4.4 , the picker worked as expected.

**Comment by Ghostish** [comment]
@wdullaer  I've found that even though I can't scroll the picker with finger swiping ,  I can scroll it with the mouse wheel when using a virtual device

**Comment by PavelSynek** [comment]
I have the same problem on physical Android 4.1.1 480x800 device. Everything was ok in 1.4.2, so it looks like [this commit](https://github.com/wdullaer/MaterialDateTimePicker/commit/2cbc89f270a5bcf5c1c647fa15a9f9b5b5fd511f) caused it.

**Comment by wdullaer** [comment]
@PavelSynek That is exactly what I thought, but I can't reproduce the behaviour on my devices, which is why I was still asking some questions.
I'll release a new version this evening.

**Comment by petrica5800** [comment]
I found same problem on Android 4.2.2 devices, i can't scroll to select next month or next year.
