### ISSUE TITLE
How to add seconds?

### ISSUE THREAD

**Issue by cabuhatprince** [wdullaer/MaterialDateTimePicker#87]

**Comment by wdullaer** [comment]
Setting time up to seconds is not supported by this library.
The scope of the library is to implement the Date and Time Pickers as shown in the material design guidelines. Picking seconds is not included, so I probably won't be adding this feature.

**Comment by freezy** [comment]
Would you accept a PR for this as an opt-in feature?

**Comment by wdullaer** [comment]
If it's well done and easily supportable, sure.

**Comment by freezy** [comment]
[There you go :)](https://github.com/wdullaer/MaterialDateTimePicker/pull/104)
