### ISSUE TITLE
Can I show show year picker first?

### ISSUE THREAD

**Issue by adolfdsilva** [wdullaer/MaterialDateTimePicker#90]
What i want is when the DatePickerDialog appears, it ask for the user to select year instead of date.
Thanks!!!

**Comment by wdullaer** [comment]
Currently not, but it's something I can add.

**Comment by adolfdsilva** [comment]
It'll be really intuitive for using the date picker as DOB picker.

**Comment by adolfdsilva** [comment]
Thanks!!!

**Comment by Dellkan** [comment]
Hi @wdullaer. Thanks for adding this, I need this as well.

Would you mind releasing another version on bintray with this feature?

**Comment by wdullaer** [comment]
should be up on maven central soon
