### ISSUE TITLE
Can't change month and year.

### ISSUE THREAD

**Issue by spaine** [wdullaer/MaterialDateTimePicker#93]
I can't seem to change month or year. Scrolling doesn't work. Though this problem only seem to exist on my HTC One X+ running 4.1.1.

All other phones functions normally.

**Comment by wdullaer** [comment]
I'm sorry, there's not much I can do here.
I test this on 4 devices.
If you can give me detailed steps on how to reproduce this, eg on the emulator, I can take a look at it.
