### ISSUE TITLE
Error:Failed to resolve: com.wdullaer.materialdatetimepicker:1.5.2: build.gradle"

### ISSUE THREAD

**Issue by Spiderbezno** [wdullaer/MaterialDateTimePicker#94]
This version can be resolved and aslo the same for 1.5.1

**Comment by Spiderbezno** [comment]
In the realese note has an erro the right code is com.wdullaer:materialdatetimepicker:1.5.2

**Comment by wdullaer** [comment]
Thanks for the heads up. Fixed now.
