### ISSUE TITLE
DatePickerDialog day TextView greyed out

### ISSUE THREAD

**Issue by MrBrightside29** [wdullaer/MaterialDateTimePicker#95]
If you reopen the DatePickerDialog after being shown for the first time and instantiated outside the OnClickListener, the day TextView for the selected date appears greyed out.

```
DatePickerDialog datePickerDialogStart = DatePickerDialog.newInstance(this, calendar.get(Calendar.YEAR), calendar.get(Calendar.MONTH), calendar.get(Calendar.DAY_OF_MONTH));
     
layoutDateStart.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                datePickerDialogStart.show(getFragmentManager(), DATEPICKER_START_TAG);
            }
 });
```
![screenshot_2015-09-17-13-46-32](https://cloud.githubusercontent.com/assets/6217462/9932424/0277c826-5d44-11e5-8ba4-7ee1873dd245.png)

**Comment by wdullaer** [comment]
What you're saying is that if you instantiate the dialog from within the onClickListener, the text color is fine?

**Comment by MrBrightside29** [comment]
Yes, that's right. I want to avoid instantiating every time I show the picker.

**Comment by wdullaer** [comment]
I think I understand why this is happening, I'll probably solve it when I implement #90 

Might I ask why you want to avoid instantiating the picker? I understand that instantiating a Fragment is rather resource intensive, but that's actually a reason to lazy load it in the onClickListener rather than upfront.

**Comment by MrBrightside29** [comment]
Well, in my case it won't make too much difference from instantiating inside the onClickListener to outside, so I guess I could change the code. Anyway, thanks for your fast reply.
