### ISSUE TITLE
Time in AM and PM format 

### ISSUE THREAD

**Issue by Mandeep221** [wdullaer/MaterialDateTimePicker#96]
Hi, It would probably sound very silly but i was not able to find a way to get the timepicker dialog to show time in AM PM format. It shows Time in 24 hr format by default. It would be great if you tell me how i can get it in AM and PM. Thanks!

**Comment by wdullaer** [comment]
A look at the code in the example, or the spec for the `TimePickerDialog.newInstance` method would have shown you the path to enlightenment:

```java
public static TimePickerDialog newInstance(OnTimeSetListener callback,
            int hourOfDay, int minute, boolean is24HourMode) {}
```
I should update the docs to document the full API in more detail at some point.

**Comment by Mandeep221** [comment]
Thanks alot!
