### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by hearsilent** [wdullaer/MaterialDateTimePicker#97]
http://www.google.com/design/spec/components/pickers.html#pickers-date-pickers

**Comment by tuxmobil** [comment]
To my eyes, and compared to the stock TimePicker, the stroke width in RadialSelectorView:308 looks a bit thin.

**Comment by mshearer123** [comment]
Any idea if the new design will be used at some stage?

**Comment by wdullaer** [comment]
Fixed in version 3.0.0
